### ISSUE TITLE
[Bug] Zeitwerk Dependency Required And Wrong Nokogiri installed

### ISSUE THREAD

**Issue by skycat2216** [gushmazuko/metasploit_in_termux#100]
**Describe the bug**
I'll describe it very quick,if my words offend anyone,I have to apologize in here.
First,Ruby recently removed net-stmp/net-imap/net-pop from default gems.
So Zeitwerk is down.
Before developers fix this,please add these gems into Gemfile.lock file manually and run:
```
bundle install
```
To fix dependency errors.
And next thing is the script installed wrong version of Nokogiri.
Again,please install it with these command:
```
pkg install ruby clang make binutils pkg-config libxslt
gem install nokogiri --platform=ruby -- --use-system-libraries
gem uninstall nokogiri
```
and choose the options with aarch64-linux
Before developers fix it.
[About]
https://github.com/mikel/mail/pull/1439
https://stackoverflow.com/questions/70500220/rails-7-ruby-3-1-loaderror-cannot-load-such-file-net-smtp
https://github.com/termux/termux-packages/discussions/8855
https://nokogiri.org/tutorials/installing_nokogiri.html

**Smartphone (please complete the following information):**
 - Device: Realme X50
 - OS: Android 10

**Comment by skycat2216** [comment]
I think I have to left it open for everyone have same problem

**Comment by hackglitz** [comment]
Before developers fix this,please add these gems into Gemfile.lock file manually



How to do that please explain

**Comment by skycat2216** [comment]
![Screenshot_2022-03-06-23-46-38-47_84d3000e3f4017145260f7618db1d683~2](https://user-images.githubusercontent.com/33820902/156930647-d00dad2f-e143-4fed-8b60-19a116336df2.jpg)
![Screenshot_2022-03-06-23-47-00-97_84d3000e3f4017145260f7618db1d683~2](https://user-images.githubusercontent.com/33820902/156930650-7a8679eb-9391-4dc5-a90a-216cd5841c90.jpg)

**Comment by hackglitz** [comment]
Thanks a lot.. fixed

**Comment by gushmazuko** [comment]
Fixed https://github.com/gushmazuko/metasploit_in_termux/commit/280f656e1dfc0ef8a866218346d3db651e87aac3
