### ISSUE TITLE
ERROR:  Loading command: install (LoadError)         dlopen failed: library "libssl.so.1.1" not found: needed by /data/data/com.termux/files/usr/lib/ruby/2.7.0/aarch64-linux-android/openssl.so in namespace (default) - /data/data/com.termux/files/usr/lib/ruby/2.7.0/aarch64-linux-android/openssl.so ERROR:  While executing gem ... (NoMethodError)     undefined method `invoke_with_build_args' for nil:NilClass ERROR:  Loading command: install (LoadError)         dlopen failed: library "libssl.so.1.1" not found: needed by /data/data/com.termux/files/usr/lib/ruby/2.7.0/aarch64-linux-android/openssl.so in namespace (default) - /data/data/com.termux/files/usr/lib/ruby/2.7.0/aarch64-linux-android/openssl.so ERROR:  While executing gem ... (NoMethodError)     undefined method `invoke_with_build_args' for nil:NilClass ERROR:  Loading command: install (LoadError)       

### ISSUE THREAD

**Issue by 11092004** [gushmazuko/metasploit_in_termux#101]
**Important**
Do not duplicate, search your issue before creating one!

**Describe the bug**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 8]
 - OS: [e.g. Android 10]
![Screenshot_2022-03-05-11-45-09-113_com termux](https://user-images.githubusercontent.com/100334195/156870947-6a67f61c-5d0b-4d3f-a420-f6cb8ee93298.jpg)

**Comment by 11092004** [comment]
I have tried reinstalling it numerous times but every time I run into these issues

**Comment by ajithlak18** [comment]
same here no solution is given my team

**Comment by dedshit** [comment]
lol use latest version

**Comment by skycat2216** [comment]
Check my issue that I've reopened.
https://github.com/gushmazuko/metasploit_in_termux/issues/100

**Comment by 11092004** [comment]
> lol use latest version

Using the latest version

**Comment by dedshit** [comment]
send screesnshot

**Comment by 11092004** [comment]
> send screesnshot

![Uploading Screenshot_2022-03-06-19-06-40-304_com.termux.jpg…]()

**Comment by 11092004** [comment]
> send screesnshot

![Screenshot_2022-03-06-19-06-40-304_com termux](https://user-images.githubusercontent.com/100334195/156925655-0f50a1d8-4fbc-46be-be87-b38bbc6e8728.jpg)

**Comment by dedshit** [comment]
did u reinstalling mstasploit or termux ?

**Comment by 11092004** [comment]
> did u reinstalled metasploit or termux ?

I tried to do so many times but again again I get a issue

**Comment by skycat2216** [comment]
Do you ran 
```
pkg upgrade
```
before?

**Comment by 11092004** [comment]
> Do you ran
> 
> ```
> pkg upgrade
> ```
> 
> before?

Yes I did

**Comment by skycat2216** [comment]
Can you check your version of ruby and openssl??
It should be 3.1.0p0 and 3.0.1
Or just check the status of openssl 1.1

**Comment by MohammedAlkadasi** [comment]
I got a solution to all the problems related to this project. First, you have to install the latest Termux version and delete all its data. Second, the automatic installation by this link : source <(curl -fsSL https://bit.ly/36UvNhV)

**Comment by MohammedAlkadasi** [comment]
I got a solution to all the problems related to this project. First, you have to install the latest Termux version and delete all its data. Second, the automatic installation by this link : source <(curl -fsSL https://bit.ly/36UvNhV)

**Comment by amzker** [comment]
install openssl-tools & then go to $PREFIX/lib
move all content of openssl1.1/* to $PREFIX/lib

**Comment by gushmazuko** [comment]
Fixed https://github.com/gushmazuko/metasploit_in_termux/commit/280f656e1dfc0ef8a866218346d3db651e87aac3

**Comment by moonpower007** [comment]
Change to gremilers repo to install the old version worked for me

**Comment by CoryResilient** [comment]
> Fixed [280f656](https://github.com/gushmazuko/metasploit_in_termux/commit/280f656e1dfc0ef8a866218346d3db651e87aac3)

No it's not solved. Stop lying

**Comment by skycat2216** [comment]
Do you installed Openssl**1.1**?

**Comment by dedshit** [comment]
> > Fixed [280f656](https://github.com/gushmazuko/metasploit_in_termux/commit/280f656e1dfc0ef8a866218346d3db651e87aac3)
> 
> No it's not solved. Stop lying



screenshot

**Comment by CyberKid1987** [comment]
![Uploading Screenshot_20220415-115259051.jpg…]()

Same problem. Any help?

**Comment by skycat2216** [comment]
try installing openssl-1. 1
That might the reason

**Comment by CyberKid1987** [comment]
> try installing openssl-1. 1 That might the reason

Same

**Comment by skycat2216** [comment]
Wait,Have you reinstall Ruby?

**Comment by CyberKid1987** [comment]
> Wait,Have you reinstall Ruby?

Yes

**Comment by amzker** [comment]
> `pkg install openssl-tools` `cp -r $PREFIX/lib/openssl-1.1/* $PREFIX/lib/`

**Comment by CyberKid1987** [comment]
> > `pkg install openssl-tools` `cp -r $PREFIX/lib/openssl-1.1/* $PREFIX/lib/`

Wrong commands

**Comment by amzker** [comment]
can you share the output of your typed command

**Comment by CyberKid1987** [comment]
> can you share the output of your typed command, my typo openssl-tool

![Uploading Screenshot_20220415-132906753.jpg…]()

**Comment by amzker** [comment]
borh are seprate commands, use like this
1st
pkg install openssl-tool 

2nd 
cp -r $PREFIX/lib/openssl-1.1/* $PREFIX/lib/

or combined

pkg install openssl-tool && cp -r $PREFIX/lib/openssl-1.1/* $PREFIX/lib/

**Comment by CyberKid1987** [comment]
> borh are seprate commands, use like this 1st pkg install openssl-tool
> 
> 2nd cp -r $PREFIX/lib/openssl-1.1/* $PREFIX/lib/
> 
> or combined
> 
> pkg install openssl-tool && cp -r $PREFIX/lib/openssl-1.1/* $PREFIX/lib/

First time not working. Second time works.. Its madness...

Now for dB connect:

mkdir -p $PREFIX/var/lib/postgresql
initdb $PREFIX/var/lib/postgresql

Commands to start and stop from termux  are..
pg_ctl -D $PREFIX/var/lib/postgresql start

pg_ctl -D $PREFIX/var/lib/postgresql stop

Type msfconsole and the db_connect msf

Done...

**Comment by momo-AUX1** [comment]
Switch to the grimler mirrors to install an old openssh/ssl version that worked for me
