### ISSUE TITLE
after installing metaspliit can ot open maf console

### ISSUE THREAD

**Issue by ajithlak18** [gushmazuko/metasploit_in_termux#102]
![Screenshot_2022-03-05-16-54-28-211_com termux](https://user-images.githubusercontent.com/66713732/156881020-b313f716-f8ac-4238-9493-a40e3854480e.jpg)
Poco x2

**Comment by hackglitz** [comment]
Same here
How to fix plz reply

**Comment by dedshit** [comment]
add net-smtp in gemspec and change mini_portile2 to 2.2.0

**Comment by Prince01github** [comment]
> add net-smtp in gemspec and change mini_portile2 to 2.2.0

How to do that bro?

**Comment by skycat2216** [comment]
https://github.com/gushmazuko/metasploit_in_termux/issues/100
Plz check closed issue next time.

**Comment by ajithlak20** [comment]
after adding also same problem msfconsole didnt run

**Comment by skycat2216** [comment]
Guess, Nokogiri failed to load?

**Comment by dedshit** [comment]
> > add net-smtp in gemspec and change mini_portile2 to 2.2.0
> 
> How to do that bro?

go to pull request and check and change

**Comment by ajithlak20** [comment]
Nothing Works how it work for other's

**Comment by hackglitz** [comment]
But yesterday worked.. not now

**Comment by dedshit** [comment]
> But yesterday worked.. not now

msfconsole or msfvenom ?

**Comment by dedshit** [comment]
> Bundler could not find compatible versions for gem "mini_portile2": In snapshot (Gemfile.lock): mini_portile2 (= 2.8.0)
> 
> In Gemfile: metasploit-framework was resolved to 6.1.33, which depends on nokogiri was resolved to 1.8.0, which depends on mini_portile2 (~> 2.2.0)
> 
> Running `bundle update` will rebuild your snapshot from scratch, using only the gems in your Gemfile, which may resolve the conflict.


dont you see , it says incompatible version just change 2.8.0 to 2.2.0 and run or clone my forked repo

**Comment by hackglitz** [comment]
Great work..  Thank u.. it's working with your forked repo..

**Comment by gushmazuko** [comment]
@dedshit check comment on pr.

**Comment by ajithlak18** [comment]
> > Bundler could not find compatible versions for gem "mini_portile2": In snapshot (Gemfile.lock): mini_portile2 (= 2.8.0)
> > In Gemfile: metasploit-framework was resolved to 6.1.33, which depends on nokogiri was resolved to 1.8.0, which depends on mini_portile2 (~> 2.2.0)
> > Running `bundle update` will rebuild your snapshot from scratch, using only the gems in your Gemfile, which may resolve the conflict.
> 
> dont you see , it says incompatible version just change 2.8.0 to 2.2.0 and run or clone my forked repo

its working with your cloned repo

**Comment by ajithlak18** [comment]
working msf6

**Comment by Zenith-77** [comment]
> Great work.. Thank u.. it's working with your forked repo..

Bro!! I am New on termux AND I am curious of learning it, But i am also facing same issue, Plz can you tell me step to step, how to clone forked repo and change version to 2.2.0,PLZ someone help,

**Comment by Zenith-77** [comment]
> > > Bundler could not find compatible versions for gem "mini_portile2": In snapshot (Gemfile.lock): mini_portile2 (= 2.8.0)
> > > In Gemfile: metasploit-framework was resolved to 6.1.33, which depends on nokogiri was resolved to 1.8.0, which depends on mini_portile2 (~> 2.2.0)
> > > Running `bundle update` will rebuild your snapshot from scratch, using only the gems in your Gemfile, which may resolve the conflict.
> > 
> > 
> > dont you see , it says incompatible version just change 2.8.0 to 2.2.0 and run or clone my forked repo
> 
> its working with your cloned repo

How to fork his repo? Plz tell me
