### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Senzoman1** [gushmazuko/metasploit_in_termux#106]
**Important**
Do not duplicate, search your issue before creating one!

**Describe the bug**
Msf payload missing

![Screenshot_20220311-054429_Termux](https://user-images.githubusercontent.com/99367113/157803705-c9072e7d-1915-4971-863b-63630f15283d.jpg)

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung A02]
 - OS: [e.g. Android 11]

**Comment by moonpower007** [comment]
I have the same config/boot error but to fix your gems try changing repos to gremiler and then installing everything from there it worked for me and I could use the listener

**Comment by Xmomoo** [comment]
i get when i try msfvenom 
<internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- metasploit/framework/profiler (LoadError)
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /data/data/com.termux/files/usr/bin/msfvenom:23:in `<main>'

**Comment by dedshit** [comment]
> **Important** Do not duplicate, search your issue before creating one!
> 
> **Describe the bug** Msf payload missing
> 
> ![Screenshot_20220311-054429_Termux](https://user-images.githubusercontent.com/99367113/157803705-c9072e7d-1915-4971-863b-63630f15283d.jpg)
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. Samsung A02]
> * OS: [e.g. Android 11]

`gem install metasploit-payloads`

**Comment by Senzoman1** [comment]
![Screenshot_20220312-074925_Termux.jpg](https://user-images.githubusercontent.com/99367113/158007554-51f5735f-9bee-4e8d-98fb-84571b0e05bd.jpg)


Now this

**Comment by dedshit** [comment]
> ![Screenshot_20220312-074925_Termux.jpg](https://user-images.githubusercontent.com/99367113/158007554-51f5735f-9bee-4e8d-98fb-84571b0e05bd.jpg)
> 
> Now this



clear data try reinstall
