### ISSUE TITLE
msfvenom bug

### ISSUE THREAD

**Issue by Xmomoo** [gushmazuko/metasploit_in_termux#107]
when i try msfvenom i get

```
<internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- metasploit/framework/profiler (LoadError)
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /data/data/com.termux/files/usr/bin/msfvenom:23:in `<main>`
```
**Smartphone:**
 - Device: Redmi 9C
 - OS: Android 10

**Comment by moonpower007** [comment]
I have a found a workaround for this instead of typing msfvenom -p for example you need to type :/data/data/com.termux/files/home/metasploit-framework/msfvenom -p android/meterpreter/reverse_tcp" and it will work !

**Comment by dedshit** [comment]
> when i try msfvenom i get
> 
> ```
> <internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- metasploit/framework/profiler (LoadError)
>         from <internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
>         from /data/data/com.termux/files/usr/bin/msfvenom:23:in `<main>`
> ```
> 
> **Smartphone:**
> 
> * Device: Redmi 9C
> * OS: Android 10

thats not a bug

**Comment by dedshit** [comment]
> when i try msfvenom i get
> 
> ```
> <internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- metasploit/framework/profiler (LoadError)
>         from <internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
>         from /data/data/com.termux/files/usr/bin/msfvenom:23:in `<main>`
> ```
> 
> **Smartphone:**
> 
> * Device: Redmi 9C
> * OS: Android 10


rm -rf /data/data/com.termux/files/usr/bin/msfvenom
cd metasploit-framework; ln -s $HOME/metasploit-framework/msfvenom /data/data/com.termux/files/usr/bin/

do this msfvenom will work fine

**Comment by anandaps2** [comment]
Solution: Please copy paste the commands in your termux terminal mentioned below. It worked for me [Source](https://github.com/efxtv/Metasploit-in-termux)

<pre>cd metasploit-framework;
sed -i '13,15 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb;
clear;echo "Done...."</pre>

**Comment by Ezgghxh** [comment]
$ msfvenom
<internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- metasploit/framework/profiler (LoadError)

**Comment by dedshit** [comment]
> $ msfvenom internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- metasploit/framework/profiler (LoadError)

#111
