### ISSUE TITLE
Could not find nokogiri-1.8.0 in any of the source

### ISSUE THREAD

**Issue by sarpanch1322** [gushmazuko/metasploit_in_termux#11]
![Screenshot_20201229_191123](https://user-images.githubusercontent.com/52079685/103288166-4f918f80-4a0a-11eb-8b13-453c11ca5c5c.jpg)
Im fasing this problem in my termux while installing metasploit please help

**Comment by Abhishek8r456** [comment]
First clear data of termux and then follow this post 
https://www.instagram.com/p/CKCM_YjJGLS/?igshid=hgssxyq89535

**Comment by gushmazuko** [comment]
Fixed with update
