### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by M9G1C19N** [gushmazuko/metasploit_in_termux#111]
This error shows after installing and typing msfconsole
![Screenshot_20220316-021642](https://user-images.githubusercontent.com/101665791/158447169-4676cb37-d148-4875-b143-51d2165ffcba.png)

 - Device: [Poco x3 nfc]
 - OS: [Android 11]

**Comment by dedshit** [comment]
sed -i '13,15 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb

paste this it will work fine

**Comment by dedshit** [comment]
> This error shows after installing and typing msfconsole ![Screenshot_20220316-021642](https://user-images.githubusercontent.com/101665791/158447169-4676cb37-d148-4875-b143-51d2165ffcba.png)
> 
> * Device: [Poco x3 nfc]
> * OS: [Android 11]


sed -i '13,15 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb



**@M9G1C19N  paste this it will work**

**Comment by dedshit** [comment]
> This error shows after installing and typing msfconsole ![Screenshot_20220316-021642](https://user-images.githubusercontent.com/101665791/158447169-4676cb37-d148-4875-b143-51d2165ffcba.png)
> 
> * Device: [Poco x3 nfc]
> * OS: [Android 11]

sed -i '13,15 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb

### **@M9G1C19N  just paste this**

**Comment by M9G1C19N** [comment]
Thank you, its fix now

**Comment by gmakshe** [comment]
This didn't work for me

**Comment by dedshit** [comment]
> This didn't work for me

send detailed screenshot

**Comment by kumlachew-mitiku** [comment]
(most recent call last):
        35: from /data/data/com.termux/files/usr/bin/msfconsole:17:in `<main>'
        34: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        33: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        32: from /data/data/com.termux/files/home/metasploit-framework/config/boot.rb:26:in `<top (required)>'
        31: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        30: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        29: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/setup.rb:10:in `<top (required)>'
        28: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/ui/shell.rb:88:in `silence'
        27: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/ui/shell.rb:136:in `with_level'
        26: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/setup.rb:10:in `block in <top (required)>'
        25: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler.rb:143:in `setup'
        24: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler.rb:195:in `definition'
        23: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/definition.rb:34:in `build'
        22: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/dsl.rb:13:in `evaluate'
        21: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/dsl.rb:234:in `to_definition'
        20: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/dsl.rb:234:in `new'
        19: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/definition.rb:119:in `initialize'
        18: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/definition.rb:628:in `converge_paths'
        17: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/definition.rb:628:in `any?'
        16: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/definition.rb:629:in `block in converge_paths'
        15: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/definition.rb:585:in `specs_changed?'
        14: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/definition.rb:600:in `specs_for_source_changed?'
        13: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/source/path.rb:113:in `specs'
        12: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/source/path.rb:105:in `local_specs'
        11: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/source/path.rb:170:in `load_spec_files'
        10: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/source/path.rb:170:in `each'
         9: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/source/path.rb:176:in `block in load_spec_files'
         8: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/source/path.rb:162:in `validate_spec'
         7: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/rubygems_integration.rb:70:in `validate'
         6: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/ui/shell.rb:88:in `silence'
         5: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/ui/shell.rb:136:in `with_level'
         4: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/rubygems_integration.rb:70:in `block in validate'
         3: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/rubygems/specification.rb:2594:in `validate'
         2: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/rubygems/specification_policy.rb:76:in `validate'
         1: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/rubygems/specification_policy.rb:180:in `validate_dependencies'
/data/data/com.termux/files/usr/lib/ruby/2.7.0/rubygems/specification_policy.rb:426:in `error': duplicate dependency on net-smtp (>= 0), (>= 0) use: (Gem::InvalidSpecificationException)
    add_runtime_dependency 'net-smtp', '>= 0', '>= 0'
        29: from /data/data/com.termux/files/usr/bin/msfconsole:17:in `<main>'
        28: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        27: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        26: from /data/data/com.termux/files/home/metasploit-framework/config/boot.rb:26:in `<top (required)>'
        25: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        24: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        23: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/setup.rb:10:in `<top (required)>'
        22: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/ui/shell.rb:88:in `silence'
        21: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/ui/shell.rb:136:in `with_level'
        20: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/setup.rb:10:in `block in <top (required)>'
        19: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler.rb:143:in `setup'
        18: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler.rb:195:in `definition'
        17: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/definition.rb:34:in `build'
        16: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/dsl.rb:13:in `evaluate'
        15: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/dsl.rb:234:in `to_definition'
        14: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/dsl.rb:234:in `new'
        13: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/definition.rb:119:in `initialize'
        12: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/definition.rb:628:in `converge_paths'
        11: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/definition.rb:628:in `any?'
        10: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/definition.rb:629:in `block in converge_paths'
         9: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/definition.rb:585:in `specs_changed?'
         8: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/definition.rb:600:in `specs_for_source_changed?'
         7: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/source/path.rb:113:in `specs'
         6: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/source/path.rb:105:in `local_specs'
         5: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/source/path.rb:170:in `load_spec_files'
         4: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/source/path.rb:170:in `each'
         3: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/source/path.rb:176:in `block in load_spec_files'
         2: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/source/path.rb:162:in `validate_spec'
         1: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/rubygems_integration.rb:69:in `validate'
/data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/rubygems_integration.rb:74:in `rescue in validate': The gemspec at /data/data/com.termux/files/home/metasploit-framework/metasploit-framework.gemspec is not valid. Please fix this gemspec. (Gem::InvalidSpecificationException)
The validation error was 'duplicate dependency on net-smtp (>= 0), (>= 0) use:
    add_runtime_dependency 'net-smtp', '>= 0', '>= 0'

**Comment by gushmazuko** [comment]
https://github.com/gushmazuko/metasploit_in_termux/commit/969dea056e05c3e1cd60bfa79262ac1caa509b08
