### ISSUE TITLE
Need Help 

### ISSUE THREAD

**Issue by mdfrabby** [gushmazuko/metasploit_in_termux#112]
Could not load OpenSSL.
You must recompile Ruby with OpenSSL support or
change the sources in your Gemfile from 'https'
to 'http'. Instructions for compiling with
OpenSSL using RVM are available at
https://rvm.io/packages/openssl.

**Comment by dedshit** [comment]
reinstall termux

**Comment by dedshit** [comment]
give credits to @gushmazuko  first also no promotion here @anandaps2
