### ISSUE TITLE
Not opening metadploit

### ISSUE THREAD

**Issue by Whitedevil807** [gushmazuko/metasploit_in_termux#116]
![Screenshot_20220318_094408](https://user-images.githubusercontent.com/101460475/159109814-3591b8c4-5c84-4b9a-bd5d-2be8d535af46.jpg)

**Comment by HashTreep** [comment]
I have this error too.

**Comment by KalkiKS** [comment]
I have same problem....

**Comment by dedshit** [comment]
dont spam here check this #111  and close this issue

**Comment by oday-almoaafa** [comment]
وانا ايضاً لدي نفس المشكلة

**Comment by oday-almoaafa** [comment]
I also have the same problem

**Comment by dedshit** [comment]
> I also have the same problem....

?

**Comment by gushmazuko** [comment]
Fixed https://github.com/gushmazuko/metasploit_in_termux/commit/969dea056e05c3e1cd60bfa79262ac1caa509b08
