### ISSUE TITLE
When I write msfconsole it will not start please solve my problems 

### ISSUE THREAD

**Issue by arav0125** [gushmazuko/metasploit_in_termux#118]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
![Screenshot_20220321_150758](https://user-images.githubusercontent.com/91102859/159237352-3b85ff7b-ceaf-4cb5-a3c2-6c9fa43c257e.jpg)

I have requested to you to solve my problems fast

**Comment by dedshit** [comment]
#111

**Comment by Aryan-Tyagi555** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen. ![Screenshot_20220321_150758](https://user-images.githubusercontent.com/91102859/159237352-3b85ff7b-ceaf-4cb5-a3c2-6c9fa43c257e.jpg)
> 
> I have requested to you to solve my problems fast

I also have same problem

**Comment by Aryan-Tyagi555** [comment]
I also have same problem

**Comment by dedshit** [comment]
> I also have same problem

dont spam

**Comment by vipulsharma4473** [comment]
I have also problem

**Comment by Starboyop** [comment]
Plz solve the problem and plz clearly explain the method of fixing so that we can fix it plz solve the problem

**Comment by dedshit** [comment]
> Plz solve the problem and plz clearly explain the method of fixing so that we can fix it plz solve the problem


are you new to github ?

**Comment by gushmazuko** [comment]
Fixed https://github.com/gushmazuko/metasploit_in_termux/commit/969dea056e05c3e1cd60bfa79262ac1caa509b08
