### ISSUE TITLE
postgresql_ctl.sh not starting

### ISSUE THREAD

**Issue by Abhishek8r456** [gushmazuko/metasploit_in_termux#12]
$ ./postgresql_ctl.sh start
./postgresql_ctl.sh
: line 3: pg_ctl: command not found
![20210109_085530](https://user-images.githubusercontent.com/67840255/104081997-99734480-5258-11eb-9dc7-6492498bef58.jpg)

 Please help

**Comment by calistro172** [comment]
Same here

**Comment by olorochi** [comment]
That's not what the end of the installation process should look like try re-running ./metasploit.sh

**Comment by calistro172** [comment]
I tried re-running metasploit.sh it gives the same results

**Comment by Abhishek8r456** [comment]
First clear data of termux and then try this method 
Instagram post -
https://www.instagram.com/p/CKCM_YjJGLS/?igshid=hgssxyq89535

**Comment by hey991** [comment]
Hjh
