### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Cool1l** [gushmazuko/metasploit_in_termux#120]
When I tried to launch msfconsole I got this error

![IMG_20220322_142434_633](https://user-images.githubusercontent.com/94423611/159443568-251cd94e-b830-4b95-98dc-e9564ef249a9.jpg)

**Comment by dedshit** [comment]
> @Cool1l **you didn't cloned this repo aren't you ?**



> S I did can u help me bro

delete previous metasploit folder

**Comment by Cool1l** [comment]
okay thank you bro
