### ISSUE TITLE
![Screenshot_20220228-102941](https://user-images.githubusercontent.com/95457825/156020542-37ce2019-d6d2-4c30-b859-941033ff7528.png)

### ISSUE THREAD

**Issue by 250416** [gushmazuko/metasploit_in_termux#123]
![Screenshot_20220228-102941](https://user-images.githubusercontent.com/95457825/156020542-37ce2019-d6d2-4c30-b859-941033ff7528.png)

Thank you

_Originally posted by @Theworld15 in https://github.com/gushmazuko/metasploit_in_termux/issues/92#issuecomment-1054437123_

**Comment by dedshit** [comment]
Is that an issue ?

**Comment by Theworld15** [comment]
> ![Screenshot_20220228-102941](https://user-images.githubusercontent.com/95457825/156020542-37ce2019-d6d2-4c30-b859-941033ff7528.png)
> 
> Thank you
> 
> _Originally posted by @Theworld15 in https://github.com/gushmazuko/metasploit_in_termux/issues/92#issuecomment-1054437123_

Is there a problem?

**Comment by zhengyo** [comment]
我可启动不了

**Comment by zhengyo** [comment]
I can't start it .
