### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zhengyo** [gushmazuko/metasploit_in_termux#126]
[#**Important**](
![Screenshot_20220331-185702](https://user-images.githubusercontent.com/95407088/161040240-db5ca702-2ee5-4154-8ea4-cae1e12a0103.jpg)
![Screenshot_20220331-185702](https://user-images.githubusercontent.com/95407088/161040467-ce1f8a27-6814-4d30-a563-ef0c13d776ef.jpg)
)

`/data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb:13:in `initialize': unsupported (OpenSSL::Cipher::CipherError)
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb:13:in `new'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb:13:in `included'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/blowfish_cbc.rb:14:in `include'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/blowfish_cbc.rb:14:in `<class:BlowfishCbc>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/blowfish_cbc.rb:9:in `<class:EncryptionAlgorithm>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/blowfish_cbc.rb:8:in `<class:Transport>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/blowfish_cbc.rb:7:in `<module:HrrRbSsh>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/blowfish_cbc.rb:6:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm.rb:19:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/kex_algorithm/iv_computable.rb:5:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/kex_algorithm/diffie_hellman.rb:7:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/kex_algorithm/diffie_hellman_group1_sha1.rb:4:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/kex_algorithm.rb:17:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport.rb:15:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh.rb:15:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/lib/rex/proto/ssh/hrr_rb_ssh.rb:3:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/lib/rex/proto/ssh/connection.rb:2:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/handler/reverse_ssh.rb:146:in `default_version_string'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/handler/reverse_ssh.rb:40:in `initialize'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/base/sessions/command_shell_options.rb:16:in `initialize'
        from /data/data/com.termux/files/home/metasploit-framework/modules/payloads/singles/cmd/unix/reverse_ssh.rb:16:in `initialize'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_set.rb:95:in `new'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_set.rb:95:in `block (2 levels) in recalculate'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_set.rb:93:in `each_pair'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_set.rb:93:in `block in recalculate'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_set.rb:73:in `each_pair'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_set.rb:73:in `recalculate'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/modules/loader/base.rb:258:in `block in load_modules'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/modules/loader/base.rb:255:in `each'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/modules/loader/base.rb:255:in `load_modules'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/module_manager/loading.rb:170:in `block in load_modules'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/module_manager/loading.rb:168:in `each'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/module_manager/loading.rb:168:in `load_modules'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:41:in `block in add_module_path'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `each'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `add_module_path'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:51:in `block in init_module_paths'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in `each'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in `init_module_paths'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/ui/console/driver.rb:160:in `initialize'
        from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/command/console.rb:60:in `new'
        from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/command/console.rb:60:in `driver'
        from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
        from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'`

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 8]
 - OS: [e.g. Android 7]

**Comment by dedshit** [comment]
check closed issue first. Dont open duplicate issue

**Comment by zhengyo** [comment]
> check closed issue first. Dont open duplicate issue

I don't know how to solve it.

**Comment by dedshit** [comment]
> > check closed issue first. Dont open duplicate issue
> 
> I don't know how to solve it.

#111

**Comment by zhengyo** [comment]
> > > check closed issue first. Dont open duplicate issue
> > 
> > 
> > I don't know how to solve it.
> 
> #111

![Screenshot_20220401-194716](https://user-images.githubusercontent.com/95407088/161257573-16b4df8a-e11c-408b-990f-a110d5664b80.jpg)

**Comment by zhengyo** [comment]
Still can't solve.

**Comment by zhengyo** [comment]
> > > check closed issue first. Dont open duplicate issue
> > 
> > 
> > I don't know how to solve it.
> 
> #111

Problem solved, thank you very much!

**Comment by Nurik-png** [comment]
> 
How did you do it?

**Comment by zhengyo** [comment]
> > 
> 
> How did you do it?

Just open his link and copy the code.

**Comment by Nurik-png** [comment]
Можешь помочь мне , либо показать как ты сделал это
--
Отправлено из Mail.ru для Android пятница, 08 апреля 2022г., 10:35 +03:00 от zhengyo  ***@***.*** :

**Comment by zhengyo** [comment]
> Можешь помочь мне , либо показать как ты сделал это -- Отправлено из Mail.ru для Android пятница, 08 апреля 2022г., 10:35 +03:00 от zhengyo ***@***.*** :
> […](#)
> >How did you do it? Just open his link and copy the code. — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you commented. Message ID: @ github . com>

Please speak English.

**Comment by zhengyo** [comment]
> Можешь помочь мне , либо показать как ты сделал это -- Отправлено из Mail.ru для Android пятница, 08 апреля 2022г., 10:35 +03:00 от zhengyo ***@***.*** :
> […](#)
> >How did you do it? Just open his link and copy the code. — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you commented. Message ID: @ github . com>

Can you speak English? I don't know your language.

**Comment by zhengyo** [comment]
In particular, my problem has been solved.
