### ISSUE TITLE
Como desintalar metasploit

### ISSUE THREAD

**Issue by yoil12** [gushmazuko/metasploit_in_termux#128]
**Important**
Do not duplicate, search your issue before creating one!

**Describe the bug**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 8]
 - OS: [e.g. Android 10]

**Comment by dedshit** [comment]
invalid

**Comment by zhengyo** [comment]
It seems useless for you to send this, try to send some useful bugs.
