### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by The-Young-Programmer** [gushmazuko/metasploit_in_termux#129]
Pls help solve this, already Installed the latest version of Termux.

But still getting this error..... Don't know what to do @dedshit @gushmazuko

![Screenshot_20220408-211346](https://user-images.githubusercontent.com/79866006/162522748-2ab512d0-aec5-46f5-85e8-5588aca171f9.jpg)

![Screenshot_20220408-211322](https://user-images.githubusercontent.com/79866006/162522864-a6dd66ae-257f-4fe0-927f-7d0e1da00575.jpg)

**Comment by dedshit** [comment]
did you overwrite existing one with new

**Comment by The-Young-Programmer** [comment]
Yes, I did.... I Re install termux Clone your git still giving same error

**Comment by zhengyo** [comment]
Try Ruby3 instead .

**Comment by zhengyo** [comment]
OpenSSL errors will occur in Ruby2.

**Comment by The-Young-Programmer** [comment]
Okay let me try it out @zhengyo
What about the gem error it's showing?

**Comment by zhengyo** [comment]
> Okay let me try it out @zhengyo What about the gem error it's showing?

I don't know. Anyway, Ruby2 can't intercept the ssl signal from February and March. Only Ruby3 can intercept the ssl signal. Just delete the sources.list. d folder under the apt folder and try installing it again .

**Comment by zhengyo** [comment]
Well, look at my problem now. With the latest Ruby.

**Comment by dedshit** [comment]
> Okay let me try it out @zhengyo What about the gem error it's showing?


check my forked repo @The-Young-Programmer

**Comment by The-Young-Programmer** [comment]
> 

I tried it still getting error

**Comment by zhengyo** [comment]
Ruby3 ？ 
(Don't send messages in the middle of the night, consider our Chinese. It's 12: 02 in China now. ）

**Comment by The-Young-Programmer** [comment]
`check my forked repo @The-Young-Programmer`

It was your forked repo I use. Still getting the same error @dedshit

But am thinking maybe I should Uninstall the termux then re-download it from F-Driod.

Can you send the command to download the Metasploit from  start to end pls. 🙏

**Comment by zhengyo** [comment]
It's no use.

**Comment by zhengyo** [comment]
I can't download it now. 
Look at #130

**Comment by The-Young-Programmer** [comment]
@zhengyo
Ooh sorry about the time.

**Comment by zhengyo** [comment]
It's not Ruby2, but Ruby3 doesn't work right now. 
Download it in a few days. @The-Young-Programmer

**Comment by zhengyo** [comment]
> @zhengyo Ooh sorry about the time.

Nothing

**Comment by The-Young-Programmer** [comment]
@dedshit
Am about Installing new termux. 
I will use your forked repo. 
when am done will let you know.

Thanks very much
