### ISSUE TITLE
[BUG] Installation problems 

### ISSUE THREAD

**Issue by zhengyo** [gushmazuko/metasploit_in_termux#130]
**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung sm-t560nu]
 - OS: [e.g. Android 7]

The previous installation was still good, and now there is a problem with the installation. 

![Screenshot_20220409-165623](https://user-images.githubusercontent.com/95407088/162564584-bd7e06eb-1146-4c9c-9745-2fed4c8ff510.jpg)

**Comment by dedshit** [comment]
check my forked repo  @zhengyo

**Comment by zhengyo** [comment]
> check my forked repo @zhengyo

Can you tell me the method in detail?

**Comment by zhengyo** [comment]
You can run it with your tools. 

![Screenshot_20220410-085742](https://user-images.githubusercontent.com/95407088/162596772-fca98668-75c3-49e0-ad9c-1d3e69a56e96.jpg)

**Comment by zhengyo** [comment]
I was wrong. It's ready to use. 

@dedshit
