### ISSUE TITLE
rm: cannot remove '/data/data/com.termux/files/usr/etc/apt/sources.list.d/*': No such file or directory[BUG]

### ISSUE THREAD

**Issue by yochi-chan** [gushmazuko/metasploit_in_termux#131]
rm: cannot remove '/data/data/com.termux/files/usr/etc/apt/sources.list.d/*': No such file or directory

When ever I try installing metasploit it shows this
![Uploading Screenshot_2022-04-11-15-36-16-951_com.termux.jpg…]()

**Comment by dedshit** [comment]
### **invalid**

**Comment by yochi-chan** [comment]
So do I just ignore it???

**Comment by dedshit** [comment]
> So do I just ignore it???

yep

**Comment by yochi-chan** [comment]
Ok thank you
