### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AnastiaQwe** [gushmazuko/metasploit_in_termux#132]
This problem has not been resolved yet by the dev, I want to know why this error occur when I follow the whole process and installed the necessary dependencies for it to work. But so far I’m still getting the same error again and again; I tried to install and reinstall it a couple of times but nothing can solve the issue. 

![Screenshot_20220412-011223](https://user-images.githubusercontent.com/103449267/162796272-56a0363b-6d61-41ce-9ba0-a0086301af16.png)

![Screenshot_20220412-011223](https://user-images.githubusercontent.com/103449267/162796621-013bc1d9-4380-40f7-b3e6-3c61d714ea49.png)
![Screenshot_20220412-011232](https://user-images.githubusercontent.com/103449267/162796649-53d8401d-f665-4040-8554-d180a8f0b98a.png)
![Screenshot_20220412-011455](https://user-images.githubusercontent.com/103449267/162796671-fec77f47-77af-4121-a08a-6708fcc5dff1.png)
![Uploading Screenshot_20220412-011501.png…]()

Os: Android
Version: 11
Model: Realme C11 2021

**Comment by na755** [comment]
I have same problem

**Comment by Sachin5441** [comment]
I have also same problem

**Comment by dedshit** [comment]
remove net-smtp from gemspec

**Comment by AnastiaQwe** [comment]
Please make your response clear and concise. What do you mean by removing net-smtp from gemspec?

**Comment by 123445aman** [comment]
Same problem

**Comment by dedshit** [comment]
> Same problem

if you have http canary just modify the response
