### ISSUE TITLE
Net-smtp no longer needed

### ISSUE THREAD

**Issue by dedshit** [gushmazuko/metasploit_in_termux#134]
# @gushmazuko 

![20220413_143303](https://user-images.githubusercontent.com/62318734/163140880-f4328b68-6c4f-4191-90ef-7fb5d0e6f560.png)

remove/comment these from metasploit.sh 

![20220413_143513](https://user-images.githubusercontent.com/62318734/163141309-5457cb53-0d3d-45b2-884a-e9b9f4e117a2.png)

they have added net-smtp in gemspec so no need for that 

#111 #129 #130 #132 #133 

# Thanks in Advance

**Comment by gushmazuko** [comment]
@dedshit thanks dude!

**Comment by dedshit** [comment]
> @dedshit thanks dude!


if you have free time please check that debian package 
.I know there might be some issues for aarch64 but for armv7 no prob

thank you

**Comment by gushmazuko** [comment]
https://github.com/gushmazuko/metasploit_in_termux/commit/969dea056e05c3e1cd60bfa79262ac1caa509b08
