### ISSUE TITLE
[error]

### ISSUE THREAD

**Issue by senadulanka** [gushmazuko/metasploit_in_termux#136]
**Important**
Do not duplicate, search your issue before creating one!

**Describe the bug**
error 

**Screenshots**
![Screenshot_20220414-231237_Termux](https://user-images.githubusercontent.com/80214587/163445265-99a773b8-2e17-48cf-ad5e-a33d57fe1feb.jpg)

**Smartphone (please complete the following information):**
 - Device: [samsung a12]
 - OS: [Android 11]

**Comment by dedshit** [comment]
delete ruby in lib and use http canary

**Comment by zhengyo** [comment]
Delete $ prefix / etc / apt / sources.list.d / and install it again
