### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Aadhithyaa009** [gushmazuko/metasploit_in_termux#138]
**Important**
Do not duplicate, search your issue before creating one!

**Describe the bug**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 8]
 - OS: [e.g. Android 10]
![Uploading Screenshot_20220416-141206_Termux.jpg…]()
``

**Comment by Aadhithyaa009** [comment]
Give me some solution to solve the error

**Comment by zhengyo** [comment]
I can't see the screenshot you sent: 
![Screenshot_20220416-193649](https://user-images.githubusercontent.com/95407088/163673436-0bf24af5-03d2-474b-8c8e-02b9c770f8bc.jpg)

**Comment by zhengyo** [comment]
Please upload the screenshot again.

**Comment by Aadhithyaa009** [comment]
Please upload the screenshot again.

**Comment by Aadhithyaa009** [comment]
[Screenshot_20220416-190415_Gallery.jpg]

**Comment by Aadhithyaa009** [comment]
> Please upload the screenshot again. 

~/Metasploit_Termux $ pkg install metsaploit
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package metsaploit

**Comment by Aadhithyaa009** [comment]
> Please upload the screenshot again. 



Unable to send screenshot 



~/Metasploit_Termux $ pkg install metsaploit
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package metsaploit

**Comment by dedshit** [comment]
> > Please upload the screenshot again.
> 
> Unable to send screenshot
> 
> ~/Metasploit_Termux $ pkg install metasploit Checking availability of current mirror: ok Reading package lists... Done Building dependency tree... Done Reading state information... Done E: Unable to locate package metasploit ~/Metasploit_Termux $


dont open issue that is irrelevant

**Comment by zhengyo** [comment]
This question doesn't make any sense 。

**Comment by zhengyo** [comment]
> > Please upload the screenshot again.
> 
> Unable to send screenshot
> 
> ~/Metasploit_Termux $ pkg install metasploit Checking availability of current mirror: ok Reading package lists... Done Building dependency tree... Done Reading state information... Done E: Unable to locate package metasploit ~/Metasploit_Termux $

Looks like you're using someone else's program.

**Comment by Aadhithyaa009** [comment]
Error



~ $ ifconfig
Warning: cannot open /proc/net/dev (Permission denied). Limited output.
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1  (UNSPEC)

rmnet_data0: flags=65<UP,RUNNING>  mtu 1500
        inet 26.146.81.183  netmask 255.255.255.240
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)

**Comment by zhengyo** [comment]
> Error
> 
> ~ $ ifconfig Warning: cannot open /proc/net/dev (Permission denied). Limited output. lo: flags=73<UP,LOOPBACK,RUNNING> mtu 65536 inet 127.0.0.1 netmask 255.0.0.0 unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 1 (UNSPEC)
> 
> rmnet_data0: flags=65<UP,RUNNING> mtu 1500 inet 26.146.81.183 netmask 255.255.255.240 unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 1000 (UNSPEC)

It doesn't make any sense for you to send this. It's not a problem. Please tell me what is wrong with your program with Gushmazko and don't mention irrelevant issues.
