### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ghost** [gushmazuko/metasploit_in_termux#139]
![Screenshot_20220418-213840](https://user-images.githubusercontent.com/95457825/163909450-383cabf9-5fb4-4513-b069-0f9feba298c6.png)

**Comment by Clearzero22** [comment]
This problem has been solved for me, I read someone's comments.
First, you remove/comment these from metasploit.sh



Comment out the code above

Second, use vim, Modify the metasploit framework/metasploit. Gemspec  ,In lines 138 through 146, there is a net-smtp comment that is repeated  

than,Run metasloit.sh again  ,You will find a new problem, after the completion of execution msfconsle again you will find a new problem, unsupported (OenSSL: : Cipher: : CipherError),.Pay attention to executing the following code, and you'll be pleasantly surprised when your MSFConsle executes  

sed -i '13,15 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb

**Comment by gushmazuko** [comment]
https://github.com/gushmazuko/metasploit_in_termux/commit/969dea056e05c3e1cd60bfa79262ac1caa509b08
