### ISSUE TITLE
[BUG] msfconsole spell checkers error name 

### ISSUE THREAD

**Issue by Bakwanxyz** [gushmazuko/metasploit_in_termux#141]
**Important**
Do not duplicate, search your issue before creating one! Please help me 🙏🙏🙏

**Describe the bug**

 #**Scre
![IMG-20220429-WA0006](https://user-images.githubusercontent.com/104622845/165915893-3505ea93-e253-4ab7-970d-fec4b5a26bcf.jpg)
enshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 8]
 - OS: [e.g. Android 10]
!
![IMG-20220429-WA0007](https://user-images.githubusercontent.com/104622845/165916233-e9ea9ad9-7a52-4351-8980-0896f745f6ef.jpg)

**Comment by dedshit** [comment]
check my pr @Bakwanxyz

**Comment by gushmazuko** [comment]
https://github.com/gushmazuko/metasploit_in_termux/commit/969dea056e05c3e1cd60bfa79262ac1caa509b08
