### ISSUE TITLE
warning: Exception in finalizer

### ISSUE THREAD

**Issue by cmarlon00** [gushmazuko/metasploit_in_termux#142]
I have followed all the instructions correctly to install the metasploit, when I type msfconsole it runs fine but when I type quit to exit the metasploit I get a warn, I still tried to run ./msfdb and ran the code but a warn came out, I would be grateful if someone told me could you help with this the warn is :

``/data/data/com.termux/files/usr/bin/msfconsole: warning: Exception in finalizer #<Proc:0x00000074de4f1a70 /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.0.5/lib/concurrent/atomic/ruby_thread_local_var.rb:85>``

``/data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:471:in `new': can't alloc thread (ThreadError)
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:471:in `create_with_logging_context'``

``from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:436:in `new'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.0.5/lib/concurrent/atomic/ruby_thread_local_var.rb:86:in `block in threadlocal_finalizer'``

``/data/data/com.termux/files/usr/bin/msfconsole: warning: Exception in finalizer #<Proc:0x00000074de4f2470 /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.0.5/lib/concurrent/atomic/ruby_thread_local_var.rb:85>``

``/data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:471:in `new': can't alloc thread (ThreadError)
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:471:in `create_with_logging_context'``

``from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:436:in `new'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.0.5/lib/concurrent/atomic/ruby_thread_local_var.rb:86:in `block in threadlocal_finalizer'``

It would be great to know if this warn affects the operation of the metasploit and if there is any way to solve it

Thanks

**Comment by dedshit** [comment]
> I have followed all the instructions correctly to install the metasploit, when I type msfconsole it runs fine but when I type quit to exit the metasploit I get a warn, I still tried to run ./msfdb and ran the code but a warn came out, I would be grateful if someone told me could you help with this the warn is :
> 
> ``/data/data/com.termux/files/usr/bin/msfconsole: warning: Exception in finalizer #<Proc:0x00000074de4f1a70 /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.0.5/lib/concurrent/atomic/ruby_thread_local_var.rb:85>``
> 
> ``/data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:471:in `new': can't alloc thread (ThreadError)
>         from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:471:in `create_with_logging_context'``
> 
> ``from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:436:in `new'
>         from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.0.5/lib/concurrent/atomic/ruby_thread_local_var.rb:86:in `block in threadlocal_finalizer'``
> 
> ``/data/data/com.termux/files/usr/bin/msfconsole: warning: Exception in finalizer #<Proc:0x00000074de4f2470 /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.0.5/lib/concurrent/atomic/ruby_thread_local_var.rb:85>``
> 
> ``/data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:471:in `new': can't alloc thread (ThreadError)
>         from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:471:in `create_with_logging_context'``
> 
> ``from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:436:in `new'
>         from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.0.5/lib/concurrent/atomic/ruby_thread_local_var.rb:86:in `block in threadlocal_finalizer'``
> 
> 
> It would be great to know if this warn affects the operation of the metasploit and if there is any way to solve it
> 
> 
> Thanks 
> 
> 
> 

check pr @cmarlon00  & do it yourself

**Comment by gushmazuko** [comment]
https://github.com/gushmazuko/metasploit_in_termux/commit/969dea056e05c3e1cd60bfa79262ac1caa509b08
