### ISSUE TITLE
Could not load openssl 

### ISSUE THREAD

**Issue by loopdawglol** [gushmazuko/metasploit_in_termux#143]
Idk what to do it says change https file to http

**Comment by dedshit** [comment]
> 
> Idk what to do it says change https file to http
> 

share screenshot

**Comment by zhengyo** [comment]
sed -i '13,15 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb;

**Comment by zhengyo** [comment]
Remember to switch to the "msf" folder first

**Comment by krisdowis** [comment]
Then you don't have openssl in your pkg

First install the required apts

```
apt install openssl openssh apache2 zip unzip apktool apksigner php 
```

and it should work fine now
