### ISSUE TITLE
[BUG] Msfvenom error 

### ISSUE THREAD

**Issue by darkmoon16** [gushmazuko/metasploit_in_termux#144]
i get this error when i run msfvenom 

<internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- metasploit/framework/profiler (LoadError)
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /data/data/com.termux/files/usr/bin/msfvenom:23:in `<main>'

**Comment by gushmazuko** [comment]
Fixed https://github.com/gushmazuko/metasploit_in_termux/commit/529ea5a6bec49d67525d9da3a46b72779eeed1b8

**Comment by HackerBrine2004** [comment]
Sir will it work like normal metasploit i mean does it have postegresql

**Comment by gushmazuko** [comment]
> Sir will it work like normal metasploit i mean does it have postegresql

Yea

**Comment by HackerBrine2004** [comment]
> 

Thank you sir best of luck for future 👍

**Comment by 773aimn** [comment]
`حدد اختيار`

**Comment by 773aimn** [comment]
![Screenshot_20220713-003835377](https://user-images.githubusercontent.com/109182754/178605466-1678a211-d8c8-47d5-ad9e-70e1a11f5561.png)

**Comment by 773aimn** [comment]
مذا افعل بعد هذا
