### ISSUE TITLE
Msfvenom command doesn't work,how to do?

### ISSUE THREAD

**Issue by someshsrichandan** [gushmazuko/metasploit_in_termux#154]
**Describe the bug**
![Screenshot_2022-07-04-20-13-29-604_com termux](https://user-images.githubusercontent.com/69620426/177177647-9322eadc-729d-4370-896e-df984318f513.jpg)

![Screenshot_2022-07-04-20-14-34-342_com termux](https://user-images.githubusercontent.com/69620426/177177710-633aeb5f-c437-4958-8170-7a564fdd657a.jpg)

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 8]poco m4 pro 4g
 - OS: [e.g. Android 10] Android 11
 - Termux version 0.118.0

**Comment by krisdowis** [comment]
you need to set it up

Use the following commands to set up msfveno


```
cd /data/data/com.termux/files/usr/opt/metasploit-framework

cp msfvenom /data/data/com.termux/files/usr/bin

updatedb 

```
and that's all you can now use the `msfvenom`command
