### ISSUE TITLE
Can't uninstall or update

### ISSUE THREAD

**Issue by krisdowis** [gushmazuko/metasploit_in_termux#156]

**Comment by kartikverma007** [comment]
I have rooted my phone and i am not able to update termux when I try to update it comes:
~ $ pkg update
Checking availability of current mirror: ok
Get:1 https://packages.termux.dev/apt/termux-main stable InRelease [14.0 kB]
Get:2 https://packages.termux.dev/apt/termux-games games InRelease [7999 B]
Err:1 https://packages.termux.dev/apt/termux-main stable InRelease
  At least one invalid signature was encountered.
Get:3 https://packages.termux.dev/apt/termux-science science InRelease [8011 B]
Err:2 https://packages.termux.dev/apt/termux-games games InRelease
  At least one invalid signature was encountered.
Err:3 https://packages.termux.dev/apt/termux-science science InRelease
  At least one invalid signature was encountered.
Reading package lists... Done
W: GPG error: https://packages.termux.dev/apt/termux-main stable InRelease: At least one invalid signature was encountered.
E: The repository 'https://packages.termux.org/apt/termux-main stable InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
W: GPG error: https://packages.termux.dev/apt/termux-games games InRelease: At least one invalid signature was encountered.
E: The repository 'https://packages.termux.org/apt/termux-games games InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
W: GPG error: https://packages.termux.dev/apt/termux-science science InRelease: At least one invalid signature was encountered.
E: The repository 'https://packages.termux.org/apt/termux-science science InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
~ $
