### ISSUE TITLE
msfrpcd

### ISSUE THREAD

**Issue by david56downs** [gushmazuko/metasploit_in_termux#158]
we dont have no msfrpcd

**Comment by krisdowis** [comment]
There is you need to set it up

**Comment by gushmazuko** [comment]
Issue was fixed: https://github.com/gushmazuko/metasploit_in_termux/commit/81ab90be391d893b3413eb6120229dce9def0a90

**Comment by krisdowis** [comment]
> Issue was fixed: https://github.com/gushmazuko/metasploit_in_termux/commit/81ab90be391d893b3413eb6120229dce9def0a90

Hello how do I update it now

**Comment by krisdowis** [comment]
The issues has been fixed so how do I update it
