### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mclovinIG** [gushmazuko/metasploit_in_termux#159]
TENGO UN PROBLEMA AL EJECUTAR EL COMANDO 
msfconsole me sale este error: 
![Screenshot_2022-07-24-19-00-41-346_com termux](https://user-images.githubusercontent.com/84486811/180671373-6747db51-cca8-4545-9771-f389c92f5d87.jpg)
![Screenshot_2022-07-24-19-00-41-346_com termux](https://user-images.githubusercontent.com/84486811/180671385-5caccba5-6dc3-439d-88a3-94b9110b44d7.jpg)

⋊> ~ msfconsole                                       18:59:55
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Could not find nokogiri-1.12.5 in any of the sources
Run `bundle install` to install missing gems.
⋊> ~

**Comment by krisdowis** [comment]
Hubo un problema/error cuando estabas instalando... intenta volver a instalarlo y funcionará.  usa este comando para instalar 👇


```
source <(curl -fsSL https://kutt.it/msf)
```
