### ISSUE TITLE
Ruby 3.0 not support metasploit

### ISSUE THREAD

**Issue by capunk2708** [gushmazuko/metasploit_in_termux#16]
![Screenshot_20210214_141858](https://user-images.githubusercontent.com/74790361/107870115-d0c8b700-6ed0-11eb-9540-4492581cbf55.jpg)
 
![Screenshot_20210214_142543](https://user-images.githubusercontent.com/74790361/107870120-daeab580-6ed0-11eb-94ca-6a54585b4ccb.jpg) 
![Screenshot_20210214_142604](https://user-images.githubusercontent.com/74790361/107870123-e6d67780-6ed0-11eb-8eec-1d1c6222be87.jpg)
![Screenshot_20210214_142626](https://user-images.githubusercontent.com/74790361/107870130-f1910c80-6ed0-11eb-8d32-177b0724f1af.jpg)

**Comment by NecrofexColosuss** [comment]
Same :(

**Comment by capunk2708** [comment]
Not respon

**Comment by duranmev** [comment]
Its been a week

**Comment by amirgamalofficial** [comment]
Me too ☃️

**Comment by mitchadams21** [comment]
Unfortunately,  same

**Comment by 21BelowZero** [comment]
Same

**Comment by balapraveenkumar786** [comment]
i too facing same issue.
better owner of this link make a new updated file

**Comment by gascs** [comment]
We can consider installing ruby2.7.2 by ourselves :)

**Comment by 21BelowZero** [comment]
@gascs Is rvm the only way to run 2 versions of ruby simultaneously? I ran into issues going that route as well, but I also have no idea what im doing 🤣🤣

**Comment by balapraveenkumar786** [comment]
> @gascs Is rvm the only way to run 2 versions of ruby simultaneously? I ran into issues going that route as well, but I also have no idea what im doing 🤣🤣

can u say the process we will try it

**Comment by 21BelowZero** [comment]
> > @gascs Is rvm the only way to run 2 versions of ruby simultaneously? I ran into issues going that route as well, but I also have no idea what im doing 🤣🤣
> 
> can u say the process we will try it

If this doesn't belong here, feel free to delete.

     ***warning***
I am new to all of this and learning on the fly, may be unsafe 🤷‍♂️


Work around to install ruby 2.7.2...

Install rvm (reference rvm.io). Once downloaded, edit both files titled "termux" to remove these packages from the code: libclang, libclang-dev, openssl-dev, and zlib-dev.

Now run 'rvm install ruby-2.7.2'. I was able to run 2.7.2 as default ruby version and successfully get metasploit running.

**Comment by MuhammedAhmmed** [comment]
￼ Could not find Ascii85-1.1.0 in any of the sources
Run `bundle install` to install missing gems.


Money solution please

**Comment by gascs** [comment]
> > > @gascs Is rvm the only way to run 2 versions of ruby simultaneously? I ran into issues going that route as well, but I also have no idea what im doing 🤣🤣
> > 
> > can u say the process we will try it
> 
> If this doesn't belong here, feel free to delete.
> 
>      ***warning***
> I am new to all of this and learning on the fly, may be unsafe 🤷‍♂️
> 
> 
> Work around to install ruby 2.7.2...
> 
> Install rvm (reference rvm.io). Once downloaded, edit both files titled "termux" to remove these packages from the code: libclang, libclang-dev, openssl-dev, and zlib-dev.
> 
> Now run 'rvm install ruby-2.7.2'. I was able to run 2.7.2 as default ruby version and successfully get metasploit running.

**Then we seem to have solved the incompatibility between metasploit and ruby3.0**

**Comment by gascs** [comment]
> > > > @gascs Is rvm the only way to run 2 versions of ruby simultaneously? I ran into issues going that route as well, but I also have no idea what im doing 🤣🤣
> > > 
> > > can u say the process we will try it
> > 
> > If this doesn't belong here, feel free to delete.
> > 
> >      ***warning***
> > I am new to all of this and learning on the fly, may be unsafe 🤷‍♂️
> > 
> > 
> > Work around to install ruby 2.7.2...
> > 
> > Install rvm (reference rvm.io). Once downloaded, edit both files titled "termux" to remove these packages from the code: libclang, libclang-dev, openssl-dev, and zlib-dev.
> > 
> > Now run 'rvm install ruby-2.7.2'. I was able to run 2.7.2 as default ruby version and successfully get metasploit running.
> 
> **Then we seem to have solved the incompatibility between metasploit and ruby3.0**
> 

So who will announce some specific solutions :)

**Comment by drygdryg** [comment]
# The best solution
Use [Linux Deploy](https://github.com/meefik/linuxdeploy) + Alpine Linux edge
1. Install Linux Deploy app
2. Configure image:
Distribution: Alpine
Distribution suite: edge
Image size: no less than 1200 MiB
User name: root
SSH - Enable
3. Install distribution :3 dots -> Install
4. Start distribution
5. Connect with SSH (you can use free version of JuiceSSH client) and install Metasploit framework:
```
apk add git build-base autoconf linux-headers ncurses ruby-dev ruby-bigdecimal libpcap-dev zlib-dev sqlite-dev postgresql-dev ruby-bundler
git clone --depth 1 https://github.com/rapid7/metasploit-framework
cd metasploit-framework/
bundle install
```
6. Run it: `./metasploit-framework/msfconsole`

**Comment by avistnm** [comment]
How should I install rvm in a brand new termux??

**Comment by vagedis** [comment]
Thank you very much, it works perfectly.


Get Outlook for Android

**Comment by gascs** [comment]
> How should I install rvm in a brand new termux??

I did not understand what you mean: (

**Comment by avistnm** [comment]
I meant that when I am installing rvm then I am getting this error
![Screenshot_2021-02-20-23-03-20-759_com.termux.jpg](https://user-images.githubusercontent.com/79373546/108615981-34059c80-742f-11eb-86e0-7eb5785f7b3e.jpg)

**Comment by 21BelowZero** [comment]
> I meant that when I am installing rvm then I am getting this error
> ![Screenshot_2021-02-20-23-03-20-759_com.termux.jpg](https://user-images.githubusercontent.com/79373546/108615981-34059c80-742f-11eb-86e0-7eb5785f7b3e.jpg)

I get that error regardless, try closing and then starting a new termux session. Use "rvm -v" to see if RVM successfully installed.

**Comment by gushmazuko** [comment]
I have updated the code, issue has been [fixed](https://github.com/gushmazuko/metasploit_in_termux/commit/80d383b42c8b12e99cbfa4dca0070234c55dff2a). You can also do it manually by following the instructions [here](https://github.com/rapid7/metasploit-framework/issues/14660#issuecomment-803689295)

**Comment by Lord-Rohit** [comment]
> We can consider installing ruby2.7.2 by ourselves :)

Pls tell how to do that
