### ISSUE TITLE
Please help me to solve this issues.

### ISSUE THREAD

**Issue by Admin122312** [gushmazuko/metasploit_in_termux#160]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Bundler could not find compatible versions for gem
"mini_portile2":
  In snapshot (Gemfile.lock):
    mini_portile2 (= 2.8.0)

  In Gemfile:
metasploit-framework was resolved to 6.2.9, which
depends on
      nokogiri was resolved to 1.8.0, which depends on
        mini_portile2 (~> 2.2.0)

Deleting your Gemfile.lock file and running `bundle
install` will rebuild your snapshot from scratch,
using only
the gems in your Gemfile, which may resolve the
conflict.

**Comment by gushmazuko** [comment]
In order to have updated Termux:
- **Purge all data** of Termux in Android Settings
- Uninstall and reinstall latest Termux version from [F-Droid](https://f-droid.org/en/packages/com.termux/) (Version on Play Store is outdated)
- Then launch Termux to initialization, close it (force stop, not swap)
- Reopen and execute:
```bash
source <(curl -fsSL https://kutt.it/msf)
```

**Comment by Admin122312** [comment]
![Screenshot_2022-07-28-15-28-27](https://user-images.githubusercontent.com/109783741/181690288-570f7ff8-2f7a-490f-bcc9-e7409c599b1c.png)
Please help me to solve this problem.

**Comment by krisdowis** [comment]
Just ignore
metasploit will still work with the error

**Comment by nuprostoartem** [comment]
Помогите выбивает ошыбку
![Screenshot_20220801-164022_Termux](https://user-images.githubusercontent.com/110044624/182160837-a4f74879-5e08-470c-b204-174cf00c47cf.jpg)

**Comment by nuprostoartem** [comment]
Помогите даёт ошибку
![Uploading Screenshot_20220801-164022_Termux.jpg…]()

**Comment by krisdowis** [comment]
хорошо.....какой метод вы использовали для установки...автоматический или ручной

**Comment by krisdowis** [comment]
> Помогите выбивает ошыбку
> ![Screenshot_20220801-164022_Termux](https://user-images.githubusercontent.com/110044624/182160837-a4f74879-5e08-470c-b204-174cf00c47cf.jpg)
> 

Это была моя ошибка Я допустил ошибку при внесении кода, но я уже открыл запрос на включение, чтобы исправить это Владелец еще не одобрил, потому что он занят, но вы можете исправить это с помощью команды на данный момент
```
source <(curl -fsSL https://bit.ly/3cTWx5g)
```

**Comment by krisdowis** [comment]
Пожалуйста, дайте мне знать, если вы смогли решить проблему или у вас все еще есть ошибки

**Comment by emilysdead** [comment]
> 

Та же ошибка, можете помочь как решите пожалуйста, я новичок, если можете объяснить буду очень благодарна

**Comment by krisdowis** [comment]
> > 
> 
> Та же ошибка, можете помочь как решите пожалуйста, я новичок, если можете объяснить буду очень благодарна 

Это была моя ошибка Я допустил ошибку при внесении кода, но я уже открыл запрос на включение, чтобы исправить это Владелец еще не одобрил, потому что он занят, но вы можете исправить это с помощью команды на данный момент
```
source <(curl -fsSL https://bit.ly/3cTWx5g)
```

**Comment by krisdowis** [comment]
> > 
> 
> Та же ошибка, можете помочь как решите пожалуйста, я новичок, если можете объяснить буду очень благодарна 

Я объясню, почему это происходит, в строке 101 есть синтаксическая ошибка, ошибка заключается в том, что после «тогда» есть пробел, поэтому, когда код доходит до строки ошибки 101, ошибка приводит к остановке установки, вызывая такие команды, как msfconsole  и мсфвеном не работать

**Comment by gushmazuko** [comment]
Fixed https://github.com/gushmazuko/metasploit_in_termux/commit/65c9cf10e227b945a42e238118158ebfe087d34e

**Comment by Rahulv95** [comment]
> `
![Screenshot_2022-09-23-21-09-08-586_com termux](https://user-images.githubusercontent.com/90695779/191999367-b6af6bc9-3c9d-4902-9ced-0398aa9cd561.jpg)
Help`

**Comment by Rahulv95** [comment]
Please help in fixing this.... 
![Uploading Screenshot_2022-09-23-21-09-08-586_com.termux.jpg…]()

**Comment by Rahulv95** [comment]
Help

**Comment by dedshit** [comment]
> Help

send proper screenshot

**Comment by EBADSIDD** [comment]
$ msfconsole
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.                                Could not find Ascii85-1.1.0 in any of the sourcesRun `bundle install` to install missing gems.
~

How to solve this 
![Screenshot_20220925-221619](https://user-images.githubusercontent.com/114259421/192156693-78e0915e-51cc-4979-9b29-e459f82b7431.jpg)

**Comment by dedshit** [comment]
> $ msfconsole Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead. Could not find Ascii85-1.1.0 in any of the sourcesRun `bundle install` to install missing gems. ~
> 
> How to solve this ![Screenshot_20220925-221619](https://user-images.githubusercontent.com/114259421/192156693-78e0915e-51cc-4979-9b29-e459f82b7431.jpg)

run `bundle install`

**Comment by EBADSIDD** [comment]
~ $ bundle install
bash: /data/data/com.termux/files/usr/bin/bundle: ruby: bad interpreter: No such file or directory

**Comment by dedshit** [comment]
> ~ $ bundle install bash: /data/data/com.termux/files/usr/bin/bundle: ruby: bad interpreter: No such file or directory

just clear everything related to ruby try cloning this repo
