### ISSUE TITLE
Msfvenom

### ISSUE THREAD

**Issue by Medwin3** [gushmazuko/metasploit_in_termux#166]
$ msfvenom
<internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- metasploit/framework/profiler (LoadError)
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /data/data/com.termux/files/usr/bin/msfvenom:23:in `<main>'

**Comment by krisdowis** [comment]
This was my mistake I made an error while contributing to the code but I already opened a pull request to fix it The owner hasn't approved yet because he is busy but you can fix with the command for now ```
source <(curl -fsSL https ://bit.ly/3cTWx5g)
```

**Comment by krisdowis** [comment]
Please let me know if you were able to fix the problem or if you still have errors
