### ISSUE TITLE
Ошыбка

### ISSUE THREAD

**Issue by nuprostoartem** [gushmazuko/metasploit_in_termux#167]
Помогите что делать даёт ошыбку буду рад если поможете
![Screenshot_20220801-164022_Termux](https://user-images.githubusercontent.com/110044624/182175930-202e817d-c9af-4bcc-80b8-59661a162cd4.jpg)

 - Device: Samsung a50

**Comment by krisdowis** [comment]
Попробуйте команду msfconsole прямо сейчас и сообщите мне, если у вас все еще есть проблемы

**Comment by krisdowis** [comment]
Пожалуйста, дайте мне знать, если вы смогли решить проблему или у вас все еще есть ошибки

**Comment by nuprostoartem** [comment]
Всё сробатоло спасибо большое тебе удачи

**Comment by krisdowis** [comment]
всегда пожалуйста.  не забудьте подписаться на меня на github
