### ISSUE TITLE
pcaprub-0.13.0 requires ruby version ~> 2.0, which is incompatible with the current version, ruby 3.0.0p0

### ISSUE THREAD

**Issue by ErrorBot101** [gushmazuko/metasploit_in_termux#17]
![Screenshot_20210222-191407](https://user-images.githubusercontent.com/79076772/108716477-31e03280-7542-11eb-8401-ba9fd9e01f74.png)
![Screenshot_20210222-191359](https://user-images.githubusercontent.com/79076772/108716500-373d7d00-7542-11eb-9028-11ec22e324b6.png)

**Comment by balapraveenkumar786** [comment]
Same issue bro 
Waiting for admin of this thread reply

**Comment by hocine-hj** [comment]
downgrade ur ruby version to 2.7.2

**Comment by balapraveenkumar786** [comment]
> downgrade ur ruby version to 2.7.2

how to do it
Say procedure

**Comment by hocine-hj** [comment]
I use termux docker image I built ruby v 2.7.2 on it
u install this https://github.com/Hax4us/TermuxBlack
remove ur ruby v3 and metasploit too
then install .. apt install ruby2
then edit file metasploit.sh .. delet ruby from it

**Comment by balapraveenkumar786** [comment]
Can you please tell us in step by step
So that we can understand

**Comment by hocine-hj** [comment]
hmm ok .. 
first delet corrent ruby and metasploit too

**Comment by hocine-hj** [comment]
install this https://github.com/Hax4us/TermuxBlack

**Comment by hocine-hj** [comment]
apt install ruby2

**Comment by Anynomas13** [comment]
Why are you messageing me continuesly

**Comment by hocine-hj** [comment]
I did not, , I just wrot that commond

**Comment by BLUE-444** [comment]
![Screenshot_20210311_201325_com.huawei.hidisk.jpg](https://user-images.githubusercontent.com/78936176/110841602-6542f100-82a6-11eb-9222-437223bba4df.jpg) 
When I make an apk payload with metasploit the apk stop downloading in 13kb or 2kb... What's the problem ?

**Comment by ErrorBot101** [comment]
when i am try to install ruby2 by your command "apt install ruby2" i getting this error (termuxblack > pkg install ruby2
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  ruby2
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 0 B/4086 kB of archives.
After this operation, 23.6 MB of additional disk space will be used.
(Reading database ... 36786 files and directories currently installed.)
Preparing to unpack .../ruby2_2.7.2-3_aarch64.deb ...
Unpacking ruby2 (2.7.2-3) ...
dpkg: error processing archive /data/data/com.termux/cache/apt/archives/ruby2_2.7.2-3_aarch64.deb (--unpack):
 trying to overwrite '/data/data/com.termux/files/usr/share/man/man5/gemfile.5.gz', which is also in package ruby 3.0.0
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /data/data/com.termux/cache/apt/archives/ruby2_2.7.2-3_aarch64.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
termuxblack > ) can you please tell me what is wrong with it and what i want to do next i removed ruby from termux from every where like from lib from bin from every where reply fast.

**Comment by avistnm** [comment]
Guys u can use my metasploit framework it is working with all versions of Termux of android 
You can get it from here -
https://github.com/avistnm/Metasploit-avistnm.git

**Comment by gushmazuko** [comment]
Issue is fixed, more info [here](https://github.com/gushmazuko/metasploit_in_termux/issues/16#issuecomment-803701501)!

**Comment by veerkaram869-dev** [comment]
https://github.com/gushmazuko/metasploit_in_termux

**Comment by veerkaram869-dev** [comment]
apt update -y && apt upgrade -y&& pkg install git -y&& git clone https://github.com/gushmazuko/metasploit_in_termux && cd metasploit_in_termux && bash metasploit.sh && msfconsolehttps://github.com/gushmazuko/metasploit_in_termux

**Comment by veerkaram869-dev** [comment]
https://github.com/gushmazuko/metasploit_in_termux

**Comment by veerkaram869-dev** [comment]
#https://github.com/gushmazuko/metasploit_in_termux/issues/17

**Comment by veerkaram869-dev** [comment]
`https://github.com/gushmazuko/metasploit_in_termux```
