### ISSUE TITLE
Bundler could not find compatible versions for
gem "mini_portile2":

### ISSUE THREAD

**Issue by mdfrabby** [gushmazuko/metasploit_in_termux#176]
![Screenshot_2022-08-15-23-17-46-19_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/21121974/184711205-58caad16-ca32-4e87-8541-b7dee73452c2.jpg)

**Comment by Bittu68997** [comment]
Ha bhai ahei a ra hai

**Comment by subash2203** [comment]
![Screenshot_2022-08-16-14-53-10-50_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/111345062/184845519-b1e82276-87ce-4e48-83c5-ec6db0d50c87.jpg)
Please resolve this

**Comment by krisdowis** [comment]
This isn't our repository

**Comment by krisdowis** [comment]
> ![Screenshot_2022-08-15-23-17-46-19_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/21121974/184711205-58caad16-ca32-4e87-8541-b7dee73452c2.jpg)
@mdfrabby 
It's a warning not error
Metasploit will still work

**Comment by krisdowis** [comment]
> > ![Screenshot_2022-08-15-23-17-46-19_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/21121974/184711205-58caad16-ca32-4e87-8541-b7dee73452c2.jpg)
 

@mdfrabby 
It's a warning not error
Metasploit will still work

**Comment by krisdowis** [comment]
This isn't a problem with our repo
It is clearly stated there that you are using m-wiz by noob-hacker so you can go open an issue there

So I can 100% confirm this isn't the repo you cloned

But you can fix the error by downloading the up to date metasploit-framework with this command 
 ```
source <(curl -fsSL https://bit.ly/3cTWx5g)
```
Please let me know if you were able to fix the problem or if you still have errors

**Comment by krisdowis** [comment]
> 
> ![Screenshot_2022-08-16-14-53-10-50_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/111345062/184845519-b1e82276-87ce-4e48-83c5-ec6db0d50c87.jpg)
> Please resolve this
> 

This isn't a problem with our repo
It is clearly stated there that you are using m-wiz by noob-hacker so you can go open an issue there

So I can 100% confirm this isn't the repo you cloned

But you can fix the error by downloading the up to date metasploit-framework with this command 
 ```
source <(curl -fsSL https://bit.ly/3cTWx5g)
```
Please let me know if you were able to fix the problem or if you still have errors

**Comment by mdfrabby** [comment]
Thank you Sir

**Comment by mdfrabby** [comment]
@subash2203 Working fine. Thanks a lot buddy

**Comment by Bittu68997** [comment]
Ok, I will check.
