### ISSUE TITLE
Help this I can't run msfconsole command

### ISSUE THREAD

**Issue by shrinivas2003** [gushmazuko/metasploit_in_termux#180]
**Important**
Do not duplicate, search your issue before creating one!

**Describe the bug**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [poco m3]
 - OS: [
![Screenshot_2022-09-14-10-06-08-582_com termux](https://user-images.githubusercontent.com/107052067/190061581-298cafcc-310d-4296-b36c-2c250502ebcd.jpg)
![Screenshot_2022-09-14-10-09-46-402_com termux](https://user-images.githubusercontent.com/107052067/190061588-c1ca3df6-2eda-41a1-a4a2-7120ae364b31.jpg)
Android 11]

**Comment by ChillVibesMushroom** [comment]
I'm going to try installing SQLite 3 manually okay I'll lyk what's up right now

**Comment by ChillVibesMushroom** [comment]
Pkg install SQLite doesn't fix it

**Comment by ChillVibesMushroom** [comment]
It doesn't work

**Comment by Satyam3265** [comment]
This is also my problem
What the solution anyone help me

**Comment by Techymaster** [comment]
I have solution to this......
Use command:
$ pkg install build-essentials 
After installing Ruby in termux. Then try installing nokogiri manually by using
$ gem install nokogiri -- -- use-system-libraries (after installing metasploit)
Finally run $ bundle install

**Comment by dedshit** [comment]
> **Important** Do not duplicate, search your issue before creating one!
> 
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [poco m3]
> * OS: [
>   ![Screenshot_2022-09-14-10-06-08-582_com termux](https://user-images.githubusercontent.com/107052067/190061581-298cafcc-310d-4296-b36c-2c250502ebcd.jpg)
>   ![Screenshot_2022-09-14-10-09-46-402_com termux](https://user-images.githubusercontent.com/107052067/190061588-c1ca3df6-2eda-41a1-a4a2-7120ae364b31.jpg)
>   Android 11]

#185

**Comment by rohit77983195** [comment]
I can also same problem

**Comment by dedshit** [comment]
> I can also same problem

see #186

**Comment by krisdowis** [comment]
Old version of nokogiri and mini_portile2 & Ruby version are obsolete thats causes major problems during installation process.

**Comment by krisdowis** [comment]
> It doesn't work

The problem isn't Sqlite

**Comment by krisdowis** [comment]
@Techymaster @ChillVibesMushroom @Satyam3265 
Solved.
You can now fix the issue/error by reinstalling,
sorry for the wait.

**Comment by ScarletRodgers** [comment]
I also have a lil bit similar issue.
Please solve this 
Screenshot is here
![Screenshot_20230407-122018_Termux](https://user-images.githubusercontent.com/107828810/230557394-b795d9ac-55e7-4210-bebd-dfa0ad84514d.jpg)
