### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Forhad-449** [gushmazuko/metasploit_in_termux#181]
Please help me. I found this problem .
I am new 

Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.

![Screenshot_20220917-154437](https://user-images.githubusercontent.com/113767522/190850847-8e95a4d7-eb58-4634-b79c-fdc314090d3f.png)

**Comment by varunvic** [comment]
same issue , it was working 1 week before @gushmazuko

**Comment by Ajknight1** [comment]
Same issue here

**Comment by varunvic** [comment]
@krisdowis

**Comment by gushmazuko** [comment]
I'll check today

**Comment by krisdowis** [comment]
okay 
sorry for late reply 
have been busy
i will check now

**Comment by krisdowis** [comment]
@varunvic @Ajknight1 @Forhad-449 
Solved.
You can now fix the issue/error by reinstalling,
sorry for the wait.
