### ISSUE TITLE
An error occurred while installing nokogiri

### ISSUE THREAD

**Issue by rimassolti** [gushmazuko/metasploit_in_termux#184]
An error occurred while installing nokogiri
(1.8.0), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.8.0' --source
'https://rubygems.org/'` succeeds before bundling.
![Uploading Screenshot_2022-09-21-22-32-48-517_com.termux.jpg…]()

**Comment by NowLoadY** [comment]
mine is similar to yours 
![Screenshot_20220922-104712_Termux.jpg](https://user-images.githubusercontent.com/79356856/191647879-cb6de8e1-1ba1-4541-b0db-44ad0a1734b6.jpg)
and then:
![Screenshot_20220922-104740_Termux.jpg](https://user-images.githubusercontent.com/79356856/191647943-39422084-d3c8-4720-900e-c8f498b7285b.jpg)
Then:
![Screenshot_20220922-104814_Termux.jpg](https://user-images.githubusercontent.com/79356856/191647989-751720c0-3219-4956-b6c8-fa53204f9582.jpg)
Finally tried 'msfconsole':
![Screenshot_20220922-105045_Termux.jpg](https://user-images.githubusercontent.com/79356856/191648039-5e9bf152-c693-44d6-84cf-58d539f18dd7.jpg)

Hope these information could help developers to find the solution 😀

**Comment by Kasmorioffi** [comment]
I have the same problem. I already tried to reinstall termux and I already tried different versions of Termux. Maybe it's important to mention that I have android 12 maybe that have a problem with smth ?

**Comment by NowLoadY** [comment]
> I have the same problem. I already tried to reinstall termux and I already tried different versions of Termux. Maybe it's important to mention that I have android 12 maybe that have a problem with smth ?

but I tried it on my Mi6 too, which is using android 9, the same error occurred :(
(the screenshot i sent is android 12)

**Comment by dedshit** [comment]
> > I have the same problem. I already tried to reinstall termux and I already tried different versions of Termux. Maybe it's important to mention that I have android 12 maybe that have a problem with smth ?
> 
> but I tried it on my Mi6 too, which is using android 9, the same error occurred :( (the screenshot i sent is android 12)

see #185

**Comment by dedshit** [comment]
@NowLoadY 
[Metasploit-fix.zip](https://github.com/gushmazuko/metasploit_in_termux/files/9623964/Metasploit-fix.zip)
 or try my package

**Comment by krisdowis** [comment]
Old version of nokogiri and mini_portile2 & Ruby version are obsolete thats causes major problems during installation process.

**Comment by krisdowis** [comment]
@NowLoadY  @rimassolti @Kasmorioffi 
Solved.
You can now fix the issue/error by reinstalling,
sorry for the wait.

**Comment by gushmazuko** [comment]
Fixed https://github.com/gushmazuko/metasploit_in_termux/pull/185

**Comment by MrS0n1CTF** [comment]
> mine is similar to yours ![Screenshot_20220922-104712_Termux.jpg](https://user-images.githubusercontent.com/79356856/191647879-cb6de8e1-1ba1-4541-b0db-44ad0a1734b6.jpg) and then: ![Screenshot_20220922-104740_Termux.jpg](https://user-images.githubusercontent.com/79356856/191647943-39422084-d3c8-4720-900e-c8f498b7285b.jpg) Then: ![Screenshot_20220922-104814_Termux.jpg](https://user-images.githubusercontent.com/79356856/191647989-751720c0-3219-4956-b6c8-fa53204f9582.jpg) Finally tried 'msfconsole': ![Screenshot_20220922-105045_Termux.jpg](https://user-images.githubusercontent.com/79356856/191648039-5e9bf152-c693-44d6-84cf-58d539f18dd7.jpg)
> 
> Hope these information could help developers to find the solution 😀

Hi! 🛡️ I noticed you're having trouble with Metasploit dependencies on Termux. 🛠️ I've developed a professional toolkit specifically to automate environment repairs (Nokogiri/Gumbo fixes) and provide a stable workspace for MSF on Android. 🚀 It might be exactly what you need! Check it out here: https://github.com/MrS0n1CTF/MSF-repair_Toolkit 🦅✨

**Comment by MrS0n1CTF** [comment]
> I have the same problem. I already tried to reinstall termux and I already tried different versions of Termux. Maybe it's important to mention that I have android 12 maybe that have a problem with smth ?

Hi! 🛡️ I noticed you're having trouble with Metasploit dependencies on Termux. 🛠️ I've developed a professional toolkit specifically to automate environment repairs (Nokogiri/Gumbo fixes) and provide a stable workspace for MSF on Android. 🚀 It might be exactly what you need! Check it out here: https://github.com/MrS0n1CTF/MSF-repair_Toolkit 🦅✨

**Comment by MrS0n1CTF** [comment]
> > I have the same problem. I already tried to reinstall termux and I already tried different versions of Termux. Maybe it's important to mention that I have android 12 maybe that have a problem with smth ?
> 
> but I tried it on my Mi6 too, which is using android 9, the same error occurred :( (the screenshot i sent is android 12)

Hi! 🛡️ I noticed you're having trouble with Metasploit dependencies on Termux. 🛠️ I've developed a professional toolkit specifically to automate environment repairs (Nokogiri/Gumbo fixes) and provide a stable workspace for MSF on Android. 🚀 It might be exactly what you need! Check it out here: https://github.com/MrS0n1CTF/MSF-repair_Toolkit 🦅✨

**Comment by MrS0n1CTF** [comment]
> [@NowLoadY](https://github.com/NowLoadY) [Metasploit-fix.zip](https://github.com/gushmazuko/metasploit_in_termux/files/9623964/Metasploit-fix.zip) or try my package

Hi! 🛡️ I noticed you're having trouble with Metasploit dependencies on Termux. 🛠️ I've developed a professional toolkit specifically to automate environment repairs (Nokogiri/Gumbo fixes) and provide a stable workspace for MSF on Android. 🚀 It might be exactly what you need! Check it out here: https://github.com/MrS0n1CTF/MSF-repair_Toolkit 🦅✨

**Comment by MrS0n1CTF** [comment]
> Fixed [#185](https://github.com/gushmazuko/metasploit_in_termux/pull/185)

Hi! 🛡️ I noticed you're having trouble with Metasploit dependencies on Termux. 🛠️ I've developed a professional toolkit specifically to automate environment repairs (Nokogiri/Gumbo fixes) and provide a stable workspace for MSF on Android. 🚀 It might be exactly what you need! Check it out here: https://github.com/MrS0n1CTF/MSF-repair_Toolkit 🦅✨
