### ISSUE TITLE
Error when doing msfconsole

### ISSUE THREAD

**Issue by Kasmorioffi** [gushmazuko/metasploit_in_termux#188]
Hallo, after the bug fix with the installation the installation is not working but when I type in msfconsole I get many error message (i got a screenshot from it)
![Screenshot_20220925-102453_Termux](https://user-images.githubusercontent.com/86166088/192135230-0e6c3d70-8099-4020-9af4-208058b033c2.jpg)

**Comment by dedshit** [comment]
@Kasmorioffi  please take a look into [patch](https://github.com/dedshit/metasploit_in_termux/issues/10)

**Comment by dedshit** [comment]
> Hallo, after the bug fix with the installation the installation is not working but when I type in msfconsole I get many error message (i got a screenshot from it) ![Screenshot_20220925-102453_Termux](https://user-images.githubusercontent.com/86166088/192135230-0e6c3d70-8099-4020-9af4-208058b033c2.jpg)

are you available in whatsapp. if yes contact +918428425154 me

**Comment by Kasmorioffi** [comment]
> > Hallo, after the bug fix with the installation the installation is not working but when I type in msfconsole I get many error message (i got a screenshot from it) ![Screenshot_20220925-102453_Termux](https://user-images.githubusercontent.com/86166088/192135230-0e6c3d70-8099-4020-9af4-208058b033c2.jpg)
> 
> are you available in whatsapp. if yes contact +918428425154 me

Hello, the problem was solved after reinstalling termux a few times and trying it again.
