### ISSUE TITLE
Could not find nokogiri-1.8.0

### ISSUE THREAD

**Issue by EBADSIDD** [gushmazuko/metasploit_in_termux#189]
~ $ msfconsole
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Could not find nokogiri-1.8.0
![Screenshot_20220925-164524](https://user-images.githubusercontent.com/114259421/192141720-2a974913-9d82-4f4f-b190-6aa6a53b35bd.jpg)
 in any of the sources

**Comment by dedshit** [comment]
run `uname -m` and send a screenshot

**Comment by EBADSIDD** [comment]
> run `uname -m` and send a screenshot

![Uploading Screenshot_20220925-170953.jpg…]()

**Comment by EBADSIDD** [comment]
> run `uname -m` and send a screenshot

![Screenshot_20220925-170953](https://user-images.githubusercontent.com/114259421/192142732-5e26ce9c-9b66-4e0a-bb81-2683751337c7.jpg)

**Comment by dedshit** [comment]
> > run `uname -m` and send a screenshot
> 
> ![Screenshot_20220925-170953](https://user-images.githubusercontent.com/114259421/192142732-5e26ce9c-9b66-4e0a-bb81-2683751337c7.jpg)

clone this repo and run `bash metasploit.sh`
