### ISSUE TITLE
./postgresql_ctl.sh start not working and msfconsole too

### ISSUE THREAD

**Issue by Daandroidian** [gushmazuko/metasploit_in_termux#19]
Hi when i finish downloading metasploit none of the command title work here a screenshot.

![Screenshot_20210326-183519_Termux.jpg](https://user-images.githubusercontent.com/81447673/112699817-0616dc00-8e63-11eb-93d7-882405582509.jpg)

**Comment by BLUE-444** [comment]
Make sure you have at least 600 MB on your phone's storage 
And download it from https://github.com/gushmazuko/metasploit_in_termux

**Comment by Daandroidian** [comment]
> Make sure you have at least 600 MB on your phone's storage 
> And download it from https://github.com/gushmazuko/metasploit_in_termux

I have more than 600mb of storage in my phone and i downloades it from https://github.com/gushmazuko/metasploit_in_termux

**Comment by BLUE-444** [comment]
Hmm, wait for Admin to solve the problem.
@gushmazuko

**Comment by Daandroidian** [comment]
Ok

**Comment by atefnino** [comment]
![Uploading Screenshot_20210329-090856_Termux.jpg…]()
Same problem

**Comment by abhinav-sketch** [comment]
> Hi when i finish downloading metasploit none of the command title work here a screenshot.
> 
> ![Screenshot_20210326-183519_Termux.jpg](https://user-images.githubusercontent.com/81447673/112699817-0616dc00-8e63-11eb-93d7-882405582509.jpg)

**Comment by gushmazuko** [comment]
@Daandroidian redirect your installation logs to a file and send it here please. You can do it by following comand:
```bash
source <(curl -fsSL https://kutt.it/msf) 2>&1 | tee mfs-install.log
```

**Comment by Daandroidian** [comment]
> @Daandroidian redirect your installation logs to a file and send it here please. You can do it by following command:
> ```bash
> source <(curl -fsSL https://kutt.it/msf) 2>&1 | tee mfs-install.log
> ```

I did the command what do i have to do now?

**Comment by gushmazuko** [comment]
> > @Daandroidian redirect your installation logs to a file and send it here please. You can do it by following command:
> > ```shell
> > source <(curl -fsSL https://kutt.it/msf) 2>&1 | tee mfs-install.log
> > ```
> 
> I did the command what do i have to do now?

Upload this file to https://pastebin.com and share your link here

**Comment by Daandroidian** [comment]
> > > @Daandroidian redirect your installation logs to a file and send it here please. You can do it by following command:
> > > ```shell
> > > source <(curl -fsSL https://kutt.it/msf) 2>&1 | tee mfs-install.log
> > > ```
> > 
> > I did the command what do i have to do now?
> 
> Upload this file to https://pastebin.com and share your link here

Where does the file is? I am not finding it?

**Comment by gushmazuko** [comment]
> 
> 
> > > > @Daandroidian redirect your installation logs to a file and send it here please. You can do it by following command:
> > > > ```shell
> > > > source <(curl -fsSL https://kutt.it/msf) 2>&1 | tee mfs-install.log
> > > > ```
> > > 
> > > 
> > > I did the command what do i have to do now?
> > 
> > 
> > Upload this file to https://pastebin.com and share your link here
> 
> Where does the file is? I am not finding it?

In currenet directory (where you execute the command).

**Comment by Daandroidian** [comment]
This is the log file txt i cant upload to pastebin idk why

**Comment by Daandroidian** [comment]
[H[2J[3J +-+-+-+-+-+-+-+-+-+-+ +-+-+ +-+-+-+-+-+-+ |M|e|t|a|s|p|l|o|i|t| |i|n| |T|e|r|m|u|x| +-+-+-+-+-+-+-+-+-+-+ +-+-+ +-+-+-+-+-+-+ +-+-+ +-+-+-+-+-+-+-+-+-+-+ |b|y| |G|u|s|h|m|a|z|u|k|o| +-+-+ +-+-+-+-+-+-+-+-+-+-+ ========================= Loading... ========================== | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | =============== *** Dependencies installation... =============== deb https://github.com/gushmazuko/metasploit_in_termux/raw/master gushmazuko main Testing the available mirrors: [*] https://termux.org/packages: ok [*] https://10.via0.com/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx: ok [*] https://termux.mentality.rip/termux-packages-24: ok [*] https://ipfs.io/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx: ok [*] https://grimler.se/termux-packages-24: ok Picking mirror: https://termux.mentality.rip/termux-packages-24 WARNING: apt does not have a stable CLI interface. Use with caution in scripts. Get:1 https://ipfs.io/ipns/k51qzi5uqu5dj05z8mr958kwvrg7a0wqouj5nnoo5uqu1btnsljvpznfaav9nk unstable InRelease [14.0 kB] Get:3 https://grimler.se/game-packages-24 games InRelease [12.5 kB] Get:4 https://termux.mentality.rip/termux-packages-24 stable InRelease [13.1 kB] Get:5 https://grimler.se/science-packages-24 science InRelease [13.3 kB] Get:2 https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master gushmazuko InRelease [7397 B] Get:6 https://ipfs.io/ipns/k51qzi5uqu5dj05z8mr958kwvrg7a0wqouj5nnoo5uqu1btnsljvpznfaav9nk unstable/main aarch64 Packages [13.4 kB] Get:7 https://grimler.se/game-packages-24 games/stable aarch64 Packages [7137 B] Get:8 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 Packages [261 kB] Get:9 https://termux.mentality.rip/termux-packages-24 stable/main all Packages [20.4 kB] Get:10 https://grimler.se/science-packages-24 science/stable aarch64 Packages [28.8 kB] Err:2 https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master gushmazuko InRelease The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 46C9F2CB506F14B4 Reading package lists... W: GPG error: https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master gushmazuko InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 46C9F2CB506F14B4 E: The repository 'https://github.com/gushmazuko/metasploit_in_termux/raw/master gushmazuko InRelease' is not signed. The program gpg is not installed. Install it by executing: pkg install gnupg curl: (23) Failed writing body ## Set low priority for all gushmazuko repository (for security purposes) Package: * Pin: release gushmazuko Pin-Priority: 100 ## Set highest priority for ruby package from gushmazuko repository Package: ruby Pin: release gushmazuko Pin-Priority: 1001 WARNING: apt does not have a stable CLI interface. Use with caution in scripts. Reading package lists... Building dependency tree... Reading state information... Package 'ruby' is not installed, so not removed The following packages were automatically installed and are no longer required: bc flex imlib2 libandroid-shmem libcaca libgc libid3tag libx11 libxau libxcb libxdmcp libxext m4 man ncurses-utils Use 'apt autoremove' to remove them. 0 upgraded, 0 newly installed, 0 to remove and 12 not upgraded. Checking availability of current mirror: ok WARNING: apt does not have a stable CLI interface. Use with caution in scripts. Get:2 https://ipfs.io/ipns/k51qzi5uqu5dj05z8mr958kwvrg7a0wqouj5nnoo5uqu1btnsljvpznfaav9nk unstable InRelease [14.0 kB] Hit:3 https://grimler.se/game-packages-24 games InRelease Hit:4 https://termux.mentality.rip/termux-packages-24 stable InRelease Get:1 https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master gushmazuko InRelease [7397 B] Hit:5 https://grimler.se/science-packages-24 science InRelease Err:1 https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master gushmazuko InRelease The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 46C9F2CB506F14B4 Reading package lists... W: GPG error: https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master gushmazuko InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 46C9F2CB506F14B4 E: The repository 'https://github.com/gushmazuko/metasploit_in_termux/raw/master gushmazuko InRelease' is not signed. Checking availability of current mirror: ok WARNING: apt does not have a stable CLI interface. Use with caution in scripts. Reading package lists... Building dependency tree... Reading state information... coreutils is already the newest version (8.32-7). findutils is already the newest version (4.8.0). libffi is already the newest version (3.3-2). libffi set to manually installed. libgmp is already the newest version (6.2.1). libxml2 is already the newest version (2.9.10-4). libxml2 set to manually installed. libxslt is already the newest version (1.1.34-1). libxslt set to manually installed. ncurses is already the newest version (6.2.20200725-2). ncurses-utils is already the newest version (6.2.20200725-2). ncurses-utils set to manually installed. readline is already the newest version (8.1.0). tar is already the newest version (1.34). unzip is already the newest version (6.0-7). wget is already the newest version (1.21.1). The following packages were automatically installed and are no longer required: bc flex imlib2 libcaca libgc libid3tag libx11 libxau libxcb libxdmcp libxext man Use 'apt autoremove' to remove them. The following additional packages will be installed: binutils c-ares gdbm glib libcurl libexpat libllvm libltdl libprotobuf libyaml ncurses-ui-libs ndk-sysroot perl protobuf Suggested packages: python-tkinter termux-api The following NEW packages will be installed: apr apr-util autoconf binutils bison c-ares clang gdbm glib libexpat libgrpc libllvm libltdl libpcap libprotobuf libtool libyaml make ncurses-ui-libs ndk-sysroot perl pkg-config postgresql protobuf python ruby termux-elf-cleaner zip The following packages will be upgraded: curl git libcurl libsqlite openssl termux-tools 6 upgraded, 28 newly installed, 0 to remove and 6 not upgraded. Need to get 86.7 MB of archives. After this operation, 462 MB of additional disk space will be used. Get:1 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 openssl aarch64 1.1.1k-2 [1150 kB] Get:2 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 libcurl aarch64 7.76.1 [867 kB] Get:3 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 curl aarch64 7.76.1 [157 kB] Get:4 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 termux-tools all 0.118 [18.2 kB] Get:5 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 apr aarch64 1.7.0-3 [224 kB] Get:6 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 libexpat aarch64 2.2.10 [68.2 kB] Get:7 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 apr-util aarch64 1.6.1-3 [107 kB] Get:8 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 make aarch64 4.3-1 [219 kB] Get:9 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 perl aarch64 5.32.1 [14.5 MB] Err:9 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 perl aarch64 5.32.1 Error reading from server - read (5: I/O error) [IP: 135.181.76.187 443] Get:10 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 autoconf all 2.71 [613 kB] Get:11 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 binutils aarch64 2.36.1 [2413 kB] Get:12 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 bison aarch64 3.7.5 [492 kB] Get:13 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 c-ares aarch64 1.17.1-1 [112 kB] Get:14 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 ndk-sysroot aarch64 21d [1514 kB] Get:15 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 libllvm aarch64 11.1.0 [18.0 MB] Get:16 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 clang aarch64 11.1.0 [18.3 MB] Get:17 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 gdbm aarch64 1.19 [104 kB] Get:18 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 git aarch64 2.31.1 [2886 kB] Get:19 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 glib aarch64 2.66.1 [1094 kB] Get:20 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 libprotobuf aarch64 2:3.14.0 [964 kB] Get:21 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 protobuf aarch64 2:3.14.0 [735 kB] Get:22 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 libgrpc aarch64 1.35.0 [2081 kB] Get:23 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 libltdl aarch64 2.4.6-8 [12.3 kB] Get:24 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 libpcap aarch64 1.10.0 [214 kB] Get:25 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 libsqlite aarch64 3.35.4 [528 kB] Get:26 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 libtool aarch64 2.4.6-8 [375 kB] Get:27 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 libyaml aarch64 0.2.5-4 [43.8 kB] Get:28 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 ncurses-ui-libs aarch64 6.2.20200725-2 [29.1 kB] Get:29 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 pkg-config aarch64 0.29.2 [25.9 kB] Get:30 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 postgresql aarch64 13.1-4 [4949 kB] Get:31 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 python aarch64 3.9.4 [8071 kB] Get:32 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 ruby aarch64 3.0.0 [5752 kB] Get:33 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 termux-elf-cleaner aarch64 1.7 [3752 B] Get:34 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 zip aarch64 3.0-5 [141 kB] Fetched 72.3 MB in 56s (1281 kB/s) E: Failed to fetch https://termux.mentality.rip/termux-packages-24/pool/main/p/perl/perl_5.32.1_aarch64.deb Error reading from server - read (5: I/O error) [IP: 135.181.76.187 443] E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing? The program python3 is not installed. Install it by executing: pkg install python The program python3 is not installed. Install it by executing: pkg install python =================== *** Fix ruby BigDecimal ==================== WARNING: apt does not have a stable CLI interface. Use with caution in scripts. Reading package lists... Building dependency tree... Reading state information... The following packages were automatically installed and are no longer required: bc flex imlib2 libandroid-shmem libcaca libgc libid3tag libx11 libxau libxcb libxdmcp libxext m4 man ncurses-utils Use 'apt autoremove' to remove them. The following NEW packages will be installed: patchelf 0 upgraded, 1 newly installed, 0 to remove and 12 not upgraded. Need to get 52.2 kB of archives. After this operation, 217 kB of additional disk space will be used. Get:1 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 patchelf aarch64 0.12 [52.2 kB] Fetched 52.2 kB in 1s (62.8 kB/s) Selecting previously unselected package patchelf. (Reading database ... (Reading database ... 5% (Reading database ... 10% (Reading database ... 15% (Reading database ... 20% (Reading database ... 25% (Reading database ... 30% (Reading database ... 35% (Reading database ... 40% (Reading database ... 45% (Reading database ... 50% (Reading database ... 55% (Reading database ... 60% (Reading database ... 65% (Reading database ... 70% (Reading database ... 75% (Reading database ... 80% (Reading database ... 85% (Reading database ... 90% (Reading database ... 95% (Reading database ... 100% (Reading database ... 11817 files and directories currently installed.) Preparing to unpack .../patchelf_0.12_aarch64.deb ... Unpacking patchelf (0.12) ... Setting up patchelf (0.12) ... Processing triggers for man (1.14.5-2) ... ============= *** Erasing old metasploit folder... ============= ====================== *** Downloading... ====================== Cloning into 'metasploit-framework'... error: RPC failed; curl 56 OpenSSL SSL_read: Connection reset by peer, errno 104 error: 3154 bytes of body are still expected fetch-pack: unexpected disconnect while reading sideband packet fatal: early EOF fatal: fetch-pack: invalid index-pack output ===================== *** Installation... ====================== bash: cd: /data/data/com.termux/files/home/metasploit-framework: No such file or directory sed: can't read Gemfile.lock: No such file or directory sed: can't read metasploit-framework.gemspec: No such file or directory The program gem is not installed. Install it by executing: pkg install ruby sed: can't read Gemfile.lock: No such file or directory The program gem is not installed. Install it by executing: pkg install ruby The program gem is not installed. Install it by executing: pkg install ruby The program bundle is not installed. Install it by executing: pkg install ruby The program bundle is not installed. Install it by executing: pkg install ruby The program bundle is not installed. Install it by executing: pkg install ruby rm: cannot remove './modules/auxiliary/gather/http_pdf_authors.rb': No such file or directory The program termux-elf-cleaner is not installed. Install it by executing: pkg install termux-elf-cleaner ================ *** Database configuration... ================= bash: cd: /data/data/com.termux/files/home/metasploit-framework/config: No such file or directory The program initdb is not installed. Install it by executing: pkg install postgresql The program pg_ctl is not installed. Install it by executing: pkg install postgresql The program createuser is not installed. Install it by executing: pkg install postgresql The program createdb is not installed. Install it by executing: pkg install postgresql ============================== * =============================== [32m Installation complete. To start msf database use: ./postgresql_ctl.sh start Launch metasploit by executing: msfconsole[0m ============================== * ===============================

**Comment by anonymouskhalid** [comment]
I also have same problem 
When I executr msfconsole it says ,,command not found
![Screenshot_2021-06-01-22-47-52-45_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/85188649/120365877-96bedc00-c32c-11eb-91b7-6bd13f15181b.jpg)

**Comment by KISHU1234** [comment]
Not useful

**Comment by roodyridar2** [comment]
You can this way to start sql:

pkg install pg_ctl 

mkdir -p $PREFIX/var/lib/postgresql 

initdb $PREFIX/var/lib/postgresql 

pg_ctl -D $PREFIX/var/lib/postgresql start

**Comment by yesahek** [comment]
https://youtu.be/_JaEhpgm_uE

**Comment by AndroidLurker** [comment]
Help pls




![Screenshot_20210926-225454_Termux](https://user-images.githubusercontent.com/91424305/134813228-29111288-2f8e-4b51-895b-9214e30b8226.jpg)

**Comment by yesahek** [comment]
Look how i install it 
https://youtu.be/_JaEhpgm_uE

**Comment by gushmazuko** [comment]
https://github.com/gushmazuko/metasploit_in_termux/issues/67#issuecomment-966387632
