### ISSUE TITLE
nokogiri not installing

### ISSUE THREAD

**Issue by Dstar001** [gushmazuko/metasploit_in_termux#190]
An error occurred while installing nokogiri (1.13.8), and Bundler cannot
continue.

In Gemfile:
  factory_bot_rails was resolved to 6.2.0, which depends on
    railties was resolved to 6.1.7, which depends on
      actionpack was resolved to 6.1.7, which depends on
        actionview was resolved to 6.1.7, which depends on
          rails-dom-testing was resolved to 2.0.3, which depends on
            nokogiri

**Comment by dedshit** [comment]
**`gem install nokogiri --platform=ruby -- --use-system-libraries`**
