### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Jesusjimmy** [gushmazuko/metasploit_in_termux#196]
**Important**
Please solve my problem 

**Screenshots**
![IMG20220928165519](https://user-images.githubusercontent.com/114582749/192770521-80e662aa-299f-4ec9-a9a1-aa35555bf028.jpg)

**Smartphone (please complete the following information):**
 - Device: [Vivo y91i ]
 - OS: [Android 8.1]

**Comment by dedshit** [comment]
run `bundle` and send ss

**Comment by Jesusjimmy** [comment]
![Uploading Screenshot_2022_0928_231313.jpg…]()

**Comment by Jesusjimmy** [comment]
Bundle ss 
![Uploading IMG20220928232034.jpg…]()

**Comment by dedshit** [comment]
send again

**Comment by Jesusjimmy** [comment]
![Uploading IMG20220928232034.jpg…]()

**Comment by dedshit** [comment]
dude just wait for the file to upload then send

**Comment by Jesusjimmy** [comment]
> send again

![Uploading IMG20220928232034.jpg…]()

**Comment by Jesusjimmy** [comment]
Ok

**Comment by Jesusjimmy** [comment]
> dude just wait for the file to upload then send

![IMG20220928232034](https://user-images.githubusercontent.com/114582749/192854587-bdf54e03-3e42-4d2f-ae29-db96f350bbfd.jpg)

**Comment by dedshit** [comment]
looks like bundle itself corrupt

**Comment by Jesusjimmy** [comment]
What I do to install metasploit framework

**Comment by dedshit** [comment]
whats your ruby version @Jesusjimmy

**Comment by Jesusjimmy** [comment]
Please solve this

**Comment by Jesusjimmy** [comment]
> whats your ruby version @Jesusjimmy

I don't know

**Comment by Jesusjimmy** [comment]
![IMG20220928233425](https://user-images.githubusercontent.com/114582749/192856030-4b40c560-f436-4b91-b781-7e6ed9ea0fb5.jpg)

**Comment by dedshit** [comment]
> whats your ruby version @Jesusjimmy
> 
> you can check thay by running `ruby --version`

@Jesusjimmy

**Comment by dedshit** [comment]
> ![IMG20220928233425](https://user-images.githubusercontent.com/114582749/192856030-4b40c560-f436-4b91-b781-7e6ed9ea0fb5.jpg)

looks like you didnt even upgrade pkg's

**Comment by Jesusjimmy** [comment]
![IMG20220928234648](https://user-images.githubusercontent.com/114582749/192858737-705ffcca-d192-48b6-a6e1-baa9aac308e2.jpg)
