### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Jesusjimmy** [gushmazuko/metasploit_in_termux#197]
**Important**
Please solve it

**Describe the bug**

**Screenshots**
![IMG20220929000649](https://user-images.githubusercontent.com/114582749/192862164-0c02b644-2005-41bd-b312-4b8b6454913f.jpg)
![IMG20220929000915](https://user-images.githubusercontent.com/114582749/192862494-fc04bce8-1178-49e2-9535-bf487f419e39.jpg)
![IMG20220929001003](https://user-images.githubusercontent.com/114582749/192862650-76d4b1a5-5f7d-405c-91b9-c0e0eb6578aa.jpg)
![IMG20220929001038](https://user-images.githubusercontent.com/114582749/192862769-752711b6-2e1a-42f1-bfeb-c10d5b5a5783.jpg)

**Smartphone (please complete the following information):**
 - Device: Vivo y91i 
 - OS: Android 8.1

**Comment by dedshit** [comment]
install binutils

**Comment by dedshit** [comment]
> **Important** Please solve it
> 
> **Describe the bug**
> 
> **Screenshots** ![IMG20220929000649](https://user-images.githubusercontent.com/114582749/192862164-0c02b644-2005-41bd-b312-4b8b6454913f.jpg) ![IMG20220929000915](https://user-images.githubusercontent.com/114582749/192862494-fc04bce8-1178-49e2-9535-bf487f419e39.jpg) ![IMG20220929001003](https://user-images.githubusercontent.com/114582749/192862650-76d4b1a5-5f7d-405c-91b9-c0e0eb6578aa.jpg) ![IMG20220929001038](https://user-images.githubusercontent.com/114582749/192862769-752711b6-2e1a-42f1-bfeb-c10d5b5a5783.jpg)
> 
> **Smartphone (please complete the following information):**
> 
> * Device: Vivo y91i
> * OS: Android 8.1

run `gem` command

**Comment by dedshit** [comment]
if everything fine run these `gem install --no-document rubygems-update; update_rubygems
` & `gem install --no-document bundler`

**Comment by Jesusjimmy** [comment]
![IMG20220929004503](https://user-images.githubusercontent.com/114582749/192869263-db885dc7-3e05-4dc0-9024-7b29d5cbe963.jpg)

**Comment by Jesusjimmy** [comment]
> if everything fine run these `gem install --no-document rubygems-update; update_rubygems ` & `gem install --no-document bundler`

![IMG20220929004816](https://user-images.githubusercontent.com/114582749/192869814-cbf7d7b8-bd4d-4222-8967-4ddd66fb12a8.jpg)

**Comment by dedshit** [comment]
now run `bundle`

**Comment by Jesusjimmy** [comment]
> now run `bundle`

![IMG20220929130414](https://user-images.githubusercontent.com/114582749/192968952-8d2f6083-ec84-4629-88db-bc14990edf82.jpg)

**Comment by dedshit** [comment]
> **Important** Please solve it

> 
> **Smartphone (please complete the following information):**
> 
> * Device: Vivo y91i
> * OS: Android 8.1

now try to clone this repo and do what you did in previous

**Comment by chiragb76** [comment]
I've got the fix. They have an script worked for me [source](https://youtu.be/c08713O7prU)

**Comment by dedshit** [comment]
@chiragb76 dont promote your content here its not right place

**Comment by Mwayayaj** [comment]
> 

@dedshit I have the same problem after following all steps  it is working for me, thanks
