### ISSUE TITLE
After install the console errors out 

### ISSUE THREAD

**Issue by Darkcast** [gushmazuko/metasploit_in_termux#2]
####################################
$ msfconsole
metasploit-credential not in the bundle, so Metasploit::Credential creation will fail for Msf::DBManager
Traceback (most recent call last):
        31: from /data/data/com.termux/files/usr/bin/msfconsole:48:in `<main>'
        30: from /data/data/com.termux/files/usr/bin/msfconsole:48:in `require'
        29: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
        28: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
        27: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
        26: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
        25: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core.rb:47:in `<top (required)>'
        24: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
        23: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
        22: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:24:in `<top (required)>'
        21: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:65:in `<class:DBManager>'
        20: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:115:in `optionally_include_metasploit_credential_creation'
        19: from /data/data/com.termux/files/hom

**Comment by sharad740** [comment]
same problem here

**Comment by pple7000** [comment]
Maybe you don't have a database .Create one.

**Comment by gushmazuko** [comment]
Fixed
