### ISSUE TITLE
unable to load modules

### ISSUE THREAD

**Issue by CodyAvi** [gushmazuko/metasploit_in_termux#20]
![IMG_20210327_230308](https://user-images.githubusercontent.com/79373546/112729594-fd053800-8f52-11eb-82a4-1a30fa30ae8f.jpg)

Please Solve this error

**Comment by avistnm** [comment]
@gushmazuko

**Comment by gushmazuko** [comment]
> @gushmazuko

Please poste your `~/.msf4/logs/framework.log`

**Comment by addi7** [comment]
Help me how to install missing gems plz ![Screenshot_20210407-032855.png](https://user-images.githubusercontent.com/56815395/113793617-67875680-9751-11eb-8cff-d65d62fb63b1.png)

**Comment by avistnm** [comment]
On running `~/.msf4/logs/framework.log`
I am getting this `bash: /data/data/com.termux/files/home/.msf4/logs/framework.log: No such file or directory`

**Comment by avistnm** [comment]
I wrote this `~/.msf4/logs/framework.log`

and got this 
![IMG_20210409_085306.jpg](https://user-images.githubusercontent.com/79373546/114123971-04dcb900-9911-11eb-902b-3dc11ad45590.jpg)

**Comment by avistnm** [comment]
@gushmazuko

**Comment by gushmazuko** [comment]
> @gushmazuko

Share your `~/.msf4/logs/framework.log` here, you do it via https://pastebin.com/
