### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ha-ha-ha777** [gushmazuko/metasploit_in_termux#200]
В конце установки выходит ошибка 
failed to create symbolic link на msfconsole и на msfvenom 
![Screenshot_20221015-010728_Termux](https://user-images.githubusercontent.com/75281726/195951007-a210fe2f-0d6a-4dcc-a39f-a44d1633759d.jpg)

**Comment by SeifStar** [comment]
How do I solve this error? I need help from everyone. 🤔
![IMG-20221015-WA0033](https://user-images.githubusercontent.com/115873902/195982417-f7cf0c87-b660-4a6e-a19c-57803ffb5669.jpg)

**Comment by dedshit** [comment]
@SeifStar  install Ascii gem

**Comment by ha-ha-ha777** [comment]
> > В конце установки выходит ошибка не удалось создать символическую ссылку на msfconsole и на msfvenom![Скриншот_20221015-010728_Termux](https://user-images.githubusercontent.com/75281726/195951007-a210fe2f-0d6a-4dcc-a39f-a44d1633759d.jpg)
> 
> отправить полный журнал

![Screenshot_20221015-010728_Termux](https://user-images.githubusercontent.com/75281726/195983834-6ad92ddc-9190-489f-8b1c-2c80ca9bf20b.jpg)
![Screenshot_20221015-141817_Termux](https://user-images.githubusercontent.com/75281726/195983839-070d4f8d-f3f8-4109-bdb6-71b24768fe0f.jpg)
![Screenshot_20221015-141834_Termux](https://user-images.githubusercontent.com/75281726/195983845-81aea519-d894-4e7a-8576-b11110f38a41.jpg)
![Screenshot_20221015-141848_Termux](https://user-images.githubusercontent.com/75281726/195983851-5215148a-075f-4672-b91d-e351624ea59c.jpg)
![Screenshot_20221015-141903_Termux](https://user-images.githubusercontent.com/75281726/195983854-1a6a8c3b-13ac-4f8c-9a81-bd751ab8beaa.jpg)
![Screenshot_20221015-141927_Termux](https://user-images.githubusercontent.com/75281726/195983861-4b070307-1910-4cf4-bcb7-0556d46c77be.jpg)
![Screenshot_20221015-141939_Termux](https://user-images.githubusercontent.com/75281726/195983864-56565565-8c4b-46c5-a772-f76e4e5a9613.jpg)
![Screenshot_20221015-141956_Termux](https://user-images.githubusercontent.com/75281726/195983869-122f49bf-d45c-4dcd-9736-c03a1bfa8fa8.jpg)
![Screenshot_20221015-142012_Termux](https://user-images.githubusercontent.com/75281726/195983874-04f1a35e-37b5-4354-97b9-3e0a584e500e.jpg)
![Screenshot_20221015-142028_Termux](https://user-images.githubusercontent.com/75281726/195983880-4848a872-c490-4690-9bf9-47d90b4e7e6e.jpg)
![Screenshot_20221015-142039_Termux](https://user-images.githubusercontent.com/75281726/195983882-e1e61af6-a928-4576-8efc-ae9accd0fc50.jpg)
![Screenshot_20221015-142052_Termux](https://user-images.githubusercontent.com/75281726/195983888-b5ee4817-d0c4-4aed-9fe4-82293590d171.jpg)
![Screenshot_20221015-142112_Termux](https://user-images.githubusercontent.com/75281726/195983891-8796445e-7103-4c31-a51d-6d4207c3ed79.jpg)
![Screenshot_20221015-142143_Termux](https://user-images.githubusercontent.com/75281726/195983894-0230550d-f6b6-4ea2-a8bd-0bd6b32ffea2.jpg)
![Screenshot_20221015-142157_Termux](https://user-images.githubusercontent.com/75281726/195983903-64f83308-4d69-4517-9a34-d56c6d1a78ff.jpg)
![Screenshot_20221015-142207_Termux](https://user-images.githubusercontent.com/75281726/195983912-9ef6f545-8cbd-4d83-8c29-9c505931a420.jpg)

**Comment by dedshit** [comment]
@SeifStar which bundler version are you using right now

**Comment by dedshit** [comment]
@ha-ha-ha777  everything properly installed

**Comment by ha-ha-ha777** [comment]
> @ha-ha-ha777 все нормально установлено

zsh: command not found: msfconsole

**Comment by dedshit** [comment]
@ha-ha-ha777 in your case its symlink is problem coz its file already in bin dir

**Comment by ha-ha-ha777** [comment]
> @ha-ha-ha777в вашем случае его символическая ссылка является проблемой, потому что его файл уже находится в каталоге bin

В таком случае как запустить метасплоит? Я заходил в каталог бин и ошибка была такой же...

**Comment by dedshit** [comment]
> > @ha-ha-ha777 все нормально установлено
> 
> zsh: command not found: msfconsole

if you are confused then  try this `cd $PREFIX/opt/metasploit-framework; ./msfconsole`

**Comment by dedshit** [comment]
> > @ha-ha-ha777в вашем случае его символическая ссылка является проблемой, потому что его файл уже находится в каталоге bin
> 
> В таком случае как запустить метасплоит? Я заходил в каталог бин и ошибка была такой же...

please use English not native lang

**Comment by ha-ha-ha777** [comment]
> 

Этот ответ помог! Спасибо Вам большое)))))

**Comment by dedshit** [comment]
> > 
> 
> Этот ответ помог! Спасибо Вам большое)))))

if you dont want to run that everytime simply remove previous files related to metasploit in bin directory and create a symlink
