### ISSUE TITLE
Can't download squilite

### ISSUE THREAD

**Issue by Dstar001** [gushmazuko/metasploit_in_termux#203]
_checker)' has been deprecated. Please call DidYouMean.correct_error(error_name, spell_checker)' instead. Could not find sqlite3-1.4.2 in any of the sources Run bundle install` to install missing gems.

**Comment by dedshit** [comment]
@Dstar001 use gem command to install sqlite3

**Comment by lexdacs** [comment]
ive already done it but nothing happens

![Screenshot_2022-11-12-21-30-20-272_com.termux.jpg](https://user-images.githubusercontent.com/74500284/201476424-0ecc4869-2257-4df1-8eb4-8f78ca4a4830.jpg)

![Screenshot_2022-11-12-21-30-30-228_com.termux.jpg](https://user-images.githubusercontent.com/74500284/201476432-c385807a-4082-4e8f-bdec-a698f84cc9ea.jpg)

**Comment by lexdacs** [comment]
it says failed to build native extension. please help
