### ISSUE TITLE
[BUG] missing gems

### ISSUE THREAD

**Issue by StormTheXef** [gushmazuko/metasploit_in_termux#207]
there is a problem when installing and i tried 3 times and the termux is from f-droid.
![Screenshot_20221123-011947](https://user-images.githubusercontent.com/103287938/203441200-61cd89f7-bcb9-444c-b331-a79109c99d6f.png)
![Screenshot_20221123-011958](https://user-images.githubusercontent.com/103287938/203441218-736e2570-fd6d-4780-ad0f-7f6ead680584.png)

Smartphone:
 - Device: infinix hot 5
 - OS: Android 7
@gushmazuko

**Comment by dedshit** [comment]
run **bundler --version** @StormTheXef
