### ISSUE TITLE
Unable to open msfconsole

### ISSUE THREAD

**Issue by AryynRain** [gushmazuko/metasploit_in_termux#210]
msfconsole
No command msfconsole found, did you mean:
 Command bconsole in package bacula-fd
 Command jconsole in package openjdk-17

How do I solve this?

**Comment by dedshit** [comment]
> msfconsole No command msfconsole found, did you mean: Command bconsole in package bacula-fd Command jconsole in package openjdk-17
> 
> How do I solve this?

**Invalid**

**Comment by AryynRain** [comment]
what do you mean invalid?

**Comment by AryynRain** [comment]
what do you mean invalid?

**Comment by Babu-100** [comment]
Also have same problem

**Comment by dedshit** [comment]
> what do you mean invalid?

u didnt attach any screenshot/transcript.
