### ISSUE TITLE
Installer issue:

### ISSUE THREAD

**Issue by Mrquana** [gushmazuko/metasploit_in_termux#212]
Please update the installer it has lot of errors like this: /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.0.5/lib/concurrent/atomic/ But when I searched in file I found  concurrent-ruby-1.0.10 instead of 1.0.5. and many more errors too like it cannot find metasploit-framework folder $PREFIX/opt/metasploit-framework so I set it as  cd /data/data/com.termux/files/home/metasploit-framework.Please fix these and thank you for your support.

**Comment by Mohsenkhoshbahar** [comment]
Metasploit
