### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 1n73ct** [gushmazuko/metasploit_in_termux#213]
Failed to bind payload to original apk. I have updated to newest version of apktool.jar, but nothing happens.

I want to bind payload to original apk, but fail when rebuilding the apk. Solution pls.

![Screenshot_2022-12-23-09-47-55-40.jpg](https://user-images.githubusercontent.com/121133036/209261148-ed56d88a-9f1a-436b-8100-7cc5bebc3a42.jpg)

![Screenshot_2022-12-23-09-48-02-18.jpg](https://user-images.githubusercontent.com/121133036/209261171-e598b3d7-5189-46ca-9927-453a1eb524b9.jpg)

**Comment by dedshit** [comment]
do it manually
