### ISSUE TITLE
msfconsole not run,, please solve this issue

### ISSUE THREAD

**Issue by Hackerkdidjfikbfof** [gushmazuko/metasploit_in_termux#218]
Hello sir,,
msfconsole and msfvenom not run,,
Please solve this issue,,

**Comment by dedshit** [comment]
You didnt upload a single thing(screenshot/transcript), without that no can solution for that

**Comment by Hackerkdidjfikbfof** [comment]
> You didnt upload a single thing(screenshot/transcript), without that no can solution for that

Ok sir I send you a screenshot 
![Screenshot_2023-02-28-20-02-28-79_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/101497446/221876649-0a7f845c-e389-47c9-9d18-6b71c7a784fa.jpg)

**Comment by ScarletRodgers** [comment]
Try using ./msfconsole 
It works for me
