### ISSUE TITLE
[BUG] Error after using msfconsole

### ISSUE THREAD

**Issue by MixingSneaX** [gushmazuko/metasploit_in_termux#219]
![Screenshot_2023-01-01-05-43-45-73.jpg](https://user-images.githubusercontent.com/55280685/210161197-2b2f9542-f05d-40f1-b3c3-b8d258fd8c3b.jpg)

After I run `./msfconsole`, I get this message

**Comment by onesevenone7** [comment]
> ![Screenshot_2023-01-01-05-43-45-73.jpg](https://user-images.githubusercontent.com/55280685/210161197-2b2f9542-f05d-40f1-b3c3-b8d258fd8c3b.jpg)
> 
> After I run `./msfconsole`, I get this message
> 

o meu tambem deu isso

**Comment by onesevenone7** [comment]
O meu tambem deu isso

**Comment by dedshit** [comment]
@MixingSneaX  install pry 0.14.1

**Comment by onesevenone7** [comment]
> @MixingSneaX  install pry 0.14

paste?

**Comment by dedshit** [comment]
8

> > @MixingSneaX  install pry 0.14
> 
> paste?

what do u mean paste

**Comment by onesevenone7** [comment]
> @MixingSneaX  install pry 0.14.1

is to run this command?

**Comment by onesevenone7** [comment]
@dedshit

**Comment by dedshit** [comment]
`gem install pry -v 0.14.1`

**Comment by onesevenone7** [comment]
I ran the command, but it's still the same

**Comment by dedshit** [comment]
remove previous version `gem uninstall pry -v 0.13.1`

**Comment by onesevenone7** [comment]
> remove previous version `gem uninstall pry -v 0.13.1`

what is the command to remove?

**Comment by onesevenone7** [comment]
I ran the command, but it's still the same@dedshit

**Comment by onesevenone7** [comment]
> remove previous version `gem uninstall pry -v 0.13.1`

are giving it now Could not find pry-0.13.1 in locally installed gems
Run `bundle install` to install missing gems.

**Comment by onesevenone7** [comment]
> remove previous version `gem uninstall pry -v 0.13.1`

are giving it now

Could not find pry-0.13.1 in locally installed gems
Run `bundle install` to install missing gems.

**Comment by dedshit** [comment]
`gem list | grep pry` run this & send screenshot

**Comment by onesevenone7** [comment]
> `gem list | grep pry` run this & send screenshot

**Comment by onesevenone7** [comment]
> `gem list | grep pry` run this & send screenshot

![Screenshot_20230101-041610.png](https://user-images.githubusercontent.com/121332241/210163561-46f3d2ca-15c5-40c4-8256-957672d571e5.png)

![Screenshot_20230101-041616.png](https://user-images.githubusercontent.com/121332241/210163564-58b0c6fe-4af3-409b-a248-abdb573f80ca.png)

![Screenshot_20230101-041602.png](https://user-images.githubusercontent.com/121332241/210163567-e200e6ff-7f3c-43bb-b610-2cb098f4adcd.png)

**Comment by dedshit** [comment]
run msfconsole again

**Comment by onesevenone7** [comment]
> `gem list | grep pry` run this & send screenshot

![Screenshot_20230101-041815.png](https://user-images.githubusercontent.com/121332241/210163601-8adcab6c-4b44-49f0-a696-ff8d51dc0046.png)

**Comment by onesevenone7** [comment]
> run msfconsole again 

Could not find pry-0.13.1 in locally installed gems
Run `bundle install` to install missing gems.

**Comment by dedshit** [comment]
change pry version in gemfile.lock

**Comment by onesevenone7** [comment]
> change pry version in gemfile.lock

what commands do i use?

**Comment by onesevenone7** [comment]
> > change pry version in gemfile.lock
> 
> what commands do i use?

I just want to install metasploit.  It's the one thing I want most.

**Comment by dedshit** [comment]
`cd $PREFIX/opt/metasploit-framework; cat Gemfile.lock | grep pry -n`

**Comment by onesevenone7** [comment]
> `cd $PREFIX/opt/metasploit-framework; cat Gemfile.lock | grep pry -n`

![Screenshot_20230101-043723.png](https://user-images.githubusercontent.com/121332241/210163951-a920aa30-2a4b-41fc-b2d4-4417fa958acd.png)

**Comment by dedshit** [comment]
`sed -i '305, 310 s/0.13.1/0.14.1/' Gemfile.lock`

**Comment by onesevenone7** [comment]
> `sed -i '305, 310 s/0.13.1/0.14.1/' Gemfile.lock` 
It worked, thank you very much.  I was trying to install metasploit for days.  Thank you very much!

**Comment by dedshit** [comment]
> > `sed -i '305, 310 s/0.13.1/0.14.1/' Gemfile.lock`
> > It worked, thank you very much.  I was trying to install metasploit for days.  Thank you very much!

👍

**Comment by onesevenone7** [comment]
@dedshit can you help me?

**Comment by onesevenone7** [comment]
![Screenshot_20230102-013738.png](https://user-images.githubusercontent.com/121332241/210195532-6e615a75-4061-4400-be6c-37cb8f3a083e.png)


---> [-] Meterpreter session 1 is not valid and will be closed
[*] 192.168.0.70 - Meterpreter session 1 closed.

**Comment by dedshit** [comment]
try with localhost

**Comment by onesevenone7** [comment]
> try with localhost

like this?

**Comment by dedshit** [comment]
instead of 192.168.0.78 try localhost

**Comment by onesevenone7** [comment]
> instead of 192.168.0.78 try localhost

OK, got it.  I'm going to sleep now, as soon as I wake up, I'll do it, okay?

**Comment by onesevenone7** [comment]
> > instead of 192.168.0.78 try localhost
> 
> OK, got it.  I'm going to sleep now, as soon as I wake up, I'll do it, okay?
> 

I live in Brazil
