### ISSUE TITLE
[BUG] Error after using msfconsole

### ISSUE THREAD

**Issue by Mrquana** [gushmazuko/metasploit_in_termux#220]
msfconsole not working:
![Screenshot_20230103-195034.png](https://user-images.githubusercontent.com/83497873/210375725-b8acbc38-b2fb-4fb9-925c-b75d015679f9.png)
![Screenshot_20230103-195050.png](https://user-images.githubusercontent.com/83497873/210375754-7cd5a235-8178-454e-b66c-a0528830450f.png)
![Screenshot_20230103-195056.png](https://user-images.githubusercontent.com/83497873/210375764-50fc83b8-9c3e-4dcf-8514-43a22a2dfa0c.png)

**Comment by dedshit** [comment]
what's your ruby version ?

**Comment by Mrquana** [comment]
> what's your ruby version & run `termux-info`

![Screenshot_20230103-205623.png](https://user-images.githubusercontent.com/83497873/210387882-cd83624c-7634-4c3f-a87c-992f2ff909bf.png)

**Comment by dedshit** [comment]
[msf.zip](https://github.com/gushmazuko/metasploit_in_termux/files/10340938/msf.zip)

@Mrquana unzip, run the deb file & send me the feedback about that

**Comment by Mrquana** [comment]
> [msf.zip](https://github.com/gushmazuko/metasploit_in_termux/files/10340938/msf.zip)
> 
> @Mrquana unzip, run the deb file & send me the feedback about that

Nah bro not working 😔:
![Screenshot_20230104-111430.png](https://user-images.githubusercontent.com/83497873/210491910-d9d84091-f850-4034-ac72-85f6237ef82c.png)

**Comment by dedshit** [comment]
`gem install --no-document --quiet rubygems-update`

**Comment by Mrquana** [comment]
> `gem install --no-document --quiet rubygems-update` and try again

Nah bro not working pls help 😔:
![Screenshot_20230104-183312.png](https://user-images.githubusercontent.com/83497873/210561077-f5c7b65a-9f3c-4ee1-9da3-7cce073c68b0.png)

**Comment by dedshit** [comment]
[test.zip](https://github.com/gushmazuko/metasploit_in_termux/files/10344351/test.zip)

**Comment by Mrquana** [comment]
> [test.zip](https://github.com/gushmazuko/metasploit_in_termux/files/10344351/test.zip)
> 

Nah no good bro:
![Screenshot_20230105-143704.png](https://user-images.githubusercontent.com/83497873/210742570-95715193-b2dd-4660-99d3-f133ddbf32a6.png)

**Comment by dedshit** [comment]
just remove ruby, metasploit completely and install ruby ; send ss
