### ISSUE TITLE
msfconsole not found

### ISSUE THREAD

**Issue by f0xn1** [gushmazuko/metasploit_in_termux#221]
No command msfconsole found

![Screenshot_2023-01-04-15-35-58-164_com.termux.jpg](https://user-images.githubusercontent.com/56946783/210505861-af68e1a1-5d37-4ec0-864e-de8a137fe56d.jpg)

**Comment by dedshit** [comment]
looks like exited halfway thru . run `./msfconsole`

**Comment by f0xn1** [comment]
Do I have to go into the directory to run it? Please help me😭😭

**Comment by f0xn1** [comment]
Before I could just type msfconsole and run it

**Comment by dedshit** [comment]
> Do I have to go into the directory to run it? Please help mesobsob

you are already inside the metasploit dir

**Comment by dedshit** [comment]
> Before I could just type msfconsole and run it



> looks like exited halfway thru . run `./msfconsole` 

.

**Comment by f0xn1** [comment]
thank you
I was wondering if there was a way to run it in any directory

[Screenshot_2023-01-04-15-47-50-857_com.termux.jpg](https://user-images.githubusercontent.com/56946783/210507739-93be8361-4389-41fe-bda5-d7f3bf249588.jpg)

**Comment by dedshit** [comment]
> thank you I was wondering if there was a way to run it in any directory


`ln -s $HOME/metasploit-framework/msfvenom $PREFIX/bin/;
ln -s $HOME/metasploit-framework/msfconsole $PREFIX/bin/`

**Comment by f0xn1** [comment]
Thank you very much
I have a little problem
Please help me.😭😭
How to solve this problem

Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.

![Screenshot_2023-01-04-16-14-10-655_com.termux.jpg](https://user-images.githubusercontent.com/56946783/210512242-b603549e-7e76-48ed-9953-bc38ebf7de84.jpg)

**Comment by dedshit** [comment]
your bundler version ?

**Comment by f0xn1** [comment]
![Screenshot_2023-01-04-16-33-48-321_com.termux.jpg](https://user-images.githubusercontent.com/56946783/210514983-8f5d2b11-8a61-49d7-886d-8b05742d5a4a.jpg)

android11
termux 0.118

**Comment by dedshit** [comment]
`gem list -e bundler`

**Comment by f0xn1** [comment]
~ $ gem list -e bundler

*** LOCAL GEMS ***

bundler (2.4.2, default: 2.4.1, 2.1.4)

**Comment by f0xn1** [comment]
![Screenshot_2023-01-04-16-51-15-371_com.termux.jpg](https://user-images.githubusercontent.com/56946783/210517986-752c2725-ecce-426f-965a-ae39ae3ed349.jpg)

**Comment by dedshit** [comment]
`gem uninstall bundler -v '<2.4.1'`

**Comment by f0xn1** [comment]
thank you\^O^/

**Comment by Student-196** [comment]
![Screenshot_20230119-210338](https://user-images.githubusercontent.com/121730695/213524795-94eebc87-647b-45fa-9243-8f8dc9279162.jpeg)

**Comment by Student-196** [comment]
Bana da yardım edin lütfen
