### ISSUE TITLE
[BUG] please help

### ISSUE THREAD

**Issue by Sai46722** [gushmazuko/metasploit_in_termux#222]
**Im not able get the apk file into storage**

**As you can see in screenshot if i try to move androl.apk payload into metasploit_in_termux it is not showing the app**

![Screenshot_20230106-122949_Termux](https://user-images.githubusercontent.com/122080050/210948444-2e1f4e7f-6b2b-4e77-85cc-c0ca68916fc1.jpg)

Samsung a30s
Android 11

**Comment by dedshit** [comment]
i still dont get it; Are you trying to move that apk into your device storage ?

**Comment by Sai46722** [comment]
Yes

**Comment by dedshit** [comment]
are you new to linux ?

**Comment by Sai46722** [comment]
> are you new to linux ?

Yes

**Comment by dedshit** [comment]
this is not even an issue!. please close this

**Comment by Sai46722** [comment]
> this is not even an issue!. please close this

Please help me

**Comment by Sai46722** [comment]
How can i move it to device storage?

**Comment by Sai46722** [comment]
Please help me bro i really dont know what to do

**Comment by Student-196** [comment]
İlk önce aşağıdaki kodu yazarak APK dosyasını sil

rm -rf androl.apk

Şimdi ise bu linkin içerisindeki Trojan videolarını izle öğren oluşturan kişi Türk o yüzden türkçe ama senin için yeterlidir umarım ayrıca burda çok fazla video var burada çok şey öğrenirsin.

https://drive.google.com/file/d/14QI1Q3lBPZCYR4QFU0Hn06-M9L38fWIA/view
