### ISSUE TITLE
[undefined method `=~' for class `Pry::Code' (NameError)

### ISSUE THREAD

**Issue by Hrnvi-guru** [gushmazuko/metasploit_in_termux#223]
![Uploading Screenshot_20230105-170530_Termux.jpg…]()
When I'm trying to run metasploit it's showing this error 
Device = samsung galaxy m31
Android 12

**Comment by dedshit** [comment]
duplicate check #219 . problem is pry version


https://github.com/rapid7/metasploit-framework/pull/17447 
![Screenshot_20230107-071828_Via](https://user-images.githubusercontent.com/62318734/211125862-3b406b93-d9bd-411c-9899-f1ae5b4ecdec.png)

i already contacted him about this , he's responding too slow
