### ISSUE TITLE
[undefined method =~' for class Pry::Code' (NameError) 

### ISSUE THREAD

**Issue by ghost** [gushmazuko/metasploit_in_termux#224]
> @
![Uploading Screenshot_20230107-230430_Termux.jpg…]()
**Important**

Do not duplicate, search your issue before creating one!

**Describe the bug**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 8]
 - OS: [e.g. Android 10]

**Comment by dedshit** [comment]
duplicate! check #219
