### ISSUE TITLE
[BUG] please help

### ISSUE THREAD

**Issue by Imoneimone** [gushmazuko/metasploit_in_termux#226]
When i open 'msfconsole' after installing the proccess

This command out like this.

No command msfconsole found, did you mean:
 Command bconsole in package bacula-fd
 Command jconsole in package openjdk-17

![Screenshot_20230115-005953967](https://user-images.githubusercontent.com/122593277/212485532-678e7d52-5bbc-43cb-a5e7-cb872e406eac.jpg)
#
How to solve this?  Thanks for yourtime :')

**Comment by Imoneimone** [comment]
And after install.. I got this..
![Screenshot_20230115-032746047](https://user-images.githubusercontent.com/122593277/212492730-c72b9480-9194-4c67-857c-0d24889cd30b.jpg)

**Comment by dedshit** [comment]
run `termux-info`

**Comment by Imoneimone** [comment]
> run `termux-info`

This i got

![Uploading Screenshot_20230115-122233452.jpg…]()

**Comment by Imoneimone** [comment]
![Screenshot_20230115-122233452](https://user-images.githubusercontent.com/122593277/212522853-f73d22aa-7428-4109-8ec0-7b28ced89541.jpg)

**Comment by Imoneimone** [comment]
I've rooted device., is that take effect bcause i've rooted my device?

**Comment by dedshit** [comment]
remove ruby and metasploit completely in lib & opt respectively

**Comment by dedshit** [comment]
> I've rooted device., is that take effect bcause i've rooted my device?

no its not

**Comment by Imoneimone** [comment]
> remove ruby and metasploit completely in lib & opt respectively

What commands i use?

**Comment by Imoneimone** [comment]
Or from where i can delete that lib&opt?

**Comment by dedshit** [comment]
/data/data/com.termux/files/usr/lib/ruby 
/data/data/com.termux/files/usr/opt/metasploit-framework

**Comment by Imoneimone** [comment]
I have not opt folder. It just lib / ruby
![Uploading Screenshot_20230115-131010357.jpg…]()

**Comment by Imoneimone** [comment]
I have not opt in my location .
What should i do?
![Screenshot_20230115-131124290](https://user-images.githubusercontent.com/122593277/212524006-4bf717b9-1fd1-43a5-a153-de1a598aa1e2.jpg)

**Comment by Imoneimone** [comment]
![Screenshot_20230115-132404534](https://user-images.githubusercontent.com/122593277/212524304-c4537705-3430-407c-9b12-26f42bf251b7.jpg)

Like this?

**Comment by Imoneimone** [comment]
Here when i type ls
![Screenshot_20230115-132740976](https://user-images.githubusercontent.com/122593277/212524384-2aa62183-58f6-4d80-983e-384b74be59a1.jpg)

**Comment by Imoneimone** [comment]
But. 
When i run sh metasploit.sh i got this
![Uploading Screenshot_20230115-132909622.jpg…]()

**Comment by Imoneimone** [comment]
When i launch " sh metsploit.sh '
I got this
![Screenshot_20230115-132909622](https://user-images.githubusercontent.com/122593277/212524446-4bbfdfdc-120a-4042-ba85-0cbcb1f232fa.jpg)

**Comment by dedshit** [comment]
> ![Screenshot_20230115-132404534](https://user-images.githubusercontent.com/122593277/212524304-c4537705-3430-407c-9b12-26f42bf251b7.jpg)
> 
> Like this?
 

remove that too

**Comment by Imoneimone** [comment]
I have remove that.
What should i do next.?

**Comment by Imoneimone** [comment]
Still cant 
![Screenshot_20230115-134548393](https://user-images.githubusercontent.com/122593277/212524920-15b69408-b236-4f3d-922d-503e6e6595ea.jpg)

**Comment by dedshit** [comment]
apt install -y binutils python autoconf bison clang coreutils curl findutils apr apr-util postgresql openssl readline libffi libgmp libpcap libsqlite libgrpc libtool libxml2 libxslt ncurses make ncurses-utils ncurses git wget unzip zip tar termux-tools termux-elf-cleaner pkg-config git ruby
git clone https://github.com/rapid7/metasploit-framework.git --depth=1
cd metasploit-framework
gem install bundler
declare NOKOGIRI_VERSION=$(cat Gemfile.lock | grep -i nokogiri | sed 's/nokogiri [\(\)]/(/g' | cut -d ' ' -f 5 | grep -oP "(.).[[:digit:]][\w+]?[.].")
gem install nokogiri -v $NOKOGIRI_VERSION -- --use-system-libraries
bundle config build.nokogiri "--use-system-libraries --with-xml2-include=$PREFIX/include/libxml2"; bundle install
gem install actionpack
bundle update activesupport
bundle install -j$(nproc --all)
rm $PREFIX/bin/msfconsole; rm $PREFIX/bin/msfvenom
ln -s $PREFIX/opt/metasploit-framework/msfconsole $PREFIX/bin/
ln -s $PREFIX/opt/metasploit-framework/msfvenom $PREFIX/bin/

**Comment by Imoneimone** [comment]
Report issues at https://termux.dev/issues
~ $ apt install -y binutils python autoconf bison clang coreutils curl findutils apr apr-util postgresql openssl readline libffi libgmp libpcap libsqlite libgrpc libtool libxml2 libxslt ncurses make ncurses-utils ncurses git wget unzip zip tar termux-tools termux-elf-cleaner pkg-config git ruby
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
binutils is already the newest version (2.39-4).
python is already the newest version (3.11.1).
autoconf is already the newest version (2.71-2).
bison is already the newest version (3.8.2-3).
clang is already the newest version (15.0.7).
coreutils is already the newest version (9.1-2).
curl is already the newest version (7.87.0).
findutils is already the newest version (4.9.0-2).
apr is already the newest version (1.7.0-8).
apr-util is already the newest version (1.6.1-6).
postgresql is already the newest version (15.1-1).
openssl is already the newest version (1:3.0.7).
readline is already the newest version (8.2.1).
libffi is already the newest version (3.4.4).
libgmp is already the newest version (6.2.1-2).
libpcap is already the newest version (1.10.3).
libsqlite is already the newest version (3.40.1).
libgrpc is already the newest version (1.51.1).
libtool is already the newest version (2.4.7).
libxml2 is already the newest version (2.10.3).
libxslt is already the newest version (1.1.37).
ncurses is already the newest version (6.4-1).
make is already the newest version (4.4).
ncurses-utils is already the newest version (6.4-1).
git is already the newest version (2.39.0).
wget is already the newest version (1.21.3-5).
unzip is already the newest version (6.0-9).
zip is already the newest version (3.0-5).
tar is already the newest version (1.34-1).
termux-tools is already the newest version (1.36.0).
termux-elf-cleaner is already the newest version (2.1.1-2).
pkg-config is already the newest version (0.29.2-2).
ruby is already the newest version (3.2.0).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
~ $ git clone https://github.com/rapid7/metasploit-framework.git --depth=1
Cloning into 'metasploit-framework'...
remote: Enumerating objects: 14232, done.
remote: Counting objects: 100% (14232/14232), done.
remote: Compressing objects: 100% (12268/12268), done.
remote: Total 14232 (delta 1772), reused 6667 (delta 1167), pack-reused 0
Receiving objects: 100% (14232/14232), 59.68 MiB | 179.00 KiB/s, done.
Resolving deltas: 100% (1772/1772), done.
Updating files: 100% (12239/12239), done.
~ $ cd metasploit-framework
~/metasploit-framework $ gem install bundler
`RubyGems' were not loaded.
`error_highlight' was not loaded.
`did_you_mean' was not loaded.
`syntax_suggest' was not loaded.
/data/data/com.termux/files/usr/bin/gem:8:in `require': cannot load such file -- rubygems/gem_runner (LoadError)
        from /data/data/com.termux/files/usr/bin/gem:8:in `<main>'
~/metasploit-framework $ declare NOKOGIRI_VERSION=$(cat Gemfile.lock | grep -i nokogiri | sed 's/nokogiri [\(\)]/(/g' | cut -d ' ' -f 5 | grep -oP "(.).[[:digit:]][\w+]?[.].")
~/metasploit-framework $ gem install nokogiri -v $NOKOGIRI_VERSION -- --use-system-libraries
`RubyGems' were not loaded.
`error_highlight' was not loaded.
`did_you_mean' was not loaded.
`syntax_suggest' was not loaded.
/data/data/com.termux/files/usr/bin/gem:8:in `require': cannot load such file -- rubygems/gem_runner (LoadError)
        from /data/data/com.termux/files/usr/bin/gem:8:in `<main>'
~/metasploit-framework $ bundle config build.nokogiri "--use-system-libraries --with-xml2-include=$PREFIX/include/libxml2"; bundle install                                                      `RubyGems' were not loaded.                                     `error_highlight' was not loaded.
`did_you_mean' was not loaded.
`syntax_suggest' was not loaded.
/data/data/com.termux/files/usr/bin/bundle:9:in `require': cannot load such file -- rubygems (LoadError)
        from /data/data/com.termux/files/usr/bin/bundle:9:in `<main>'
`RubyGems' were not loaded.
`error_highlight' was not loaded.
`did_you_mean' was not loaded.
`syntax_suggest' was not loaded.
/data/data/com.termux/files/usr/bin/bundle:9:in `require': cannot load such file -- rubygems (LoadError)
        from /data/data/com.termux/files/usr/bin/bundle:9:in `<main>'
~/metasploit-framework $ gem install actionpack
`RubyGems' were not loaded.
`error_highlight' was not loaded.
`did_you_mean' was not loaded.
`syntax_suggest' was not loaded.
/data/data/com.termux/files/usr/bin/gem:8:in `require': cannot load such file -- rubygems/gem_runner (LoadError)
        from /data/data/com.termux/files/usr/bin/gem:8:in `<main>'
~/metasploit-framework $ bundle update activesupport
`RubyGems' were not loaded.
`error_highlight' was not loaded.
`did_you_mean' was not loaded.
`syntax_suggest' was not loaded.
/data/data/com.termux/files/usr/bin/bundle:9:in `require': cannot load such file -- rubygems (LoadError)
        from /data/data/com.termux/files/usr/bin/bundle:9:in `<main>'
~/metasploit-framework $ rm $PREFIX/bin/msfconsole; rm $PREFIX/bin/msfvenom
~/metasploit-framework $ ln -s metasploit-framework/msfconsole $PREFIX/bin/
~/metasploit-framework $ ln -s metasploit-framework/msfvenom $PREFIX/bin/

**Comment by Imoneimone** [comment]
Report issues at https://termux.dev/issues
~ $ apt install -y binutils python autoconf bison clang coreutils curl findutils apr apr-util postgresql openssl readline libffi libgmp libpcap libsqlite libgrpc libtool libxml2 libxslt ncurses make ncurses-utils ncurses git wget unzip zip tar termux-tools termux-elf-cleaner pkg-config git ruby
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
binutils is already the newest version (2.39-4).
python is already the newest version (3.11.1).
autoconf is already the newest version (2.71-2).
bison is already the newest version (3.8.2-3).
clang is already the newest version (15.0.7).
coreutils is already the newest version (9.1-2).
curl is already the newest version (7.87.0).
findutils is already the newest version (4.9.0-2).
apr is already the newest version (1.7.0-8).
apr-util is already the newest version (1.6.1-6).
postgresql is already the newest version (15.1-1).
openssl is already the newest version (1:3.0.7).
readline is already the newest version (8.2.1).
libffi is already the newest version (3.4.4).
libgmp is already the newest version (6.2.1-2).
libpcap is already the newest version (1.10.3).
libsqlite is already the newest version (3.40.1).
libgrpc is already the newest version (1.51.1).
libtool is already the newest version (2.4.7).
libxml2 is already the newest version (2.10.3).
libxslt is already the newest version (1.1.37).
ncurses is already the newest version (6.4-1).
make is already the newest version (4.4).
ncurses-utils is already the newest version (6.4-1).
git is already the newest version (2.39.0).
wget is already the newest version (1.21.3-5).
unzip is already the newest version (6.0-9).
zip is already the newest version (3.0-5).
tar is already the newest version (1.34-1).
termux-tools is already the newest version (1.36.0).
termux-elf-cleaner is already the newest version (2.1.1-2).
pkg-config is already the newest version (0.29.2-2).
ruby is already the newest version (3.2.0).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
~ $ git clone https://github.com/rapid7/metasploit-framework.git --depth=1
Cloning into 'metasploit-framework'...
remote: Enumerating objects: 14232, done.
remote: Counting objects: 100% (14232/14232), done.
remote: Compressing objects: 100% (12268/12268), done.
remote: Total 14232 (delta 1772), reused 6667 (delta 1167), pack-reused 0
Receiving objects: 100% (14232/14232), 59.68 MiB | 179.00 KiB/s, done.
Resolving deltas: 100% (1772/1772), done.
Updating files: 100% (12239/12239), done.
~ $ cd metasploit-framework
~/metasploit-framework $ gem install bundler
`RubyGems' were not loaded.
`error_highlight' was not loaded.
`did_you_mean' was not loaded.
`syntax_suggest' was not loaded.
/data/data/com.termux/files/usr/bin/gem:8:in `require': cannot load such file -- rubygems/gem_runner (LoadError)
        from /data/data/com.termux/files/usr/bin/gem:8:in `<main>'
~/metasploit-framework $ declare NOKOGIRI_VERSION=$(cat Gemfile.lock | grep -i nokogiri | sed 's/nokogiri [\(\)]/(/g' | cut -d ' ' -f 5 | grep -oP "(.).[[:digit:]][\w+]?[.].")
~/metasploit-framework $ gem install nokogiri -v $NOKOGIRI_VERSION -- --use-system-libraries
`RubyGems' were not loaded.
`error_highlight' was not loaded.
`did_you_mean' was not loaded.
`syntax_suggest' was not loaded.
/data/data/com.termux/files/usr/bin/gem:8:in `require': cannot load such file -- rubygems/gem_runner (LoadError)
        from /data/data/com.termux/files/usr/bin/gem:8:in `<main>'
~/metasploit-framework $ bundle config build.nokogiri "--use-system-libraries --with-xml2-include=$PREFIX/include/libxml2"; bundle install                                                      `RubyGems' were not loaded.                                     `error_highlight' was not loaded.
`did_you_mean' was not loaded.
`syntax_suggest' was not loaded.
/data/data/com.termux/files/usr/bin/bundle:9:in `require': cannot load such file -- rubygems (LoadError)
        from /data/data/com.termux/files/usr/bin/bundle:9:in `<main>'
`RubyGems' were not loaded.
`error_highlight' was not loaded.
`did_you_mean' was not loaded.
`syntax_suggest' was not loaded.
/data/data/com.termux/files/usr/bin/bundle:9:in `require': cannot load such file -- rubygems (LoadError)
        from /data/data/com.termux/files/usr/bin/bundle:9:in `<main>'
~/metasploit-framework $ gem install actionpack
`RubyGems' were not loaded.
`error_highlight' was not loaded.
`did_you_mean' was not loaded.
`syntax_suggest' was not loaded.
/data/data/com.termux/files/usr/bin/gem:8:in `require': cannot load such file -- rubygems/gem_runner (LoadError)
        from /data/data/com.termux/files/usr/bin/gem:8:in `<main>'
~/metasploit-framework $ bundle update activesupport
`RubyGems' were not loaded.
`error_highlight' was not loaded.
`did_you_mean' was not loaded.
`syntax_suggest' was not loaded.
/data/data/com.termux/files/usr/bin/bundle:9:in `require': cannot load such file -- rubygems (LoadError)
        from /data/data/com.termux/files/usr/bin/bundle:9:in `<main>'
~/metasploit-framework $ rm $PREFIX/bin/msfconsole; rm $PREFIX/bin/msfvenom
~/metasploit-framework $ ln -s metasploit-framework/msfconsole $PREFIX/bin/
~/metasploit-framework $ ln -s metasploit-framework/msfvenom $PREFIX/bin/

**Comment by Imoneimone** [comment]
I got this when type commands

![Screenshot_20230115-144616746.jpg](https://user-images.githubusercontent.com/122593277/212527021-5542c881-e517-419b-8ad1-c5400d934400.jpg)

**Comment by dedshit** [comment]
apt remove ruby

**Comment by dedshit** [comment]
> apt remove ruby

i told you to remove ruby completely ; you just removed that ruby from lib & didnt remove from bin

**Comment by dedshit** [comment]
>`apt install ruby`
> `gem install bundler`
> 
> `declare NOKOGIRI_VERSION=$(cat Gemfile.lock | grep -i nokogiri | sed 's/nokogiri [\(\)]/(/g' | cut -d ' ' -f 5 | grep -oP "(.).[[:digit:]][\w+]?[.].")`
> 
> `gem install nokogiri -v $NOKOGIRI_VERSION -- --use-system-libraries`
> 
> `bundle config build.nokogiri "--use-system-libraries --with-xml2-include=$PREFIX/include/libxml2"; bundle install`
> 
> `gem install actionpack`
> 
> `bundle update activesupport`
> 
> `bundle install -j$(nproc --all)`

run this part only

**Comment by Imoneimone** [comment]
![Screenshot_20230115-153516404.jpg](https://user-images.githubusercontent.com/122593277/212528642-4f360bd8-0b52-4081-9f5e-402d21850358.jpg)

I got this

**Comment by dedshit** [comment]
ln -s msfconsole $PREFIX/bin/

**Comment by Imoneimone** [comment]
Stil cant bro..

**Comment by Imoneimone** [comment]
Im sorry if bothering you,..
But i got this too...
![Screenshot_20230115-194505775](https://user-images.githubusercontent.com/122593277/212538747-ba5ff68a-f550-42f9-8789-93fdae0ab628.jpg)

**Comment by Imoneimone** [comment]
SOLVED THANKS... 
![Screenshot_20230115-200051621.jpg](https://user-images.githubusercontent.com/122593277/212539314-0a0c6342-4471-4b9f-93b3-61fbaf7474e2.jpg)

**Comment by SkyCreedPH** [comment]
> 

How to fix spell_checker?

**Comment by dedshit** [comment]
remove bundler version 2.1.4

**Comment by SkyCreedPH** [comment]
> remove bundler version 2.1.4

Thank you

**Comment by SkyCreedPH** [comment]
> remove bundler version 2.1.4

Bro can i get your discord?

**Comment by dedshit** [comment]
> Bro can i get your discord?

only telegram & whatsapp

**Comment by Saroj7377** [comment]
> remove bundler version 2.1.4

Thanks brother its working

**Comment by Hackno75** [comment]
> > Bro can i get your discord?
> 
> only telegram & whatsapp
Bro  it was showing like this an error occurred while installing nio4r (2.5.8), and bundler cannot continue help me out

**Comment by Kaenzy** [comment]
Idk but i type msfconsole its not working ._.
