### ISSUE TITLE
"msfconsole"  Hata

### ISSUE THREAD

**Issue by Student-196** [gushmazuko/metasploit_in_termux#228]
![Screenshot_20230119-210834](https://user-images.githubusercontent.com/121730695/213529162-be1f4744-9198-4cd6-a1b6-56b3e65f4b73.jpeg)

![Screenshot_20230119-210808](https://user-images.githubusercontent.com/121730695/213529194-ea815f3e-46d9-4cfa-9f9b-8c723b48591f.jpeg)

![Screenshot_20230119-210741](https://user-images.githubusercontent.com/121730695/213529241-fe319acb-b781-40c4-82c9-595f72ffbc52.jpeg)

İndirirken bu tür hatalar alıyorum indirdikten sonra bu tür hatalar alıyorum.

![Screenshot_20230119-210338](https://user-images.githubusercontent.com/121730695/213529625-5781b7d7-1739-439b-bf12-290e243061bb.jpeg)

Lütfen bana yardım edin internete yazan herşeyi denedim.

**Comment by dedshit** [comment]
English

**Comment by Student-196** [comment]
thank you I solved the problem but I want something from you You are among the metasploit faramework producers I have a suggestion you can add more functional commands like wepcam_stream or dump_sms in msfconsole it would be great thank you again

**Comment by ABD123758** [comment]
Same doubt plz reply
