### ISSUE TITLE
[BUG] error after install metasploit 

### ISSUE THREAD

**Issue by mahangar** [gushmazuko/metasploit_in_termux#229]
hi, I can not use metasploit.
![Screenshot_20230121_190845_Termux](https://user-images.githubusercontent.com/58225521/213874831-709e2f0e-00ac-4b65-a950-0dbb8798f4f9.jpg)
![Screenshot_20230121_190917_Termux](https://user-images.githubusercontent.com/58225521/213874835-a2013f70-7975-4f45-8d00-284c809588ae.jpg)

Android version: 13
termux: installed from termux's github page
installed kali nethunter and then installed metasploit in it.
termux version: 0.118.0

**Comment by dedshit** [comment]
![Screenshot_20230122-073057_Termux](https://user-images.githubusercontent.com/62318734/213897338-6fa65a81-0482-4612-8569-d68198477950.png)
