### ISSUE TITLE
Issues While Running Msfconsole

### ISSUE THREAD

**Issue by MunalAdhikari** [gushmazuko/metasploit_in_termux#23]
$ msfconsole
Could not find rake-13.0.3 in any of the sources
Run `bundle install` to install missing gems.
$
![Screenshot_2021-04-11-17-17-06-21_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/79589985/114302723-f990b580-9ae9-11eb-87ac-4cd7336803a3.jpg)

**Comment by gushmazuko** [comment]
[duplicate](https://github.com/gushmazuko/metasploit_in_termux/issues/21)
