### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by locozz21** [gushmazuko/metasploit_in_termux#230]
**Important**
Do not duplicate, search your issue before creating one!

**Describe the bug**
apk is not created. 

**Screenshots**
![Screenshot_20230209_011445_Termux](https://user-images.githubusercontent.com/82099358/217586832-b9a86b26-c5a1-4a2d-a59d-2e28195d4d0c.jpg)

**Smartphone (please complete the following information):**
 - Device: [samsung Z Filp 3]
 - OS: [Android 13]

**Comment by dedshit** [comment]
`termux-setup-storage`
