### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by ashrry** [gushmazuko/metasploit_in_termux#233]
**Describe the bug**
metasploit.sh: 20: Syntax error: "(" unexpected

**Screenshots**
![Screenshot_2023-02-20-19-09-45-847_com termux](https://user-images.githubusercontent.com/51499053/220124144-82cb1415-3f43-4611-94a7-fa57a8e8d12f.jpg)

**Smartphone
 - Device: [e.g. Redme 9 power]
 - OS: [e.g. Android 11]

**Comment by dedshit** [comment]
?
