### ISSUE TITLE
[ERROR] When I'm installing it gives these errors

### ISSUE THREAD

**Issue by NthlAnd** [gushmazuko/metasploit_in_termux#234]
1: ERROR: Installing pip is forbidden, this will break the python-pip package (termux)
2: Could not locate Gemfile
3: No command msfconsole found, did you mean:

I already installed several packages like wget, git, ruby, python, python2, blundle. I already gave update and upgrade but it doesn't work. It says installation complete but doesn't run the command and says "No command msfconsole found, did you mean:".

Device: My phone is Android a Samsung j6
Architecture CPU: armeabi-v7a
Architecture Kernel: armv8I
Android 10
![WhatsApp Image 2023-03-03 at 01 03 26 (1)](https://user-images.githubusercontent.com/126616601/222631962-9a1ad6ad-56b8-46e6-9a55-536c04fdb3ee.jpeg)
![WhatsApp Image 2023-03-03 at 01 03 26](https://user-images.githubusercontent.com/126616601/222631974-f8a8e75b-046d-4927-a8f9-48124727d07a.jpeg)

**Comment by dedshit** [comment]
did you try to install manually ?

**Comment by antnb** [comment]
Not only you, every new install using this script also failed
