### ISSUE TITLE
[BUGNo command msfconsole found, did you mean:  Command bconsole in package bacula-fd  Command jconsole in package openjdk-17 عملت كل الاجراءات بعد الانتهاء لم تعمل تطلع لي هذه الرساله]

### ISSUE THREAD

**Issue by Hamdeabbas** [gushmazuko/metasploit_in_termux#236]
No command msfconsole found, did you mean:
 Command bconsole in package bacula-fd
 Command jconsole in package openjdk-17
مالحل

**Comment by Anwer20222** [comment]
وانا يطلع لي نفس الشيء

**Comment by Anwer20222** [comment]
I've just carried all steps -step by step- literally even the installation is finished,  after that I entered (msfconsole command)  the next error is appeared 👇👇
($ mfsconsole
No command mfsconsole found, did you mean:
 Command bconsole in package bacula-fd
 Command jconsole in package openjdk-17
~ $) as you see .. not that my phone is up-to-date definitely Galaxy note 10 +..so can you assist me please..

**Comment by Iworry** [comment]
Did you got any fix im also having same problem😨😨
