### ISSUE TITLE
[BUG] PLEASE HELP ME 

### ISSUE THREAD

**Issue by Ghost2101-droid** [gushmazuko/metasploit_in_termux#237]
When i open 'msfconsole' after installing the proccess

This command out like this.

No command msfconsole found, did you mean:
Command bconsole in package bacula-fd
Command jconsole in package openjdk-17

![Screenshot_2023-03-29-22-49-01-350_com.termux.jpg](https://user-images.githubusercontent.com/79782818/228656433-b8965c5f-d900-4c7e-963d-3ef453424080.jpg)

**Comment by Ghost2101-droid** [comment]
@dedshit @gushmazuko

**Comment by dedshit** [comment]
wait for it

**Comment by dedshit** [comment]
try to remove **puma** and **nio4r** gem from Gemfile.lock
![Screenshot_20230330-085300_Termux](https://user-images.githubusercontent.com/62318734/228720852-db2499be-e6c9-4838-8f25-1b46f9c381cf.png)

**Comment by Ghost2101-droid** [comment]
Hi, please show me how to do it, I do not know how to do it 🥺

**Comment by Ghost2101-droid** [comment]
![Screenshot_2023-03-30-13-08-33-739_com.termux.jpg](https://user-images.githubusercontent.com/79782818/228803473-e434e1e8-a89f-434e-8d44-00b16aadef1f.jpg)

**Comment by dedshit** [comment]
nio4r and puma gem is problem

**Comment by dedshit** [comment]
`https://github.com/socketry/nio4r.git` clone this and goto that dir then run `rake compile` after successful compilation run `rake release`

**Comment by dedshit** [comment]
if you have done correctly you will be able to install puma gem then its simple
![Screenshot_20230330-161552_Termux](https://user-images.githubusercontent.com/62318734/228812965-7e764985-25e3-42cd-beeb-fe2dc66a9ff4.png)

**Comment by dedshit** [comment]
remove rake  and re install it 

for removing gem:
`gem uninstall rake` 

for installing gem:
`gem install rake`

**Comment by Ghost2101-droid** [comment]
![Screenshot_2023-03-30-14-18-11-007_com.termux.jpg](https://user-im![Screenshot_2023-03-30-14-18-00-224_com.termux.jpg](https://user-images.githubusercontent.com/79782818/228820002-2721eaf8-6e48-430d-aef8-a87dc8f52e6e.jpg)

e-af06422a1e1d.jpg)

![Uploading Screenshot_2023-03-30-14-18-00-224_com.termux.jpg …]()

**Comment by Ghost2101-droid** [comment]
![Screenshot_2023-03-30-14-18-00-224_com.termux.jpg](https://user-images.githubusercontent.com/79782818/228820067-7e6aa680-3b8c-433e-8554-778651edaf4b.jpg)

**Comment by Ghost2101-droid** [comment]
![Screenshot_2023-03-30-14-21-18-741_com.termux.jpg](https://user-images.githubusercontent.com/79782818/228820656-fe8d5bd8-baad-4a83-af4c-dc5e2de2bbef.jpg)

**Comment by dedshit** [comment]
did you see error **incompatible function pointer type** ?

**Comment by Ghost2101-droid** [comment]
I don't think so

**Comment by Ghost2101-droid** [comment]
![IMG_20230330_142825.jpg](https://user-images.githubusercontent.com/79782818/228822189-7738e3a0-3096-4170-bb01-5d12eb1124bd.jpg)

that's just

**Comment by dedshit** [comment]
yes thats the error

**Comment by Ghost2101-droid** [comment]
how do I fix this?

**Comment by dedshit** [comment]
open any editor like vim or nano or micro which is located in ext dir 

complete location : `/data/data/com.termux/files/home/nio4r/ext/nio4r/selector.c`

**Comment by Ghost2101-droid** [comment]
it doesn't work

**Comment by dedshit** [comment]
what to you mean by that, did u try open that selector.c usingbtext editor ?

**Comment by Ghost2101-droid** [comment]
Yes, it doesn't work

**Comment by dedshit** [comment]
send a screenshot

**Comment by Ghost2101-droid** [comment]
![Screenshot_2023-03-30-14-46-19-396_com.alphainventor.filemanager.jpg](https://user-images.githubusercontent.com/79782818/228826166-214e9fd8-a3ff-4ee0-b908-dc8726806f18.jpg)

**Comment by dedshit** [comment]
?

**Comment by Ghost2101-droid** [comment]
I don't have any folders

**Comment by dedshit** [comment]
text editor in termux itself!!!!  not other apk

**Comment by Ghost2101-droid** [comment]
Oh, I'm sorry

**Comment by Ghost2101-droid** [comment]
![Screenshot_2023-03-30-14-49-50-230_com.termux.jpg](https://user-images.githubusercontent.com/79782818/228827066-20632f14-981b-44ad-8fb0-eb0334e87af2.jpg)

**Comment by Ghost2101-droid** [comment]
![Screenshot_2023-03-30-14-53-44-300_com.termux.jpg](https://user-images.githubusercontent.com/79782818/228827922-7fedad7a-30dc-4714-90d6-81f493f67060.jpg)

**Comment by dedshit** [comment]
if you uncomfortable at what you are doing then just run this

`sed -i '301 s/func/\&func/' /data/data/com.termux/files/home/nio4r/ext/nio4r/selector.c`

**Comment by Ghost2101-droid** [comment]
![Screenshot_2023-03-30-14-58-34-595_com.termux.jpg](https://user-images.githubusercontent.com/79782818/228828983-de6763c5-f8f7-4324-b627-9050865b7a45.jpg)

**Comment by Ghost2101-droid** [comment]
![Screenshot_2023-03-30-15-04-42-544_com.termux.jpg](https://user-images.githubusercontent.com/79782818/228830283-f33cf6a3-3c65-4c3a-b7e6-5adfc1f4b6c9.jpg)

**Comment by Ghost2101-droid** [comment]
Everything's fine, there doesn't seem to be a single mistake, what's next?

**Comment by dedshit** [comment]
i told you to paste the command

**Comment by dedshit** [comment]
> > `sed -i '301 s/func/\&func/' /data/data/com.termux/files/home/nio4r/ext/nio4r/selector.c`
> 
> just run this

?

**Comment by Ghost2101-droid** [comment]
Yes

**Comment by dedshit** [comment]
> after that goto that nio4r dir and type `rake clean` and `rake compile`

do this and send screenshot

**Comment by Ghost2101-droid** [comment]
![Screenshot_2023-03-30-15-12-56-144_com.termux.jpg](https://user-images.githubusercontent.com/79782818/228832334-44002744-d098-4e1a-9ac7-d83046f3ded6.jpg)

**Comment by Ghost2101-droid** [comment]
![Screenshot_2023-03-30-15-13-21-729_com.termux.jpg](https://user-images.githubusercontent.com/79782818/228832376-a4917e24-8a96-4b64-9e83-907f969d5a34.jpg)

**Comment by dedshit** [comment]
thats it

**Comment by dedshit** [comment]
now run `rake release`

**Comment by Ghost2101-droid** [comment]
![Screenshot_2023-03-30-15-16-46-738_com.termux.jpg](https://user-images.githubusercontent.com/79782818/228833114-7336e2c6-2d12-454b-8928-02857128f5c3.jpg)

**Comment by dedshit** [comment]
goto pkg dir and  run `gem i nio4r-2.5.8.gem`

**Comment by dedshit** [comment]
installed ?

**Comment by Ghost2101-droid** [comment]
![Screenshot_2023-03-30-15-26-12-312_com.termux.jpg](https://user-images.githubusercontent.com/79782818/228835363-73fd4af2-4a72-4a59-bb2c-1687800d5f13.jpg)

**Comment by dedshit** [comment]
i didnt see any error

**Comment by dedshit** [comment]
just run this `cd pkg && gem i nio4r-2.5.8.gem`

**Comment by dedshit** [comment]
goto metasploit-framework and type `bundle install` thats it

**Comment by Ghost2101-droid** [comment]
how do I log in to the directory metasploit?

**Comment by dedshit** [comment]
`cd $PREFIX/opt/metasploit-framework/ && bundle install`

**Comment by dedshit** [comment]
screenshot

**Comment by dedshit** [comment]
> Thank you very much, thank you

share the screenshot

**Comment by SkyCreedPH** [comment]
Omg thanks

**Comment by Saroj7377** [comment]
Bro I can't understand bro please help me step by step 🥺🥺🥺

**Comment by Saroj7377** [comment]
> Omg thanks

Bro I can't understand please describe step by step 🥺🥺🥺 please,

**Comment by Saroj7377** [comment]
> just run this `cd pkg && gem i nio4r-2.5.8.gem`

Bro please describe step by step 🥺🥺🥺 please

**Comment by dedshit** [comment]
> > just run this `cd pkg && gem i nio4r-2.5.8.gem`
> 
> Bro please describe step by step pleading_facepleading_facepleading_face please

Did you ask your issue in metasploit-framework ?

**Comment by dedshit** [comment]
> Bro I can't understand please describe step by step pleading_facepleading_facepleading_face please,

sorry i wont repeat that again see the above chats  and do it yourself

**Comment by Saroj7377** [comment]
Just tell me where to paste this comand
sed -i '301 s/func/\&func/' /data/data/com.termux/files/home/nio4r/ext/nio4r/selector.c

**Comment by sidhant387474** [comment]
Bro I couldn't find my pkg directory then where do it ?? And rake compile and rake realse also not working plz solve my error

**Comment by sidhant387474** [comment]
just run this `cd pkg && gem i nio4r-2.5.8.gem`

It's not run not showing any error and not done it !! Only show it's run how to solve this ??

**Comment by dedshit** [comment]
> just run this `cd pkg && gem i nio4r-2.5.8.gem`
> 
> It's not run not showing any error and not done it !! Only show it's run how to solve this ??

?

**Comment by NX2** [comment]
![Uploading Screenshot_2023-04-07-10-24-04-58_84d3000e3f4017145260f7618db1d683.jpg…]()

**Comment by NX2** [comment]
![Uploading Screenshot_2023-04-07-10-24-04-58_84d3000e3f4017145260f7618db1d683.jpg…]()

**Comment by NX2** [comment]
After uninstalling rake and re install it still rake compile command doesn't work

**Comment by NX2** [comment]
> After uninstalling rake and re install it still rake compile command doesn't work

![Uploading Screenshot_2023-04-07-10-28-22-77_84d3000e3f4017145260f7618db1d683.jpg…]()

**Comment by SikoRDX** [comment]
> > `sed -i '301 s/func/\&func/' /data/data/com.termux/files/home/nio4r/ext/nio4r/selector.c`
> 
> juts run it 

it doesn't work  i have error 

```
~/nio4r $
~/nio4r $ rake clean                                    
rake aborted!                                          
 LoadError: cannot load such file -- rake/extensiontask
<internal:/data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in require'
<internal:/data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in require'
/data/data/com.termux/files/home/nio4r/rakelib/extension.rake:10:in `<top (required)>'                          (See full trace by running task with --trace)

```

**Comment by Rishi9646** [comment]
Bro , Please help me

**Comment by idipospi** [comment]
Hello, try to download the needed version of nio4r (2.5.8) https://github.com/socketry/nio4r/tree/v2.5.8 
Then export it to Termux, unzip, enter in filder nio4r.
'ls' command show you files in folder, you are need file nio4r.gemspec
Then type command: gem build nio4r.gemspec
After that you can find in folder file nio4r-2.5.8.gem
Then type command: gem install nio4r-2.5.8.gem
Gem could be successfuly installed

**Comment by hacker369** [comment]
slove it
(https://github.com/gushmazuko/metasploit_in_termux/issues/252#issuecomment-1609048327)

**Comment by gushmazuko** [comment]
Fixed in latest update https://github.com/gushmazuko/metasploit_in_termux/commit/47ea57e9912814e689f5b3446416c5ae65d7160c
Just update your Termux and reinstall:
```bash
source <(curl -fsSL https://kutt.it/msf)
```

**Comment by Badr164** [comment]
![Screenshot_2024-06-26-23-39-00-811_com termux](https://github.com/gushmazuko/metasploit_in_termux/assets/173958887/376863fe-ca33-4d47-a7f4-9ff519b5c84e)
![Uploading Screenshot_2024-06-26-23-39-00-811_com.termux.jpg…]()

**Comment by Badr164** [comment]
![Screenshot_2024-06-26-23-56-50-676_com termux](https://github.com/gushmazuko/metasploit_in_termux/assets/173958887/d2aa33bc-cf46-404d-a461-4091be0e751f)

**Comment by daytripalexxx** [comment]
10/4
