### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by robert873to** [gushmazuko/metasploit_in_termux#238]
i need to learn metasploit framework .any can help me to solve this issue. So please help me

**Describe the bug**
i installed succesively but cant to excute msfconsole

**Screenshots**
termux emulator 0.118.0.
![Screenshot_20230330-005350.png](https://user-images.githubusercontent.com/82003695/228677035-3c132946-4293-4bf1-9ac7-810125a79c8a.png)

**Smartphone (please complete the following information):**
 - Device: [ ifinix hot 8]
 - OS: [Android 9]

**Comment by dedshit** [comment]
I already mentioned [This](https://github.com/gushmazuko/metasploit_in_termux/issues/226#issuecomment-1383064793)

**Comment by dedshit** [comment]
![Screenshot_20230330-085300_Termux](https://user-images.githubusercontent.com/62318734/228720586-e95bc010-8fd9-4a05-bd44-22657ac55786.png)
