### ISSUE TITLE
[BUG] PLEASE HELP 

### ISSUE THREAD

**Issue by Ghost2101-droid** [gushmazuko/metasploit_in_termux#241]
I can't create an apk file

![Screenshot_2023-03-30-17-47-51-245_com.termux.jpg](https://user-images.githubusercontent.com/79782818/228875791-029c6ad8-9357-4d18-a2a6-5b56c7a3448e.jpg)

@gushmazuko @dedshit

**Comment by dedshit** [comment]
?

**Comment by Ghost2101-droid** [comment]
I can't create an apk file

**Comment by Ghost2101-droid** [comment]
nothing happens, just endless loading

**Comment by dedshit** [comment]
try to run  that in new session
