### ISSUE TITLE
Content leeching and promoting spam

### ISSUE THREAD

**Issue by dedshit** [gushmazuko/metasploit_in_termux#248]
# Things that i have posted is copied by many newbies especially those who promotes their content in social media's, so i have decided not to patch upcoming issue. Goodluck everyone.

**Comment by Saroj7377** [comment]
Sorry brother i dont want to pronot my youtube channel.i just try to help other .i won't make this mistake next time.You tell me what should I do to forgive my mistake.

**Comment by Saroj7377** [comment]
> # Things that i have posted is copied by many newbies especially those who promotes their content in social media's, so i have decided not to patch upcoming issue. Goodluck everyone.

Brother ihave deleted this video from youtube.i dont use internet soo much.so i dosent see your frst coment.aggain i am verry verry soory for hurt you.

**Comment by Saroj7377** [comment]
> # Things that i have posted is copied by many newbies especially those who promotes their content in social media's, so i have decided not to patch upcoming issue. Goodluck everyone

I feel soo much gilty.....

**Comment by SikoRDX** [comment]
> > # Things that i have posted is copied by many newbies especially those who promotes their content in social media's, so i have decided not to patch upcoming issue. Goodluck everyone
> 
> I feel soo much gilty.....

**Now how are we going to correct mistakes without him? **
