### ISSUE TITLE
[BUG] Error  rake compile, reak release , and Error install nio4r-2.5.8 

### ISSUE THREAD

**Issue by SikoRDX** [gushmazuko/metasploit_in_termux#249]
**Errro** Help please @dedshit 

### rake compile , rake release , nio4r-2.5.8 , rake clean 

![image](https://user-images.githubusercontent.com/102025590/230707604-e8617229-c125-468b-925c-679e2d537812.png)
![image](https://user-images.githubusercontent.com/102025590/230707608-3cf19c09-ce6d-46b6-8363-87342018e1b2.png)
![image](https://user-images.githubusercontent.com/102025590/230707640-ef7a43cd-5d37-4492-81fb-a0d34361df0e.png)

**Comment by Cool1l** [comment]
Just make this changes in sh file it will be solvef
![Uploading Screenshot_20230409_152635.jpg…]()

**Comment by SikoRDX** [comment]
> Just make this changes in sh file it will be solved and close the issue
> 
> ![Screenshot_20230409_152635](https://user-images.githubusercontent.com/94423611/230766431-c5450622-2253-48d7-9b66-c902a73e35ce.jpg)

I didn't understand exactly what code to write 

Therefore, I wrote everything separately to the console 

But it didn't work, still getting this error.

**Comment by Cool1l** [comment]
> > Just make this changes in sh file it will be solved and close the issue
> > ![Screenshot_20230409_152635](https://user-images.githubusercontent.com/94423611/230766431-c5450622-2253-48d7-9b66-c902a73e35ce.jpg)
> 
> I didn't understand exactly what code to write
> 
> Therefore, I wrote everything separately to the console
> 
> But it didn't work, 

> > Just make this changes in sh file it will be solved and close the issue
> > ![Screenshot_20230409_152635](https://user-images.githubusercontent.com/94423611/230766431-c5450622-2253-48d7-9b66-c902a73e35ce.jpg)
> 
> I didn't understand exactly what code to write
> 
> Therefore, I wrote everything separately to the console
> 
> But it didn't work, still getting this error.
https://youtu.be/MLHOBuH-mhE
watch this

**Comment by SikoRDX** [comment]
> 
![image](https://user-images.githubusercontent.com/102025590/230786681-37ed1a94-cba4-4fc4-bcdb-6f35bec6e981.png)
I can't go to file or copy can you help me ?

**Comment by SikoRDX** [comment]
@Cool1l  pls

**Comment by SikoRDX** [comment]
Thanky very much bro i solved it 😘

**Comment by SikoRDX** [comment]
If you don’t succeed, just repeat exactly as in the video and you will succeed, you just need to wait until the end .
