### ISSUE TITLE
Showing Could not find nio4r-2.5.8 in any of the source

### ISSUE THREAD

**Issue by Hackno75** [gushmazuko/metasploit_in_termux#250]
Could not find nio4r-2.5.8 in any of the sources
Run `bundle install` to install missing gems.

**Comment by Cool1l** [comment]
> Could not find nio4r-2.5.8 in any of the sources Run `bundle install` to install missing gems.

https://youtu.be/MLHOBuH-mhE
All error fixed by me then cloae the issue

**Comment by Cool1l** [comment]
https://youtu.be/MLHOBuH-mhE
All error fixed by me after successful completion close the issue

**Comment by dedshit** [comment]
@Cool1l  can you explain what have you done to fix all errors ?

**Comment by Cool1l** [comment]
> @Cool1l can you explain what have you done to fix all errors ?

bro I made some changes in your shell script
first I changed nio4r 2.5.8 to nio4r in Gemfile.lock
and changed actionview to 7th version

**Comment by Cool1l** [comment]
![Screenshot_20230409_152635](https://user-images.githubusercontent.com/94423611/230895768-c2be5ad8-b6b6-41dd-ac75-cb847c500d88.jpg)
bro I made some changes in your shell script
first I changed nio4r 2.5.8 to nio4r 2.5.9 in Gemfile.lock
and changed actionview to 7th version

**Comment by Dagim0** [comment]
Bro can you tell me How you did it
