### ISSUE TITLE
Please help me. I found this problem . I am new[BUG]

### ISSUE THREAD

**Issue by Forhad-449** [gushmazuko/metasploit_in_termux#252]
Could not locate Gemfile
Could not locate Gemfile
Could not locate Gemfile

Msfconsol not working
Please help

![Screenshot_20230420-095530](https://user-images.githubusercontent.com/113767522/233255307-7e3c0f6b-9808-4c4c-b7f4-088fa1abc75c.png)
![Screenshot_20230420-095509](https://user-images.githubusercontent.com/113767522/233255321-d6bb2cb4-87bf-4a1a-a4cf-f5e83082fbf1.png)

![Screenshot_20230420-095523](https://user-images.githubusercontent.com/113767522/233255316-0134b152-32c1-4d68-9920-587e9f120555.png)

**Comment by vovmomyt** [comment]
cd metasploit-framework
./msfconsole

**Comment by Forhad-449** [comment]
> `cd metasploit-framework ./msfconsole`

![Screenshot_20230530-161733](https://github.com/gushmazuko/metasploit_in_termux/assets/113767522/c1c17ecb-0e2a-46d9-9d5e-c1c96d08f964)
![Screenshot_20230530-161728](https://github.com/gushmazuko/metasploit_in_termux/assets/113767522/73049ffb-57d1-40ec-8ab5-ff195d7036f6)

**Comment by hacker369** [comment]
bro, like to your problem, but I fixed it.
cd metasploit-framework/
./msfconsole
then you will get problem,but the error words in yellow can fix it,
Copy and run 'bundle install --gemfile .....'
Wait to slove,
and run ./msfconsole, will may get problem again, same step ,run 'bundle....'
Exit your termux,and open it
Cd metasploit-framework/
./msfconsole

**Comment by vivircruz** [comment]
> mano, gosto do seu problema, mas eu corrigi. cd metasploit-framework/ ./msfconsole então você vai ter problema, mas as palavras de erro em amarelo pode corrigi-lo, Copie e execute 'bundle install --gemfile .....' Espere para slove, e execute ./msfconsole, pode ter problema novamente, mesmo passo, execute 'bundle....' Saia do seu termux e abra-o Cd metasploit-framework/ ./msfconsole

Perfect, it´s working now! Tks

**Comment by gushmazuko** [comment]
Fixed in latest update https://github.com/gushmazuko/metasploit_in_termux/commit/47ea57e9912814e689f5b3446416c5ae65d7160c
Just update your Termux and reinstall:
```bash
source <(curl -fsSL https://kutt.it/msf)
```
