### ISSUE TITLE
Could not locate gemfile[BUG]

### ISSUE THREAD

**Issue by TanjiroK** [gushmazuko/metasploit_in_termux#256]
I tried all ways of solving this but failed any solution??

Smartphone 
 - Device: [Karbonn X21]
 - OS: [Android 10]
![Screenshot_20230924-193636](https://github.com/gushmazuko/metasploit_in_termux/assets/86595133/9550141f-60fb-46ef-86a5-268fb5245f58)

**Comment by Smartpluginc** [comment]
Yea I'm having the same issue

**Comment by Heda360** [comment]
Me too

**Comment by gushmazuko** [comment]
Fixed in latest update https://github.com/gushmazuko/metasploit_in_termux/commit/47ea57e9912814e689f5b3446416c5ae65d7160c
Just update your Termux and reinstall:
```bash
source <(curl -fsSL https://kutt.it/msf)
```

**Comment by Karthi02116K** [comment]
Creat gem file with nano in home derectory

nano gemfile
 

Now pate this


# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"



Now save and exit


Now

bundler install --gemfile
