### ISSUE TITLE
[BUG]No command msfconsole found, did you mean:  Command bconsole in package bacula-fd  Command jconsole in package openjdk-17

### ISSUE THREAD

**Issue by ProstoArte** [gushmazuko/metasploit_in_termux#257]
Привет, у меня проблема с запуском метасллита 
В чём заключается проблема при попытке запуска метасллита вылетает вот такой текст 
No command msfconsole found, did you mean:
 Command bconsole in package bacula-fd
 Command jconsole in package openjdk-17
Я не знаю как решить делал как написано в статье
Скачал термукс с F-droid 
![Screenshot_20231019-194757_Termux](https://github.com/gushmazuko/metasploit_in_termux/assets/90385400/b4a7bae9-62e8-4a9c-ba84-e28e083dc2d1)

Телефон:Samsung galaxy a50
Android:11
На скриншоте видно подробно проблему

**Comment by vovmomyt** [comment]
Привет! Я исправил эту ошибку в своём форке https://github.com/vovmomyt/metasploit_in_termux/

**Comment by gushmazuko** [comment]
Fixed in latest update https://github.com/gushmazuko/metasploit_in_termux/commit/47ea57e9912814e689f5b3446416c5ae65d7160c

**Comment by CubyInsane** [comment]
Same issue showing Again
