### ISSUE TITLE
MSG console not started 

### ISSUE THREAD

**Issue by 1bharath-yadav** [gushmazuko/metasploit_in_termux#269]
msfconsole         Metasploit tip: The use command supports fuzzy searching to try and                                 select the intended module, e.g. use kerberos/get_ticket or use                                     kerberos forge silver ticket                      /data/data/com.termux/files/usr/opt/metasploit-framework/lib/net/dns/resolver.rb:1087:in `foreach': No such file or directory @ rb_sysopen - /etc/resolv.conf (Errno::ENOENT)                                   from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/net/dns/resolver.rb:1087:in `parse_config_file'                                     from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/rex/proto/dns/resolver.rb:66:in `initialize'                                        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/rex/proto/dns/cached_resolver.rb:25:in `initialize'                                 from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/ui/console/driver.rb:83:in `new'                                                from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/ui/console/driver.rb:83:in `initialize'                                         from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `new'                                 from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `driver'                              from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'                               from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'                                  from /data/data/com.termux/files/usr/bin/msfconsole:23:in `<main>'

**Comment by dedshit** [comment]
@1bharath-yadav https://github.com/gushmazuko/metasploit_in_termux/issues/260#issuecomment-1888617189

**Comment by 1bharath-yadav** [comment]
Closed 260
