### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 1bharath-yadav** [gushmazuko/metasploit_in_termux#270]
Metasploit tip: Use the analyze command to suggest runnable modules for
hosts
/data/data/com.termux/files/usr/opt/metasploit-framework/lib/rex/proto/dns/resolver.rb:14:in `<module:DNS>': uninitialized constant Net::DNS (NameError)
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/rex/proto/dns/resolver.rb:8:in `<module:Proto>'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/rex/proto/dns/resolver.rb:7:in `<module:Rex>'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/rex/proto/dns/resolver.rb:6:in `<top (required)>'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:30:in `require'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/rex/proto/dns/cached_resolver.rb:13:in `<module:DNS>'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/rex/proto/dns/cached_resolver.rb:7:in `<module:Proto>'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/rex/proto/dns/cached_resolver.rb:6:in `<module:Rex>'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/rex/proto/dns/cached_resolver.rb:5:in `<top (required)>'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:30:in `require'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/ui/console/driver.rb:83:in `initialize'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `new'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `driver'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
        from /data/data/com.termux/files/usr/bin/msfconsole:23:in `<main>'

**Comment by 1bharath-yadav** [comment]
Wait I reinstalling

**Comment by dedshit** [comment]
> Wait I reinstalling

for what ?

**Comment by 1bharath-yadav** [comment]
Msf console new curl link

**Comment by 1bharath-yadav** [comment]
source <(curl -fsSL https://kutt.it/msf)

In metasploit folder    =   sed -i '0,/\"\/etc\/resolv.conf\"/s//\"\/data\/data\/com.termux\/files\/usr\/etc\/resolv.conf\"/' $(find . -name 'resolver.rb')


Solved

**Comment by 1bharath-yadav** [comment]
Solved

**Comment by dedshit** [comment]
ok

**Comment by dedshit** [comment]
> source <(curl -fsSL https://kutt.it/msf)
> 
> In metasploit folder = sed -i '0,/"/etc/resolv.conf"/s//"/data/data/com.termux/files/usr/etc/resolv.conf"/' $(find . -name 'resolver.rb')
> 
> Solved

without escaping slash it wont work 

also is this answer for me or someone else ?

**Comment by 1bharath-yadav** [comment]
Thanks anyway

**Comment by dedshit** [comment]
no prob :)
