### ISSUE TITLE
Hi, Issue On Opening MsfConsole.

### ISSUE THREAD

**Issue by UPMMASTER** [gushmazuko/metasploit_in_termux#271]
Hi, I recently installed Metasploit on Termux, but after the installation finished, while running the ./msfconsole command I Got An Error.
![Screenshot_2024-01-26-19-01-33-312_com termux](https://github.com/gushmazuko/metasploit_in_termux/assets/98464731/6210f3c4-8681-48a3-9704-88466afd2aa9)
Thank you for helping me.
Smart Phone:
Xiaomi 11T
Root:Unlocked 
Enough Storage(79GB Remaining)
Miui 14

**Comment by dedshit** [comment]
@UPMMASTER [#260 (duplicate)](https://github.com/gushmazuko/metasploit_in_termux/issues/260#issuecomment-1888617189)

**Comment by UPMMASTER** [comment]
> @UPMMASTER [#260 (duplicate)](https://github.com/gushmazuko/metasploit_in_termux/issues/260#issuecomment-1888617189)

but how to use this command $PREFIX/opt/metasploit-framework 
??
i used and it says : "I a directory"
.
then i cant use this command 
sed -i '0,/\"\/etc\/resolv.conf\"/s//\"\/data\/data\/com.termux\/files\/usr\/etc\/resolv.conf\"/' $(find . -name 'resolver.rb') 
because of error "no input files"
i should run $PREFIX/opt/metasploit-framework but i dont know how and where to run.
Can You Help Me?
Sorry to bother you.

**Comment by Rkcoder0425** [comment]
[*] Starting the MetasPloit Framework consol/data/data/com.termux/files/usr/opt/metasploit-framework/lib/net/dns/resolver.rb:1087:in `foreach': No such file or directory @ rb_sysopen - /etc/resolv.conf (Errno::ENOENT)
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/net/dns/resolver.rb:1087:in `parse_config_file'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/rex/proto/dns/resolver.rb:66:in `initialize'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/rex/proto/dns/cached_resolver.rb:25:in `initialize'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/ui/console/driver.rb:83:in `new'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/ui/console/driver.rb:83:in `initialize'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `new'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `driver'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
        from 
/data/data/com.termux/files/usr/bin/msfconsole:23:in `<main>'



How to solve this
![Uploading Screenshot_20240127-065054.png…]()

**Comment by UPMMASTER** [comment]
#260 
go with this

**Comment by UPMMASTER** [comment]
![Uploading Screenshot_2024-01-27-06-09-01-287_com.termux.jpg…]()
> @UPMMASTER [#260 (duplicate)](https://github.com/gushmazuko/metasploit_in_termux/issues/260#issuecomment-1888617189)

Thank you so much it worked.
![Screenshot_2024-01-27-06-08-38-504_com termux](https://github.com/gushmazuko/metasploit_in_termux/assets/98464731/d2498270-4c24-474e-8646-7871d75ff712)

**Comment by UPMMASTER** [comment]
@Rkcoder0425 Let me tell you how.
thank to dev, i got some knowledge, type these in termux.
cd /data/data/com.termux/files/usr/opt/metasploit-framework
and this 
sed -i '0,/\"\/etc\/resolv.conf\"/s//\"\/data\/data\/com.termux\/files\/usr\/etc\/resolv.conf\"/' $(find . -name 'resolver.rb')

**Comment by Rkcoder0425** [comment]
![Screenshot_20240127-095657](https://github.com/gushmazuko/metasploit_in_termux/assets/150472171/a33e0a4b-1d38-4632-8f5a-c4c701095a5e)
Not working brooo

**Comment by dedshit** [comment]
> ![Screenshot_20240127-095657](https://private-user-images.githubusercontent.com/150472171/300155550-a33e0a4b-1d38-4632-8f5a-c4c701095a5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMzY0MjEsIm5iZiI6MTcwNjMzNjEyMSwicGF0aCI6Ii8xNTA0NzIxNzEvMzAwMTU1NTUwLWEzM2UwYTRiLTFkMzgtNDYzMi04ZjVhLWM0YzcwMTA5NWE1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QwNjE1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODVlYzMxYTA1YjFjZjU4YWQwZmJiZWNiNGViNGUxZTBiOTc4ZjkzNWJlMGQ4YmNmNGI5Njk0OGNjNWU1MTdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vikBkIy9j7a3h0_nAarE1a1rIf0rT6a67sqi9Hd1N3s) Not working brooo


you just paste that with escaping slashes
