### ISSUE TITLE
Msfconsole

### ISSUE THREAD

**Issue by aveen001** [gushmazuko/metasploit_in_termux#3]
Segmentation faultetasploit FRamework console.../
Please anyone help me..😖

**Comment by pple7000** [comment]
I suggest you not run it on termux.
Do you have root permission?If you have ,you can go to data/data/termux to add some scripts.

**Comment by gushmazuko** [comment]
> I suggest you not run it on termux.
> Do you have root permission?If you have ,you can go to data/data/termux to add some scripts.

Root is not needed for Metasploit

**Comment by jebbieh** [comment]
Msfconsole ... Command not found, after install. Having issues loading framework on either terminal from this location.

**Comment by gushmazuko** [comment]
> Msfconsole ... Command not found, after install. Having issues loading framework on either terminal from this location.

Reinstall it, i have tested on many devices.
