### ISSUE TITLE
Unable to install packages in termux due to metasploit install

### ISSUE THREAD

**Issue by Destrocto01** [gushmazuko/metasploit_in_termux#45]
When i install any package with pkg install or with apt install it just says

W: GPG error: https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master gushmazuko InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 46C9F2CB506F14B4

and then terminates saying

N: Updating from such a repository can't be done securely, and is therefore disabled by default.

It wasn't a problem before installing metasploit framework.

Thanks for the help in advance.

**Comment by james123-la** [comment]
Yes, how can i fix it
