### ISSUE TITLE
'bundle install' not work

### ISSUE THREAD

**Issue by m0ssy-h3lo** [gushmazuko/metasploit_in_termux#5]
$ msfconsole
Could not find rake-12.3.3 in any of the sources
Run `bundle install` to install missing gems.
$ bundle install
Could not locate Gemfile

**Comment by ali8769** [comment]
Just go into the metasploit dirrctory where it is installed and type "bundle install" it will do the honours 
I got it cleared try once

**Comment by gushmazuko** [comment]
Updated
