### ISSUE TITLE
Metasploit is not properly installed

### ISSUE THREAD

**Issue by on1on-hub** [gushmazuko/metasploit_in_termux#59]
While installing metasploit on the process of Resolving dependencies : there's a error occurred
"Bundler could not find compatible versions for gem "concurrent-ruby":
  In snapshot (Gemfile.lock):
    concurrent-ruby (>= 1.0.5)"

And after this 
I use command postgresql_ctl.sh start
The it say "$ ./postgresql_ctl.sh start
pg_ctl: another server might be running; trying to start server anyway
waiting for server to start....2021-08-17 21:36:11.378 IST [3145] FATAL:  lock file "postmaster.pid" already exists
2021-08-17 21:36:11.378 IST [3145] HINT:  Is another postmaster (PID 31787) running in data directory "/data/data/com.termux/files/usr/var/lib/postgresql"?
 stopped waiting
pg_ctl: could not start server
Examine the log output."

And when when i want to start msfconsole then again a error occur said "run `bundle install` to install missing gems.
![Screenshot_2021-08-17-21-38-24-104_com termux](https://user-images.githubusercontent.com/69275035/129763029-98e2091a-33a3-434c-8074-ae87330ad42d.jpg)
![Screenshot_2021-08-17-21-38-11-361_com termux](https://user-images.githubusercontent.com/69275035/129763083-0a471226-808a-4af7-b5da-8b2fba208e90.jpg)
![Screenshot_2021-08-17-21-38-17-730_com termux](https://user-images.githubusercontent.com/69275035/129763124-2091113f-9517-4785-a1dd-1c5019c80179.jpg)

**Comment by Honkerboy06** [comment]
Try manual way. @on1on-hub

**Comment by Imango2518** [comment]
Me too same problem

**Comment by gushmazuko** [comment]
Try this https://github.com/gushmazuko/metasploit_in_termux/issues/62#issuecomment-903749537

**Comment by on1on-hub** [comment]
> Try this [#62 (comment)](https://github.com/gushmazuko/metasploit_in_termux/issues/62#issuecomment-903749537)

I tried that

**Comment by gushmazuko** [comment]
Fixed with update: https://github.com/gushmazuko/metasploit_in_termux/commit/0da057186c1fe57d6d1cb461a123eab600725ca7

**Comment by Pro100rus32** [comment]
Not fixed*
