### ISSUE TITLE
Msfconsole

### ISSUE THREAD

**Issue by bydariogamer** [gushmazuko/metasploit_in_termux#6]
There was a problem during installation. I left the installer finish and it did it successfully. When I type msfconsole I received a message alerting there wasn't a file where it should be. I've tried to uninstall and reinstall. I've tried even to redownload the package. If realized I need Ruby installed so I type
pkg install ruby
And there was no error during installation. I typed msfconsole... Another anoying error about the Ruby version, that I don't know how to fix (maybe installing the 1.7 version, but that's not an actual solution).
What can I do? I don't know how to patch it.

The terminal the terminal error output, and hardware and system info:

```
$ msfconsole

[!] There was an error parsing `Gemfile`:
[!] There was an error while loading `grpc.gemspec`: cannot load such file -- grpc/version
Does it try to require a relative path? That's been removed in Ruby 1.9. Bundler cannot continue.

 #  from /data/data/com.termux/files/home/metasploit-framework/grpc.gemspec:4
 #  -------------------------------------------
 #  $LOAD_PATH.push File.expand_path('../src/ruby/lib', __FILE__)
 >  require 'grpc/version'
 #
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /data/data/com.termux/files/home/metasploit-framework/Gemfile:4
 #  -------------------------------------------
 #  #   spec.add_runtime_dependency '<name>', [<version requirements>]
 >  gemspec name: 'metasploit-framework'
 #
 #  -------------------------------------------
```

I'm using a SM-J710FN with the last Android version available for this model: 8.1, and security patch 1 nov 2019

Please explain me how to fix it (in the improbable case in which I discover how to do it work I'll commit here).
Contact me to the email attached to this account (bydariobc03@gmail.com)

**Comment by gushmazuko** [comment]
Fixed
