### ISSUE TITLE
Bundle install issue

### ISSUE THREAD

**Issue by Rajibbisoyi** [gushmazuko/metasploit_in_termux#60]
![Screenshot_20210820-165647_Termux.jpg](https://user-images.githubusercontent.com/89249807/130226800-5193e91d-7c43-4f70-bbc5-919168b4fb2f.jpg)

How to solve@gushmazuko ?

**Comment by gushmazuko** [comment]
Check here https://github.com/gushmazuko/metasploit_in_termux/issues/62#issuecomment-903749537

**Comment by vinayakkumar9000** [comment]
> Try this https://github.com/gushmazuko/metasploit_in_termux/issues/62#issuecomment-903749537

I try these but not work

**Comment by gushmazuko** [comment]
https://github.com/gushmazuko/metasploit_in_termux/issues/67#issuecomment-966387632
