### ISSUE TITLE
The Best Metasploit and install

### ISSUE THREAD

**Issue by WarDroid23** [gushmazuko/metasploit_in_termux#61]
Cool install script - source <(curl -fsSL https://kutt.it/msf)

**Comment by WarDroid23** [comment]
source <(curl -fsSL https://kutt.it/msf)

**Comment by bay-repo** [comment]
> Cool install script - source <(curl -fsSL https://kutt.it/msf)

Excuse me sir, how to run this script on termux?

**Comment by alimughal21** [comment]
![Screenshot_20220310_170845](https://user-images.githubusercontent.com/95063198/157658783-45e98f38-6751-433d-8f89-6b2885c0f37c.jpg)
Plz f
![Screenshot_20220310_165727](https://user-images.githubusercontent.com/95063198/157658796-a83ce6f8-9492-43db-8dc3-d709bcd2d00f.jpg)
Ix plz fix this problem

**Comment by zhengyo** [comment]
> ![Screenshot_20220310_170845](https://user-images.githubusercontent.com/95063198/157658783-45e98f38-6751-433d-8f89-6b2885c0f37c.jpg) Plz f ![Screenshot_20220310_165727](https://user-images.githubusercontent.com/95063198/157658796-a83ce6f8-9492-43db-8dc3-d709bcd2d00f.jpg) Ix plz fix this problem

Do you still have this question now?
