### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ashrry** [gushmazuko/metasploit_in_termux#66]
**Important**
The following signatures couldn't be verified because the public key is not available
**Describe the bug**
pkg update not properly work
W: GPG error: https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master gushmazuko InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 46C9F2CB506F14B4
E: The repository 'https://github.com/gushmazuko/metasploit_in_termux/raw/master gushmazuko InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

**Screenshots**
![Screenshot_2021-10-06-12-40-26-831_com termux](https://user-images.githubusercontent.com/51499053/136157091-20e68eb7-9997-49c2-9fca-64c6c2aa28c8.jpg)

**Smartphone (please complete the following information):**
 - Device: [e.g. resmi 9 power]
 - OS: [e.g. Android 10]

**Comment by gushmazuko** [comment]
@ashrry If you no longer need the gushmazuko repository, you can delete it by:
```bash
rm $PREFIX/etc/apt/sources.list.d/gushmazuko.list
```

Otherwise, run the command:
```bash
pkg install -y gnupg

curl -fsSL https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master/gushmazuko-gpg.pubkey | gpg --dearmor | tee $PREFIX/etc/apt/trusted.gpg.d/gushmazuko-repo.gpg
```

**Comment by gushmazuko** [comment]
Fixed with update: https://github.com/gushmazuko/metasploit_in_termux/commit/0da057186c1fe57d6d1cb461a123eab600725ca7

**Comment by ZyrowKun** [comment]
@gushmazuko How do I fix this problem
![Screenshot_2022-03-02-18-12-14-288_com termux](https://user-images.githubusercontent.com/100487976/156363703-c4c9a9da-4b80-4e2d-bc04-65bafbea867e.jpg)



Thankyou.

**Comment by osama-bilal** [comment]
👍👍
