### ISSUE TITLE
[BUG]msf console command not found

### ISSUE THREAD

**Issue by sahil271205** [gushmazuko/metasploit_in_termux#67]
**Important**
Do not duplicate, search your issue before creating one!

**Describe the bug**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 8]
 - OS: [e.g. Android 10]
Realme narazo
Android 12

**Comment by gushmazuko** [comment]
Fixed with update: https://github.com/gushmazuko/metasploit_in_termux/commit/0da057186c1fe57d6d1cb461a123eab600725ca7

**Comment by RyuHard** [comment]
[!] There was an error parsing `Gemfile`: No such file or directory - getcwd. Bundler cannot continue.

 #  from /data/data/com.termux/files/home/metasploit-framework/Gemfile:4
 #  -------------------------------------------
 #  #   spec.add_runtime_dependency '<name>', [<version requirements>]
 >  gemspec name: 'metasploit-framework'
