### ISSUE TITLE
Me showing error wilw using ./postgresql_ctl.sh start command 

### ISSUE THREAD

**Issue by rushikeshnarule** [gushmazuko/metasploit_in_termux#68]
Me showing command not found command 😔
./postgresql_ctl.sh start
![Screenshot_2021-10-28-19-35-41-85_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/75885428/139272329-d78337d7-4153-44a7-a907-baec19aa6bdc.jpg)

**Comment by gushmazuko** [comment]
Fixed with update: https://github.com/gushmazuko/metasploit_in_termux/commit/0da057186c1fe57d6d1cb461a123eab600725ca7
