### ISSUE TITLE
dpkg source list (question)

### ISSUE THREAD

**Issue by Craglitch** [gushmazuko/metasploit_in_termux#70]
is this dpkg source list is same like from termux original one ?
![IMG_20211111_171308](https://user-images.githubusercontent.com/83074053/141270950-5fb59a7a-899e-44c7-aed2-d16054e1e037.jpg)

**Comment by gushmazuko** [comment]
This script does not change anything in the termux repository except adding `gushmazuko.list`: https://github.com/gushmazuko/metasploit_in_termux/blob/master/metasploit.sh#L34

**Comment by Craglitch** [comment]
oh ok thanks for answering
