### ISSUE TITLE
Metasploit ruby 3 + + is supported

### ISSUE THREAD

**Issue by Craglitch** [gushmazuko/metasploit_in_termux#72]
![IMG_20211115_093448](https://user-images.githubusercontent.com/83074053/141708931-63cdf010-7f2d-4fa2-9df8-9462bd5065bc.jpg)
i have try metasploit with ruby3 its working and no error output 

First install package need to use for installation like git, postgresql dll

### INSTALLING METASPLOIT-FRAMEWORK
```
cd $PREFIX/share
git clone https://github.com/rapid7/metasploit-framework.git --depth=1

# link msfconsole and msfvenom to usr/bin
cd metasploit-framework
ln -s $PREFIX/share/metasploit-framework/msfconsole $PREFIX/bin

ln -s $PREFIX/share/metasploit-framework/msfvenom $PREFIX/bin

```

### INSTALLATION AND COMPILING RUBY 3 
```
pkg install ruby
cd $HOME/metasploit-framework
sed '/rbnacl/d' -i Gemfile.lock
sed '/rbnacl/d' -i metasploit-framework.gemspec
gem install bundler
sed 's|nokogiri (1.*)|nokogiri (1.8.0)|g' -i Gemfile.lock

# nokogiri version
gem install nokogiri -v 1.8.0 -- --use-system-libraries
gem install actionpack
bundle update activesupport
bundle update --bundler
bundle install -j$(nproc --all)

$PREFIX/bin/find -type f -executable -exec termux-fix-shebang \{\} \;


```
![IMG_20211115_093448](https://user-images.githubusercontent.com/83074053/141708892-e31b71ea-d7fe-4dc1-8f72-8bf9a0b6ede7.jpg)
![IMG_20211115_093435](https://user-images.githubusercontent.com/83074053/141708902-b99774be-595f-4aba-b302-2a704d58bb0a.jpg)
compiling done

**Comment by Craglitch** [comment]
> i have try metasploit with ruby3 its working and no error output
> 
> First install package need to use for installation like git, postgresql dll
> 
> ### INSTALLING METASPLOIT-FRAMEWORK
> ```
> cd $PREFIX/share
> git clone https://github.com/rapid7/metasploit-framework.git --depth=1
> 
> # link msfconsole and msfvenom to usr/bin
> cd metasploit-framework
> ln -s $PREFIX/share/metasploit-framework/msfconsole $PREFIX/bin
> 
> ln -s $PREFIX/share/metasploit-framework/msfvenom $PREFIX/bin
> ```
> 
> ### INSTALLATION AND COMPILING RUBY 3
> ```
> pkg install ruby
> cd $HOME/metasploit-framework
> sed '/rbnacl/d' -i Gemfile.lock
> sed '/rbnacl/d' -i metasploit-framework.gemspec
> gem install bundler
> sed 's|nokogiri (1.*)|nokogiri (1.8.0)|g' -i Gemfile.lock
> 
> # nokogiri version
> gem install nokogiri -v 1.8.0 -- --use-system-libraries
> gem install actionpack
> bundle update activesupport
> bundle update --bundler
> bundle install -j$(nproc --all)
> 
> $PREFIX/bin/find -type f -executable -exec termux-fix-shebang \{\} \;
> rm ./modules/auxiliary/gather/http_pdf_authors.rb
> ```
> 
> compiling done

Nokogiri version install to 1.12.5

**Comment by Craglitch** [comment]
https://github.com/Craglitch/metasploit-in-termux-craglitch-version-

**Comment by gushmazuko** [comment]
Yes, you can build with `ruby 3`, but with errors. And if you update the bundle after installation, `msf` will no longer start, so `ruby 3` is not yet supported.
