### ISSUE TITLE
Unable to install metasploit on phone properly

### ISSUE THREAD

**Issue by learnthetech** [gushmazuko/metasploit_in_termux#74]
Hi, I am installing metasploit in termux on android, but it showed installation complete, but when i type msfconcole, it showing many errors like "gem not found exception".
![WhatsApp Image 2021-12-05 at 10 20 55 AM (1)](https://user-images.githubusercontent.com/95562777/144740884-57ad0ed2-7022-4b4c-841b-8bb0de84fe42.jpeg)
![WhatsApp Image 2021-12-05 at 10 20 55 AM](https://user-images.githubusercontent.com/95562777/144740886-ad787c6b-a564-4cf2-b6ec-7d618bb64ac2.jpeg)

Smartphone:
 - Oneplus 8 PRO
 - Android 11

**Comment by gushmazuko** [comment]
@learnthetech Uninstall termux by clearing all files and install laterst version from https://f-droid.org/en/packages/com.termux/
. Version on Play Store  is outdated.
