### ISSUE TITLE
Getting this issue while running msfconsole

### ISSUE THREAD

**Issue by Privanic99041** [gushmazuko/metasploit_in_termux#77]
16: from ./msfconsole:17:in `<main>'
        15: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        14: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        13: from /data/data/com.termux/files/home/metasploit-framework/config/boot.rb:26:in `<top (required)>'
        12: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        11: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        10: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/setup.rb:10:in `<top (required)>'
         9: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/ui/shell.rb:88:in `silence'
         8: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/ui/shell.rb:136:in `with_level'
         7: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/setup.rb:10:in `block in <top (required)>'
         6: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler.rb:149:in `setup'
         5: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/runtime.rb:22:in `setup'
         4: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/shared_helpers.rb:76:in `set_bundle_environment'
         3: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/shared_helpers.rb:297:in `set_bundle_variables'
         2: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/bundler/rubygems_integration.rb:223:in `bin_path'
         1: from /data/data/com.termux/files/usr/lib/ruby/2.7.0/rubygems.rb:254:in `bin_path'
/data/data/com.termux/files/usr/lib/ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe': Could not find 'bundler' (2.3.4) required by your /data/data/com.termux/files/home/metasploit-framework/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.3.4`

**Comment by bay-repo** [comment]
I have a same trouble sir

**Comment by ayanfaizal** [comment]
Same issue
