### ISSUE TITLE
/data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:35:in `require': cannot load such file -- net/smtp (LoadError)

### ISSUE THREAD

**Issue by Rocky8088** [gushmazuko/metasploit_in_termux#80]
**Important**
Do not duplicate, search your issue before creating one!

**Describe the bug**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 8]
 - OS: [e.g. Android 10]

**Comment by Rocky8088** [comment]
Anyone know how to fix this issue

**Comment by Rocky8088** [comment]
![Uploading Screenshot_2022-01-16-06-28-32-60.jpg…]()

**Comment by skycat2216** [comment]
https://github.com/gushmazuko/metasploit_in_termux/issues/100
I know it looks like spamming,but it's worthy to try
