### ISSUE TITLE
I can't load metasploit

### ISSUE THREAD

**Issue by AnubisTwine** [gushmazuko/metasploit_in_termux#81]
msfconsole
/data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)                                              from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.1-aarch64-linux/lib/nokogiri/extension.rb:30:in `rescue in <top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.1-aarch64-linux/lib/nokogiri/extension.rb:4:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.1-aarch64-linux/lib/nokogiri.rb:10:in `require_relative'                                    from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.1-aarch64-linux/lib/nokogiri.rb:10:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework.rb:13:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:73:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:73:in `rescue in block in require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:51:in `block in require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:44:in `each'                                                         from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:44:in `require'                                                      from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler.rb:176:in `require'                                                             from /data/data/com.termux/files/home/metasploit-framework/config/application.rb:10:in `<top (required)>'
        from /data/data/com.termux/files/home/metasploit-framework/config/environment.rb:2:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/config/environment.rb:2:in `<top (required)>'        from /data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:17:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:17:in `<top (required)>'               from /data/data/com.termux/files/usr/bin/msfconsole:18:in `require'
        from /data/data/com.termux/files/usr/bin/msfconsole:18:in `<main>'                                      /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.1-aarch64-linux/lib/nokogiri/extension.rb:7:in `require_relative': dlopen failed: library "libm.so.6" not found: needed by /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.1-aarch64-linux/lib/nokogiri/3.1/nokogiri.so in namespace (default) - /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.1-aarch64-linux/lib/nokogiri/3.1/nokogiri.so (LoadError)
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.1-aarch64-linux/lib/nokogiri/extension.rb:7:in `<top (required)>'                           from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.1-aarch64-linux/lib/nokogiri.rb:10:in `require_relative'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.1-aarch64-linux/lib/nokogiri.rb:10:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'                                 from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'                        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'                                 from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework.rb:13:in `<top (required)>'                                                         from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:73:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:73:in `rescue in block in require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:51:in `block in require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:44:in `each'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:44:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler.rb:176:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/config/application.rb:10:in `<top (required)>'
        from /data/data/com.termux/files/home/metasploit-framework/config/environment.rb:2:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/config/environment.rb:2:in `<top (required)>'        from /data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:17:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:17:in `<top (required)>'
        from /data/data/com.termux/files/usr/bin/msfconsole:18:in `require'
        from /data/data/com.termux/files/usr/bin/msfconsole:18:in `<main>'                                      /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:60:in `require': cannot load such file -- metasploit-framework (LoadError)        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:55:in `each'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:55:in `block in require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:44:in `each'                                                         from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:44:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler.rb:176:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/config/application.rb:10:in `<top (required)>'
        from /data/data/com.termux/files/home/metasploit-framework/config/environment.rb:2:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/config/environment.rb:2:in `<top (required)>'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:17:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:17:in `<top (required)>'
        from /data/data/com.termux/files/usr/bin/msfconsole:18:in `require'
        from /data/data/com.termux/files/usr/bin/msfconsole:18:in `<main>'
/data/data/com.termux/files/usr/bin/msfconsole: warning: Exception in finalizer #<Proc:0x0000007d330e8548 /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.0.5/lib/concurrent/atomic/ruby_thread_local_var.rb:85>
/data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.0.5/lib/concurrent/atomic/ruby_thread_local_var.rb:86:in `new': can't alloc thread (ThreadError)
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.0.5/lib/concurrent/atomic/ruby_thread_local_var.rb:86:in `block in threadlocal_finalizer'
/data/data/com.termux/files/usr/bin/msfconsole: warning: Exception in finalizer #<Proc:0x0000007d330e86d8 /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.0.5/lib/concurrent/atomic/ruby_thread_local_var.rb:85>
/data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.0.5/lib/concurrent/atomic/ruby_thread_local_var.rb:86:in `new': can't alloc thread (ThreadError)                                                             from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.0.5/lib/concurrent/atomic/ruby_thread_local_var.rb:86:in `block in threadlocal_finalizer'

**Comment by ivam3** [comment]
remove all nokogiri versions ::: gem uninstall nokogiri ::: and reinstall it with ::: gem install nokogiri --platform=ruby -- --use-system-libraries :::
