### ISSUE TITLE
/data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:35:in `require': cannot load such file -- net/smtp (LoadError)[BUG]

### ISSUE THREAD

**Issue by EMPEROR-OF-WORLD** [gushmazuko/metasploit_in_termux#85]
**Important**
Do not duplicate, search your issue before creating one!

**Describe the bug**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. redmi note 4]
 - OS: [e.g. Android 7]
![Screenshot_2022-01-24-08-48-25-360_com termux](https://user-images.githubusercontent.com/97828787/150722260-594ec1eb-711b-4ade-ac7a-3cfb2b7d32c9.jpg)

**Comment by EMPEROR-OF-WORLD** [comment]
help

**Comment by rffj** [comment]
when i download metasploit he giveing mee these error Bundler could not find compatible versions for gem "mini_portile2":
  In snapshot (Gemfile.lock):
    mini_portile2 (= 2.7.1)

  In Gemfile:
    metasploit-framework was resolved to 6.1.27, which depends on
      nokogiri was resolved to 1.8.0, which depends on
        mini_portile2 (~> 2.2.0)

Running `bundle update` will rebuild your snapshot from scratch, using
only
the gems in your Gemfile, which may resolve the conflict.

**Comment by rffj** [comment]
I do bundle update but not fix 
And when i run msfconole metasploit was not open help bro

**Comment by rffj** [comment]
> help
yes also i have these error

**Comment by dedshit** [comment]
> > help
> > yes also i have these error

check my pr
