### ISSUE TITLE
Metasploit Not Install Properly Or Error 

### ISSUE THREAD

**Issue by GauravShekhawat01** [gushmazuko/metasploit_in_termux#86]
![Screenshot_2022_0127_230459](https://user-images.githubusercontent.com/69868927/151412785-29b789f1-abda-4a24-a528-84a50271750b.jpg)
Please Check the problem And Give Me solution For this error

**Comment by Henilvanpariya03** [comment]
Same problem

**Comment by multik09876** [comment]
Same problem too
