### ISSUE TITLE
Errors because ruby is upgraded to v3.1.0, and this metasploit-framework requires ruby v2.7.0 or less maybe that's why it's not working?

### ISSUE THREAD

**Issue by manavsemwal** [gushmazuko/metasploit_in_termux#87]
![Screenshot_2022-01-28-21-25-58-38](https://user-images.githubusercontent.com/85974882/151602914-3dae4e8a-e966-4aa7-aa07-e94e59d624f7.jpg)

**Comment by ganeshkamal-ar** [comment]
I also have the same problem anyone please help me 🤧

**Comment by Yurisky080** [comment]
**I thought I was the only one having this problem, we need help, fixing metasploit to run with ruby v3.1.0**

**Comment by dedshit** [comment]
thats not the problem

**Comment by its-me-Hadee** [comment]
yes I have same problem  while instaling meta......☹☹😫 plz help anyone

**Comment by meybar2021** [comment]
Am also facing this problem in loading metasoit

**Comment by skycat2216** [comment]
https://github.com/gushmazuko/metasploit_in_termux/issues/100
This might help
