### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kalien-parrien** [gushmazuko/metasploit_in_termux#90]
**Describe the bug**
Running msfconsole I'm getting the errors i pasted below 

**Screenshots**

~ $ **msfconsole**
/data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require': cannot load such file -- net/smtp (LoadError)
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/lib/rex/proto/mms/model.rb:21:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:27:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:27:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `cget'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:237:in `block (2 levels) in eager_load'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `ls'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:232:in `block in eager_load'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `synchronize'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `eager_load'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `each'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `eager_load_all'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/railties-6.1.4.4/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/railties-6.1.4.4/lib/rails/initializable.rb:32:in `instance_exec'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/railties-6.1.4.4/lib/rails/initializable.rb:32:in `run'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/railties-6.1.4.4/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/tsort.rb:347:in `each'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/tsort.rb:347:in `call'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/railties-6.1.4.4/lib/rails/initializable.rb:60:in `run_initializers'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/railties-6.1.4.4/lib/rails/application.rb:391:in `initialize!'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/railties-6.1.4.4/lib/rails/railtie.rb:207:in `public_send'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/railties-6.1.4.4/lib/rails/railtie.rb:207:in `method_missing'
        from /data/data/com.termux/files/home/metasploit-framework/config/environment.rb:4:in `<top (required)>'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:17:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:17:in `<top (required)>'
        from /data/data/com.termux/files/usr/bin/msfconsole:18:in `require'
        from /data/data/com.termux/files/usr/bin/msfconsole:18:in `<main>'
/data/data/com.termux/files/usr/bin/msfconsole: warning: Exception in finalizer #<Proc:0xf1b24278 /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.0.5/lib/concurrent/atomic/ruby_thread_local_var.rb:85>
/data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:471:in `new': can't alloc thread (ThreadError)
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:471:in `create_with_logging_context'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:436:in `new'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.0.5/lib/concurrent/atomic/ruby_thread_local_var.rb:86:in `block in threadlocal_finalizer'
/data/data/com.termux/files/usr/bin/msfconsole: warning: Exception in finalizer #<Proc:0xf1b24660 /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.0.5/lib/concurrent/atomic/ruby_thread_local_var.rb:85>
/data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:471:in `new': can't alloc thread (ThreadError)
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:471:in `create_with_logging_context'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:436:in `new'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.0.5/lib/concurrent/atomic/ruby_thread_local_var.rb:86:in `block in threadlocal_finalizer'

**Smartphone (please complete the following information):**
 - Device: [SamsungTab A 6 2016]
 - OS: [8.0.1]

**Additional** **information**:
$ **termux-info**
**Application version:
0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
Updatable packages:
All packages up to date
Android version:
8.1.0
Kernel build information:
Linux localhost 3.18.14-17282421 #1 SMP PREEMPT Wed Sep 15 20:19:16 KST 2021 armv8l Android
Device manufacturer:
samsung
Device model:
SM-T585**

**Comment by dedshit** [comment]
just add **net-smtp** in gemspec

**Comment by gushmazuko** [comment]
To this: https://github.com/gushmazuko/metasploit_in_termux/issues/99#issuecomment-1059196285
