### ISSUE TITLE
$msfconsole /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require': cannot load such file -- net/smtp (LoadError)

### ISSUE THREAD

**Issue by wildan444** [gushmazuko/metasploit_in_termux#92]
**Important**
Do not duplicate, search your issue before creating one!

**Describe the bug**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 8]
 - OS: [e.g. Android 10]

**Comment by Theworld15** [comment]
Hi, I managed to solve the error by changing the repository.

termux-change-repo
I used the repository grimler so I managed to run msfconsole

**Comment by Theworld15** [comment]
![Screenshot_20220220-141429](https://user-images.githubusercontent.com/95457825/154862612-e94206ae-d2ab-4883-be80-6a18c697d407.png)

**Comment by wildan444** [comment]
> ![Tangkapan layar_2220220-141429](https://user-images.githubusercontent.com/95457825/154862612-e94206ae-d2ab-4883-be80-6a18c697d407.png)

command?

**Comment by wildan444** [comment]
> ![Screenshot_20220220-141429](https://user-images.githubusercontent.com/95457825/154862612-e94206ae-d2ab-4883-be80-6a18c697d407.png)

Not work

**Comment by Theworld15** [comment]
> 

true uninstall termux to check if that was the solution but try and still get the error

**Comment by Theworld15** [comment]
![Screenshot_20220227-134607](https://user-images.githubusercontent.com/95457825/155897515-ae79697e-db9f-453e-b3cb-bcb5469c3a92.png)

**Comment by dedshit** [comment]
add net-smtp in gemspec

**Comment by Theworld15** [comment]
> add net-smtp in gemspec

how do i do it?

**Comment by srii15** [comment]
Bro how did you done that

**Comment by Theworld15** [comment]
> I have same problem help me I am so tired of this error

https://github.com/dedshit/metasploit_in_termux

**Comment by srii15** [comment]
Again i need to install??

**Comment by skycat2216** [comment]
https://github.com/mikel/mail/pull/1439

this might help

**Comment by dedshit** [comment]
> Again i need to install??

just check my pr then modify urself

**Comment by srii15** [comment]
Where do i get your program

**Comment by gushmazuko** [comment]
To this: https://github.com/gushmazuko/metasploit_in_termux/issues/99#issuecomment-1059196285

**Comment by Prince01github** [comment]
> ![Screenshot_20220228-102941](https://user-images.githubusercontent.com/95457825/156020542-37ce2019-d6d2-4c30-b859-941033ff7528.png)
> 
> Thank you

How to solve this problem bro

**Comment by dedshit** [comment]
> > ![Screenshot_20220228-102941](https://user-images.githubusercontent.com/95457825/156020542-37ce2019-d6d2-4c30-b859-941033ff7528.png)
> > Thank you
> 
> How to solve this problem bro

seems no problem

**Comment by Theworld15** [comment]
hello

To solve the error, although it will continue to give some errors, we can execute msfconsole and eliminate metasploit

rm -rf metasploit-framework

This only if they installed it previously, once metasploit is removed we will execute the script with dedshit solution

git clone https://github.com/dedshit/metasploit_in_termux
chmod 777 metasploit.sh
./metasploit.sh

when finished we can run msfconsole

**Comment by dedshit** [comment]
> hello
> 
> To solve the error, although it will continue to give some errors, we can execute msfconsole and eliminate metasploit
> 
> rm -rf metasploit-framework
> 
> This only if they installed it previously, once metasploit is removed we will execute the script with dedshit solution
> 
> git clone https://github.com/dedshit/metasploit_in_termux chmod 777 metasploit.sh ./metasploit.sh
> 
> when finished we can run msfconsole


Try my [Gist](https://gist.github.com/dedshit/86bbd45c98c155ebda0a0ff706455531)

All warnings were removed  gud luck

credit : gushmazuko

**Comment by Theworld15** [comment]
> > hello
> > 
> > To solve the error, although it will continue to give some errors, we can execute msfconsole and eliminate metasploit
> > 
> > rm -rf metasploit-framework
> > 
> > This only if they installed it previously, once metasploit is removed we will execute the script with dedshit solution
> > 
> > git clone https://github.com/dedshit/metasploit_in_termux chmod 777 metasploit.sh ./metasploit.sh
> > 
> > when finished we can run msfconsole
> 
> 
> Try my [Gist](https://gist.github.com/dedshit/86bbd45c98c155ebda0a0ff706455531)
> 
> All warnings were removed  gud luck
> 
> credit : gushmazuko

it worked no longer there is any warning i think this problem is already solved

**Comment by dedshit** [comment]
> > > hello
> > > To solve the error, although it will continue to give some errors, we can execute msfconsole and eliminate metasploit
> > > rm -rf metasploit-framework
> > > This only if they installed it previously, once metasploit is removed we will execute the script with dedshit solution
> > > git clone https://github.com/dedshit/metasploit_in_termux chmod 777 metasploit.sh ./metasploit.sh
> > > when finished we can run msfconsole
> > 
> > 
> > Try my [Gist](https://gist.github.com/dedshit/86bbd45c98c155ebda0a0ff706455531)
> > All warnings were removed  gud luck
> > credit : gushmazuko
> 
> It worked, there is no warning anymore, I think this problem is already fixed

during msfvenom payload generation & msfconsole exit weird error will occur 

but not a problem its solved

**Comment by gushmazuko** [comment]
Fixed https://github.com/gushmazuko/metasploit_in_termux/commit/280f656e1dfc0ef8a866218346d3db651e87aac3

**Comment by Risovk** [comment]
git clone https://github.com/dedshit/metasploit_in_termux
chmod 777 metasploit.sh
./metasploit.sh
I put this command but I don't get results

**Comment by Risovk** [comment]
I have uninstall termux and download again but same result

**Comment by gushmazuko** [comment]
In order to have updated Termux:
- **Purge all data** of `Termux` in Android Settings
- Uninstall and reinstall latest Termux version from [F-Droid](https://f-droid.org/en/packages/com.termux/) (Version on Play Store is outdated)
- Then launch Termux to initialization, close it (force stop, not swap)
- Reopen and execute:
```bash
source <(curl -fsSL https://kutt.it/msf)
```
