### ISSUE TITLE
eror msf

### ISSUE THREAD

**Issue by kazuyagodsz** [gushmazuko/metasploit_in_termux#94]
I have a problem with this please fix it
![IMG_20220226_090419](https://user-images.githubusercontent.com/95276471/155824805-d1bf99eb-7a68-44c7-9bb9-ce9c0ad7d6e8.jpg)

**Comment by gushmazuko** [comment]
To this: https://github.com/gushmazuko/metasploit_in_termux/issues/99#issuecomment-1059196285
