### ISSUE TITLE
[BUG] click here [BUG]

### ISSUE THREAD

**Issue by wildan444** [gushmazuko/metasploit_in_termux#95]
Device realme
OS Android 11
![Screenshot_20220227-000202](https://user-images.githubusercontent.com/62401430/155852311-e1df4a5c-4cad-4f1c-a9bd-bef020f5a8eb.png)

![Screenshot_20220226-235315](https://user-images.githubusercontent.com/62401430/155852369-199ca464-0f5a-4c6a-a1b3-54a51d58014f.png)

**Comment by gushmazuko** [comment]
To this: https://github.com/gushmazuko/metasploit_in_termux/issues/99#issuecomment-1059196285
