### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Karthi02116K** [gushmazuko/metasploit_in_termux#96]
![Uploading Screenshot_2022-02-27-19-57-27-36_84d3000e3f4017145260f7618db1d683.jpg…]()

**Comment by gushmazuko** [comment]
Try to 
- **Purge all data** of Termux in Android Settings
- Uninstall and reinstall latest Termux version
- Then launch Termux to initialization, close it (force stop, not swap).
 - Reopen and launch installation of Metasploit with:
```bash
source <(curl -fsSL https://kutt.it/msf)
```
