### ISSUE TITLE
OpenSSL metasploit error

### ISSUE THREAD

**Issue by anandaps2** [gushmazuko/metasploit_in_termux#99]
**Important**
Openssl error. I tried to install with ruby and latest open ssl. It is not working.

**Describe the bug**
Could not load openssl,
Dpkg-deb: error: paste sub process was killed by signal(Broken pipe)

**Screenshots**
![photo_2022-02-28_21-07-24](https://user-images.githubusercontent.com/25984276/156014353-119a85b9-fd3b-4bbf-8c5c-a384c585b0e9.jpg)
![photo_2022-02-28_11-52-04](https://user-images.githubusercontent.com/25984276/156014365-d0571042-6892-4461-b6f0-32a1aaee47b3.jpg)
![photo_2022-02-28_10-50-23](https://user-images.githubusercontent.com/25984276/156014368-9e7745a4-8e3b-4545-b85e-80d562aeb8b6.jpg)

**Smartphone (please complete the following information):**
 - Device: [e.g. Realme 9 pro, noki and samsung]
 - OS: [e.g. Android 11]

**Comment by dedshit** [comment]
your termux version 0.117 right

**Comment by dedshit** [comment]
check my pr

**Comment by anandaps2** [comment]
termux-info
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24 stable main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.180-perf-gad2f9ca #1 SMP PREEMPT Sat Jan 29 14:47:56 CST 2022 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 9 Pro

**Comment by dedshit** [comment]
> termux-info Application version: 0.118.0 Packages CPU architecture: aarch64 Subscribed repositories: sources.list deb https://grimler.se/termux-packages-24 stable main Updatable packages: All packages up to date Android version: 11 Kernel build information: Linux localhost 4.14.180-perf-gad2f9ca #1 SMP PREEMPT Sat Jan 29 14:47:56 CST 2022 aarch64 Android Device manufacturer: Xiaomi Device model: Redmi Note 9 Pro


uninstall & reinstall

**Comment by ilyasky87** [comment]
Help me 2 plZ 

- 
![Screenshot_20220304-074729](https://user-images.githubusercontent.com/66322183/156701310-e064308d-9516-4b5b-9853-b3828c660e58.jpg)

**Comment by dedshit** [comment]
> Help me 2 plZ
> 
> 
> ![Screenshot_20220304-074729](https://user-images.githubusercontent.com/66322183/156701310-e064308d-9516-4b5b-9853-b3828c660e58.jpg)


install latest termux version . if already latest uninstall completely then reinstall it

**Comment by ilyasky87** [comment]
I have 0.118 and I tried to completely reinstall .. but the problem persisted

**Comment by ilyasky87** [comment]
![Screenshot_20220304-102745](https://user-images.githubusercontent.com/66322183/156718703-e25da261-6c19-428c-84e1-55804da5cfdd.jpg)
Now I have new bug ((

**Comment by gushmazuko** [comment]
Try to 
- **Purge all data** of Termux in Android Settings
- Uninstall and reinstall latest Termux version
- Then launch Termux to initialization, close it (force stop, not swap).
 - Reopen and launch installation of Metasploit with:
```bash
source <(curl -fsSL https://kutt.it/msf)
```

**Comment by anandaps2** [comment]
So far errors after following all the steps.

**Comment by anandaps2** [comment]
Not working with

**Comment by anandaps2** [comment]
Not working after following all the steps. all the errors I got so far.
![out](https://user-images.githubusercontent.com/25984276/156915138-cfec3483-336f-4e72-b395-8c84c162eed9.jpg)
.

**Comment by dedshit** [comment]
see 2nd screenshot and change according to that

**Comment by skycat2216** [comment]
run
pkg upgrade
Maintainers upgrade the openssl from 1.1 to 3.0
And they released new version to solve these problems

**Comment by gushmazuko** [comment]
Fixed https://github.com/gushmazuko/metasploit_in_termux/commit/280f656e1dfc0ef8a866218346d3db651e87aac3

**Comment by CyberKid1987** [comment]
Not working my friend. I test it now. Reinstall last termux via fdroid and run your single command.

**Comment by anandaps2** [comment]
![image](https://user-images.githubusercontent.com/25984276/158742992-c9c3c652-3d77-4e10-8edc-e2c9fbb381c6.png)
New error

**Comment by dedshit** [comment]
> ![image](https://user-images.githubusercontent.com/25984276/158742992-c9c3c652-3d77-4e10-8edc-e2c9fbb381c6.png) New error



duplicate #111 @anandaps2

**Comment by CyberKid1987** [comment]
With manual install all works perfect, only auto has problem 🙂

**Comment by anandaps2** [comment]
Solution: Please copy paste the commands in your termux terminal mentioned below. It worked for me [Source](https://github.com/efxtv/Metasploit-in-termux)

<pre>cd metasploit-framework;
sed -i '13,15 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb;
clear;echo "Done...."</pre>

**Comment by dedshit** [comment]
> Solution: Please copy paste the commands in your termux terminal mentioned below. It worked for me [Source](https://github.com/efxtv/Metasploit-in-termux)
> 
> cd metasploit-framework;
> sed -i '13,15 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb;
> clear;echo "Done...."

No promotion 😑😑

**Comment by skycat2216** [comment]
Haev you installed Opnessl1.1?

**Comment by KaimanShin** [comment]
![Uploading Screenshot_20220619-091327_Termux.jpg…]()
Someone help me, I'm not able to open metasploit Whenever I use msfconsole it gives this, someone help me please

**Comment by KaimanShin** [comment]
/data/data/com.termux/files/home/metasploit-framework/metasploit-framework-6.0.27/lib/metasploit/framework/version.rb:33: warning: already initialized constant Metasploit::Framework::Version::VERSION
/data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/version.rb:33: warning: previous definition of VERSION was here
/data/data/com.termux/files/home/metasploit-framework/metasploit-framework-6.0.27/lib/metasploit/framework/version.rb:34: warning: already initialized constant Metasploit::Framework::Version::MAJOR
/data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/version.rb:34: warning: previous definition of MAJOR was here
/data/data/com.termux/files/home/metasploit-framework/metasploit-framework-6.0.27/lib/metasploit/framework/version.rb:34: warning: already initialized constant Metasploit::Framework::Version::MINOR
/data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/version.rb:34: warning: previous definition of MINOR was here
/data/data/com.termux/files/home/metasploit-framework/metasploit-framework-6.0.27/lib/metasploit/framework/version.rb:34: warning: already initialized constant Metasploit::Framework::Version::PATCH
/data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/version.rb:34: warning: previous definition of PATCH was here
/data/data/com.termux/files/home/metasploit-framework/metasploit-framework-6.0.27/lib/metasploit/framework/version.rb:35: warning: already initialized constant Metasploit::Framework::Version::PRERELEASE
/data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/version.rb:35: warning: previous definition of PRERELEASE was here
/data/data/com.termux/files/home/metasploit-framework/metasploit-framework-6.0.27/lib/metasploit/framework/version.rb:36: warning: already initialized constant Metasploit::Framework::Version::HASH
/data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/version.rb:36: warning: previous definition of HASH was here
/data/data/com.termux/files/home/metasploit-framework/metasploit-framework-6.0.27/lib/metasploit/framework/version.rb:39: warning: already initialized constant Metasploit::Framework::VERSION
/data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/version.rb:39: warning: previous definition of VERSION was here
/data/data/com.termux/files/home/metasploit-framework/metasploit-framework-6.0.27/lib/metasploit/framework/version.rb:40: warning: already initialized constant Metasploit::Framework::GEM_VERSION
/data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/version.rb:40: warning: previous definition of GEM_VERSION was here
/data/data/com.termux/files/home/metasploit-framework/metasploit-framework-6.0.27/lib/metasploit/framework/rails_version_constraint.rb:6: warning: already initialized constant Metasploit::Framework::RailsVersionConstraint::RAILS_VERSION
/data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/rails_version_constraint.rb:6: warning: previous definition of RAILS_VERSION was here
Could not find rake-13.0.6 in any of the sources
Run `bundle install` to install missing gems.

Someone help me, I'm not able to open metasploit Whenever I use msfconsole it gives this, someone help me please
